// src/pages/register/packages/PackageList.tsx
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Plus, Edit, Trash2, Eye, Package } from 'lucide-react'
import { Button } from '@/components/ui/button/button'
import SearchBar from '@/components/ui/search-bar/SearchBar'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from '@/components/ui/data-table/table'

// Mock data - substituir por dados reais da API
const mockPackages = [
  {
    id: 1,
    nome: 'Pacote Básico',
    tipo: 'Pacote',
    descricao: 'Buffet completo para até 50 pessoas',
    preco: 2500.00,
    duracao: '4 horas',
    status: 'Ativo',
    dataCadastro: '2024-01-15'
  },
  {
    id: 2,
    nome: 'Serviço de DJ',
    tipo: 'Serviço',
    descricao: 'DJ com equipamento completo',
    preco: 800.00,
    duracao: '6 horas',
    status: 'Ativo',
    dataCadastro: '2024-01-20'
  },
  {
    id: 3,
    nome: 'Decoração Premium',
    tipo: 'Serviço',
    descricao: 'Decoração completa para eventos especiais',
    preco: 1200.00,
    duracao: '8 horas',
    status: 'Inativo',
    dataCadastro: '2024-01-25'
  }
]

export default function PackageList() {
  const [packages] = useState(mockPackages)
  const [searchTerm, setSearchTerm] = useState('')
  const [filterType, setFilterType] = useState('todos')

  const filteredPackages = packages.filter(pkg => {
    const matchesSearch = pkg.nome.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         pkg.descricao.toLowerCase().includes(searchTerm.toLowerCase())
    const matchesType = filterType === 'todos' || pkg.tipo === filterType
    return matchesSearch && matchesType
  })

  const handleDelete = (id: number) => {
    // Implementar lógica de exclusão
    console.log('Excluir pacote:', id)
  }

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('pt-BR', {
      style: 'currency',
      currency: 'BRL'
    }).format(value)
  }

  return (
    <div className='space-y-6'>
      {/* Header */}
      <div className='flex items-center justify-between'>
        <div>
          <h1 className='text-3xl font-bold tracking-tight'>Pacotes e Serviços</h1>
          <p className='text-muted-foreground'>
            Gerencie os pacotes de buffet e serviços avulsos
          </p>
        </div>
        <Button variant='outline' asChild>
          <Link to='/cadastros/pacotes/novo'>
            <Plus className='mr-2 h-4 w-4' />
            Novo Pacote/Serviço
          </Link>
        </Button>
      </div>

      {/* Filtros */}
      <div className='flex items-center space-x-2'>
        <div className='flex-1'>
          <SearchBar
            placeholder='Buscar por nome ou descrição...'
            value={searchTerm}
            onChange={setSearchTerm}
          />
        </div>
        <select
          value={filterType}
          onChange={(e) => setFilterType(e.target.value)}
          className='flex h-10 w-48 items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50'
        >
          <option value='todos'>Todos os tipos</option>
          <option value='Pacote'>Pacotes</option>
          <option value='Serviço'>Serviços</option>
        </select>
      </div>

      {/* Tabela */}
      <div className='rounded-md border'>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Nome</TableHead>
              <TableHead>Tipo</TableHead>
              <TableHead>Descrição</TableHead>
              <TableHead>Preço</TableHead>
              <TableHead>Duração</TableHead>
              <TableHead>Status</TableHead>
              <TableHead className='text-right'>Ações</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filteredPackages.map((pkg) => (
              <TableRow key={pkg.id}>
                <TableCell className='font-medium'>
                  <div className='flex items-center space-x-2'>
                    <Package className='h-4 w-4 text-muted-foreground' />
                    <span>{pkg.nome}</span>
                  </div>
                </TableCell>
                <TableCell>
                  <span
                    className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${
                      pkg.tipo === 'Pacote'
                        ? 'bg-blue-100 text-blue-800'
                        : 'bg-purple-100 text-purple-800'
                    }`}
                  >
                    {pkg.tipo}
                  </span>
                </TableCell>
                <TableCell className='max-w-xs truncate'>{pkg.descricao}</TableCell>
                <TableCell className='font-medium'>{formatCurrency(pkg.preco)}</TableCell>
                <TableCell>{pkg.duracao}</TableCell>
                <TableCell>
                  <span
                    className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${
                      pkg.status === 'Ativo'
                        ? 'bg-green-100 text-green-800'
                        : 'bg-red-100 text-red-800'
                    }`}
                  >
                    {pkg.status}
                  </span>
                </TableCell>
                <TableCell className='text-right'>
                  <div className='flex items-center justify-end space-x-2'>
                    <Button variant='ghost' size='sm'>
                      <Eye className='h-4 w-4' />
                    </Button>
                    <Button variant='ghost' size='sm' asChild>
                      <Link to={`/cadastros/pacotes/editar/${pkg.id}`}>
                        <Edit className='h-4 w-4' />
                      </Link>
                    </Button>
                    <Button
                      variant='ghost'
                      size='sm'
                      onClick={() => handleDelete(pkg.id)}
                    >
                      <Trash2 className='h-4 w-4' />
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      {/* Paginação - implementar quando necessário */}
      {filteredPackages.length === 0 && (
        <div className='text-center py-8'>
          <p className='text-muted-foreground'>
            {searchTerm ? 'Nenhum pacote/serviço encontrado.' : 'Nenhum pacote/serviço cadastrado.'}
          </p>
        </div>
      )}
    </div>
  )
}

// src/app/features/register/packages/package-list/package-list.component.ts
import { Component, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { RouterModule } from '@angular/router'
import { FormsModule } from '@angular/forms'
import { LucideAngularModule, Plus, Edit, Trash2, Eye, Package } from 'lucide-angular'
import { firstValueFrom } from 'rxjs'

import { ButtonComponent } from '@shared/components/ui/button/button.component'
import { SearchBarComponent } from '@shared/components/ui/search-bar/search-bar.component'
import { ConfirmationModalComponent } from '@shared/components/ui/confirmation-modal/confirmation-modal.component'
import { 
  TableComponent, 
  TableHeaderComponent, 
  TableBodyComponent, 
  TableRowComponent, 
  TableHeadComponent, 
  TableCellComponent 
} from '@shared/components/ui/table/table.component'
import { PackageService } from '@core/services/package.service'
import type { Package as PackageType } from '@shared/models/api.types'
import { formatDateBR } from '@shared/utils/date.utils'

@Component({
  selector: 'app-package-list',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    FormsModule,
    LucideAngularModule,
    ButtonComponent,
    SearchBarComponent,
    ConfirmationModalComponent,
    TableComponent,
    TableHeaderComponent,
    TableBodyComponent,
    TableRowComponent,
    TableHeadComponent,
    TableCellComponent
  ],
  templateUrl: './package-list.component.html'
})
export class PackageListComponent implements OnInit {
  readonly PlusIcon = Plus
  readonly EditIcon = Edit
  readonly Trash2Icon = Trash2
  readonly EyeIcon = Eye
  readonly PackageIcon = Package

  packages: PackageType[] = []
  searchTerm: string = ''
  isLoading: boolean = true
  error: string = ''
  showDeleteModal: boolean = false
  packageToDelete: PackageType | null = null
  isDeleting: boolean = false

  constructor(private packageService: PackageService) {}

  /**
   * @Function - ngOnInit
   * @description - Initializes the component
   * @author - Vitor Hugo
   * @returns - Promise<void>
   */
  async ngOnInit(): Promise<void> {
    await this.loadData()
  }

  async loadData(): Promise<void> {
    try {
      this.isLoading = true
      this.error = ''
      const response = await firstValueFrom(this.packageService.getPackages())
      if (response.success && response.data) {
        this.packages = response.data
      } else {
        this.error = 'Erro ao carregar pacotes'
      }
    } catch (err: any) {
      this.error = err.message || 'Erro ao carregar pacotes'
    } finally {
      this.isLoading = false
    }
  }

  /**
   * @Function - filteredPackages
   * @description - Filters the packages based on the search term
   * @author - Vitor Hugo
   * @returns - PackageType[]
   */
  get filteredPackages(): PackageType[] {
    if (!this.searchTerm) {
      return this.packages
    }
    
    const searchLower = this.searchTerm.toLowerCase()
    return this.packages.filter(pkg =>
      pkg.name.toLowerCase().includes(searchLower) ||
      (pkg.description && pkg.description.toLowerCase().includes(searchLower))
    )
  }

  /**
   * @Function - handleDeleteClick
   * @description - Initiates the delete process by opening the confirmation modal and clearing previous errors
   * @author - Vitor Hugo
   * @param - pkg: PackageType - The package to be deleted
   * @returns - void
   */
  handleDeleteClick(pkg: PackageType): void {
    this.packageToDelete = pkg
    this.showDeleteModal = true
    this.error = '' // Clear previous errors
  }

  /**
   * @Function - handleConfirmDelete
   * @description - Handles the confirmation of package deletion with proper error handling for dependency constraints
   * @author - Vitor Hugo
   * @returns - Promise<void>
   */
  async handleConfirmDelete(): Promise<void> {
    if (!this.packageToDelete) return

    try {
      this.isDeleting = true
      const response = await firstValueFrom(
        this.packageService.deletePackage(this.packageToDelete.id)
      )
      if (response.success) {
        this.packages = this.packages.filter(pkg => pkg.id !== this.packageToDelete!.id)
        this.showDeleteModal = false
        this.packageToDelete = null
      } else {
        // Handle error from response when success is false
        this.error = response.message || response.errors?.[0] || 'Erro ao excluir pacote'
        this.showDeleteModal = false
        this.packageToDelete = null
      }
    } catch (err: any) {
      // Extract error message from HTTP error response
      if (err.error?.error?.message) {
        // Backend returned structured error with error.error.message
        this.error = err.error.error.message
      } else if (err.error?.message) {
        // Backend returned error with error.message
        this.error = err.error.message
      } else if (err.message) {
        // Generic error message
        this.error = err.message
      } else {
        // Fallback error message
        this.error = 'Erro ao excluir pacote'
      }
      // Close modal to show error message clearly
      this.showDeleteModal = false
      this.packageToDelete = null
    } finally {
      this.isDeleting = false
    }
  }

  /**
   * @Function - handleCancelDelete
   * @description - Handles the cancellation of package deletion
   * @author - Vitor Hugo
   * @returns - void
   */
  handleCancelDelete(): void {
    this.showDeleteModal = false
    this.packageToDelete = null
  }

  /**
   * @Function - formatCurrency
   * @description - Formats a currency value to a string
   * @author - Vitor Hugo
   * @returns - string
   */
  formatCurrency(value: number): string {
    return new Intl.NumberFormat('pt-BR', {
      style: 'currency',
      currency: 'BRL'
    }).format(value)
  }

  /**
   * @Function - formatDate
   * @description - Formats a date string to a string
   * @author - Vitor Hugo
   * @returns - string
   */
  formatDate(dateString: string): string {
    return formatDateBR(dateString)
  }
}


<div class="space-y-6">
  <!-- Header -->
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-3xl font-bold tracking-tight">Pacotes e Serviços</h1>
      <p class="text-muted-foreground">
        Gerencie os pacotes de buffet e serviços avulsos
      </p>
    </div>
    <button appButton variant="outline" routerLink="/cadastros/pacotes/novo">
      <lucide-icon [img]="PlusIcon" class="mr-2 h-4 w-4"></lucide-icon>
      Novo Pacote/Serviço
    </button>
  </div>

  <!-- Filtros -->
  <div class="flex items-center space-x-2">
    <div class="flex-1">
      <app-search-bar
        placeholder="Buscar por nome ou descrição..."
        [(ngModel)]="searchTerm"
      ></app-search-bar>
    </div>
  </div>

  <!-- Error Message -->
  @if (error) {
    <div class="w-full p-3 text-sm text-red-600 bg-red-50 border border-red-200 rounded-md">
      {{ error }}
    </div>
  }

  <!-- Loading State -->
  @if (isLoading) {
    <div class="text-center py-8">
      <p class="text-muted-foreground">Carregando pacotes...</p>
    </div>
  }

  <!-- Tabela -->
  @if (!isLoading) {
    <div class="rounded-md border">
      <app-table>
        <thead appTableHeader>
          <tr appTableRow>
            <th appTableHead>Nome</th>
            <th appTableHead>Tipo</th>
            <th appTableHead>Duração</th>
            <th appTableHead>Preço</th>
            <th appTableHead>Data Cadastro</th>
            <th appTableHead class="text-right">Ações</th>
          </tr>
        </thead>
        <tbody appTableBody>
          @for (pkg of filteredPackages; track pkg.id) {
            <tr appTableRow>
              <td appTableCell class="font-medium">
                <div class="flex items-center space-x-2">
                  <lucide-icon [img]="PackageIcon" class="h-4 w-4 text-muted-foreground"></lucide-icon>
                  <span>{{ pkg.name }}</span>
                </div>
              </td>
              <td appTableCell>
                <span class="inline-flex items-center rounded-full px-2 py-1 text-xs font-medium bg-blue-100 text-blue-800">
                  {{ pkg.type }}
                </span>
              </td>
              <td appTableCell>{{ pkg.duration }}</td>
              <td appTableCell class="font-medium">{{ formatCurrency(pkg.price) }}</td>
              <td appTableCell>{{ formatDate(pkg.createdAt) }}</td>
              <td appTableCell class="text-right">
                <div class="flex items-center justify-end space-x-2">
                  <button appButton variant="ghost" size="sm">
                    <lucide-icon [img]="EyeIcon" class="h-4 w-4"></lucide-icon>
                  </button>
                  <button 
                    appButton 
                    variant="ghost" 
                    size="sm" 
                    [routerLink]="['/cadastros/pacotes/editar', pkg.id]"
                  >
                    <lucide-icon [img]="EditIcon" class="h-4 w-4"></lucide-icon>
                  </button>
                  <button
                    appButton
                    variant="ghost"
                    size="sm"
                    (click)="handleDeleteClick(pkg)"
                  >
                    <lucide-icon [img]="Trash2Icon" class="h-4 w-4"></lucide-icon>
                  </button>
                </div>
              </td>
            </tr>
          }
        </tbody>
      </app-table>
    </div>
  }

  <!-- Empty State -->
  @if (!isLoading && filteredPackages.length === 0) {
    <div class="text-center py-8">
      <p class="text-muted-foreground">
        {{ searchTerm ? 'Nenhum pacote encontrado.' : 'Nenhum pacote cadastrado.' }}
      </p>
    </div>
  }

  <!-- Confirmation Modal -->
  <app-confirmation-modal
    [isOpen]="showDeleteModal"
    (onClose)="handleCancelDelete()"
    (onConfirm)="handleConfirmDelete()"
    title="Excluir Pacote/Serviço"
    [message]="'Tem certeza que deseja excluir o pacote/serviço &quot;' + (packageToDelete?.name || '') + '&quot;? Esta ação não pode ser desfeita.'"
    confirmText="Excluir"
    cancelText="Cancelar"
    variant="danger"
    [loading]="isDeleting"></app-confirmation-modal>
</div>
