// src/pages/auth/SignUp.tsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button } from '@/components/ui/button/button'
import { Input } from '@/components/ui/input/input'
import { Label } from '@/components/ui/label/label'
import { useAuth } from '@/context/AuthContext'

export default function SignUp() {
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [error, setError] = useState('')
  const [isLoading, setIsLoading] = useState(false)
  
  const { signup } = useAuth()
  const navigate = useNavigate()

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault()
    setError('')
    setIsLoading(true)

    try {
      const success = await signup(name, email, password, confirmPassword)
      if (success) {
        navigate('/signin')
      } else {
        setError('Erro ao criar conta. Verifique os dados e tente novamente.')
      }
    } catch (err) {
      setError('Erro ao criar conta. Tente novamente.')
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <div className='flex flex-col items-start justify-center gap-2 w-[80%] max-w-[420px]'>
      <div className='flex flex-col items-start justify-center mb-4'>
        <h2 className='m-0 text-[2rem] leading-none font-bold max-[950px]:text-primary-50'>Criar Conta</h2>
        <p className='m-0 text-black max-[950px]:text-primary-50'>Cadastre-se para começar</p>
      </div>

      <form onSubmit={handleSubmit} className='flex flex-col items-start justify-center gap-4 w-full'>
        {error && (
          <div className='w-full p-3 text-sm text-red-600 bg-red-50 border border-red-200 rounded-md'>
            {error}
          </div>
        )}

        <div className='grid w-full items-center gap-3'>
          <Label htmlFor='name'>Nome</Label>
          <Input 
            type='text' 
            id='name' 
            placeholder='Seu nome completo'
            value={name}
            onChange={(e) => setName(e.target.value)}
            required
          />
        </div>

        <div className='grid w-full items-center gap-3'>
          <Label htmlFor='email'>Email</Label>
          <Input 
            type='email' 
            id='email' 
            placeholder='voce@gmail.com'
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            required
          />
        </div>

        <div className='grid w-full items-center gap-3'>
          <Label htmlFor='password'>Senha</Label>
          <Input 
            type='password' 
            id='password' 
            placeholder='•••••••'
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            required
            minLength={6}
          />
        </div>

        <div className='grid w-full items-center gap-3'>
          <Label htmlFor='confirmPassword'>Confirmar Senha</Label>
          <Input 
            type='password' 
            id='confirmPassword' 
            placeholder='•••••••'
            value={confirmPassword}
            onChange={(e) => setConfirmPassword(e.target.value)}
            required
            minLength={6}
          />
        </div>

        <Button
          type='submit'
          disabled={isLoading}
          className='
            w-full items-center gap-2 rounded-md bg-primary-700 px-3 py-1.5 text-sm/6 font-semibold text-primary-50 
            shadow-inner shadow-white/10 focus:not-data-focus:outline-none data-focus:outline data-focus:outline-primary-50 
            data-hover:bg-primary-600 data-open:bg-primary-700 cursor-pointer transition-colors hover:bg-primary-500
            disabled:opacity-50 disabled:cursor-not-allowed'
        >
          {isLoading ? 'Criando conta...' : 'Criar Conta'}
        </Button>

        <div className='w-full flex justify-center'>
          <a
            href='/signin'
            className='mt-4 text-sm text-primary-600 underline font-bold max-[950px]:text-primary-50 hover:text-primary-700'
          >
            Já tem uma conta? Faça login
          </a>
        </div>
      </form>
    </div>
  )
}

// src/app/features/auth/pages/signup/signup.component.ts
import { Component } from '@angular/core'
import { CommonModule } from '@angular/common'
import { FormsModule } from '@angular/forms'
import { Router, RouterModule } from '@angular/router'
import { AuthStateService } from '@core/services/auth-state.service'

@Component({
  selector: 'app-signup',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './signup.component.html',
  styles: []
})
export class SignupComponent {
  name = ''
  email = ''
  password = ''
  confirmPassword = ''
  isLoading = false
  error = ''

  constructor(
    private authState: AuthStateService,
    private router: Router
  ) {}

  async onSubmit() {
    if (!this.name || !this.email || !this.password || !this.confirmPassword) {
      this.error = 'Por favor, preencha todos os campos'
      return
    }

    if (this.password !== this.confirmPassword) {
      this.error = 'As senhas não coincidem'
      return
    }

    this.isLoading = true
    this.error = ''

    try {
      const success = await this.authState.signup(
        this.name,
        this.email,
        this.password,
        this.confirmPassword
      )
      
      if (success) {
        this.router.navigate(['/'])
      } else {
        this.error = 'Erro ao criar conta. Tente novamente.'
      }
    } catch (err: any) {
      this.error = err.message || 'Erro ao criar conta. Tente novamente.'
    } finally {
      this.isLoading = false
    }
  }
}


<div class="flex min-h-screen">
  <!-- Left Side - Brand Section -->
  <div class="hidden lg:flex lg:w-1/2 bg-gradient-to-br from-slate-700 to-slate-800 p-12 flex-col justify-between">
    <div>
      <h1 class="text-5xl font-bold text-white mb-4">Easy Buffet</h1>
      <p class="text-xl text-slate-300">A solução para seu buffet!</p>
    </div>
    
    <div>
      <button class="bg-white/10 hover:bg-white/20 text-white px-6 py-2 rounded-md transition-colors backdrop-blur-sm border border-white/20 flex items-center gap-2">
        Saiba mais
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
        </svg>
      </button>
    </div>
  </div>

  <!-- Right Side - Form Section -->
  <div class="flex-1 flex items-center justify-center p-8 bg-white">
    <div class="w-full max-w-md">
      <div class="mb-8">
        <h2 class="text-4xl font-bold text-gray-900 mb-2">Criar Conta</h2>
        <p class="text-gray-600">Cadastre-se para começar</p>
      </div>
      
      <form (ngSubmit)="onSubmit()" class="space-y-5">
        <div>
          <label for="name" class="block text-sm font-medium text-gray-700 mb-1">
            Nome
          </label>
          <input
            id="name"
            type="text"
            [(ngModel)]="name"
            name="name"
            required
            class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-slate-600 focus:border-transparent outline-none transition-all"
            placeholder="Seu nome completo"
          />
        </div>
        
        <div>
          <label for="email" class="block text-sm font-medium text-gray-700 mb-1">
            Email
          </label>
          <input
            id="email"
            type="email"
            [(ngModel)]="email"
            name="email"
            required
            class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-slate-600 focus:border-transparent outline-none transition-all"
            placeholder="voce@gmail.com"
          />
        </div>
        
        <div>
          <label for="password" class="block text-sm font-medium text-gray-700 mb-1">
            Senha
          </label>
          <input
            id="password"
            type="password"
            [(ngModel)]="password"
            name="password"
            required
            class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-slate-600 focus:border-transparent outline-none transition-all"
            placeholder="••••••••"
          />
        </div>
        
        <div>
          <label for="confirmPassword" class="block text-sm font-medium text-gray-700 mb-1">
            Confirmar Senha
          </label>
          <input
            id="confirmPassword"
            type="password"
            [(ngModel)]="confirmPassword"
            name="confirmPassword"
            required
            class="w-full px-4 py-3 rounded-lg border border-gray-300 focus:ring-2 focus:ring-slate-600 focus:border-transparent outline-none transition-all"
            placeholder="••••••••"
          />
        </div>

        @if (error) {
          <div class="text-sm text-red-600 bg-red-50 p-3 rounded-lg">
            {{ error }}
          </div>
        }

        <button
          type="submit"
          [disabled]="isLoading"
          class="w-full bg-slate-700 hover:bg-slate-800 text-white font-medium py-3 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {{ isLoading ? 'Criando conta...' : 'Criar Conta' }}
        </button>
        
        <div class="text-center">
          <p class="text-sm text-gray-600">
            Já tem uma conta? 
            <a routerLink="/signin" class="text-gray-900 hover:text-slate-700 underline font-medium">
              Faça login
            </a>
          </p>
        </div>
      </form>
    </div>
  </div>
</div>
