// src/pages/financial/costs/CostsList.tsx
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Plus, Edit, Trash2, Eye, Calendar, DollarSign, Tag } from 'lucide-react'
import { Button } from '@/components/ui/button/button'
import SearchBar from '@/components/ui/search-bar/SearchBar'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from '@/components/ui/data-table/table'
import { mockCosts } from '../mockData'

export default function CostsList() {
  const [costs] = useState(mockCosts)
  const [searchTerm, setSearchTerm] = useState('')

  // Debug: verificar se os dados estão sendo carregados
  console.log('Total de custos carregados:', costs.length)
  console.log('Primeiros 3 custos:', costs.slice(0, 3))

  // Filtro simples apenas por busca
  const filteredCosts = costs.filter(cost => {
    if (!searchTerm) return true
    
    return (
      cost.eventName.toLowerCase().includes(searchTerm.toLowerCase()) ||
      cost.description.toLowerCase().includes(searchTerm.toLowerCase()) ||
      cost.eventId.toLowerCase().includes(searchTerm.toLowerCase())
    )
  })

  console.log('Custos filtrados:', filteredCosts.length)

  const handleDelete = (id: string) => {
    // Implementar lógica de exclusão
    console.log('Excluir custo:', id)
  }

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('pt-BR', {
      style: 'currency',
      currency: 'BRL'
    }).format(value)
  }

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('pt-BR')
  }

  const getCategoryColor = (category: string) => {
    switch (category) {
      case 'food':
        return 'bg-orange-100 text-orange-800 border-orange-200'
      case 'staff':
        return 'bg-blue-100 text-blue-800 border-blue-200'
      case 'equipment':
        return 'bg-purple-100 text-purple-800 border-purple-200'
      case 'transport':
        return 'bg-green-100 text-green-800 border-green-200'
      case 'other':
        return 'bg-gray-100 text-gray-800 border-gray-200'
      default:
        return 'bg-gray-100 text-gray-800 border-gray-200'
    }
  }

  const getCategoryLabel = (category: string) => {
    switch (category) {
      case 'food':
        return 'Alimentação'
      case 'staff':
        return 'Equipe'
      case 'equipment':
        return 'Equipamentos'
      case 'transport':
        return 'Transporte'
      case 'other':
        return 'Outros'
      default:
        return category
    }
  }

  return (
    <div className='space-y-6'>
      {/* Header */}
      <div className='flex items-center justify-between'>
        <div>
          <h1 className='text-3xl font-bold tracking-tight'>Custos e Despesas</h1>
          <p className='text-muted-foreground'>
            Gerencie os custos operacionais dos eventos
          </p>
        </div>
        <Button variant='outline' asChild>
          <Link to='/financeiro/custos/novo'>
            <Plus className='mr-2 h-4 w-4' />
            Novo Custo
          </Link>
        </Button>
      </div>

      {/* Debug Info */}
      <div className='bg-blue-50 p-4 rounded-lg border border-blue-200'>
        <h3 className='font-semibold text-blue-800 mb-2'>Debug Info</h3>
        <p className='text-sm text-blue-700'>
          Total de custos: {costs.length} | 
          Custos filtrados: {filteredCosts.length} | 
          Termo de busca: "{searchTerm}"
        </p>
      </div>

      {/* Filtros */}
      <div className='flex items-center space-x-2'>
        <div className='flex-1'>
          <SearchBar
            placeholder='Buscar por evento ou descrição...'
            value={searchTerm}
            onChange={setSearchTerm}
          />
        </div>
      </div>

      {/* Tabela */}
      <div className='rounded-md border'>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Evento</TableHead>
              <TableHead>Data do Evento</TableHead>
              <TableHead>Descrição</TableHead>
              <TableHead>Categoria</TableHead>
              <TableHead>Valor</TableHead>
              <TableHead>Data do Gasto</TableHead>
              <TableHead className='text-right'>Ações</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filteredCosts.map((cost) => (
              <TableRow key={cost.id}>
                <TableCell className='font-medium'>
                  <div className='max-w-[200px] truncate' title={cost.eventName}>
                    {cost.eventName}
                  </div>
                </TableCell>
                <TableCell>
                  <div className='flex items-center space-x-2'>
                    <Calendar className='h-4 w-4 text-muted-foreground' />
                    <span>{formatDate(cost.eventDate)}</span>
                  </div>
                </TableCell>
                <TableCell>
                  <div className='max-w-[200px] truncate' title={cost.description}>
                    {cost.description}
                  </div>
                </TableCell>
                <TableCell>
                  <span
                    className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium border ${getCategoryColor(cost.category)}`}
                  >
                    <Tag className='h-3 w-3 mr-1' />
                    {getCategoryLabel(cost.category)}
                  </span>
                </TableCell>
                <TableCell className='font-medium text-red-600'>
                  <div className='flex items-center space-x-2'>
                    <DollarSign className='h-4 w-4 text-red-600' />
                    <span>{formatCurrency(cost.amount)}</span>
                  </div>
                </TableCell>
                <TableCell>{formatDate(cost.createdAt)}</TableCell>
                <TableCell className='text-right'>
                  <div className='flex items-center justify-end space-x-2'>
                    <Button variant='ghost' size='sm' asChild>
                      <Link to={`/financeiro/custos/visualizar/${cost.id}`}>
                        <Eye className='h-4 w-4' />
                      </Link>
                    </Button>
                    
                    <Button variant='ghost' size='sm' asChild>
                      <Link to={`/financeiro/custos/editar/${cost.id}`}>
                        <Edit className='h-4 w-4' />
                      </Link>
                    </Button>
                    
                    <Button
                      variant='ghost'
                      size='sm'
                      onClick={() => handleDelete(cost.id)}
                    >
                      <Trash2 className='h-4 w-4' />
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      {/* Paginação - implementar quando necessário */}
      {filteredCosts.length === 0 && (
        <div className='text-center py-8'>
          <p className='text-muted-foreground'>
            {searchTerm ? 'Nenhum custo encontrado.' : 'Nenhum custo cadastrado.'}
          </p>
        </div>
      )}
    </div>
  )
}

// src/app/features/financial/costs/costs-list/costs-list.component.ts
import { Component, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { RouterModule } from '@angular/router'
import { FormsModule } from '@angular/forms'
import { LucideAngularModule, Plus, Eye, Trash2 } from 'lucide-angular'
import { firstValueFrom } from 'rxjs'

import { ButtonComponent } from '@shared/components/ui/button/button.component'
import { SearchBarComponent } from '@shared/components/ui/search-bar/search-bar.component'
import { ConfirmationModalComponent } from '@shared/components/ui/confirmation-modal/confirmation-modal.component'
import {
  TableComponent,
  TableHeaderComponent,
  TableBodyComponent,
  TableRowComponent,
  TableHeadComponent,
  TableCellComponent
} from '@shared/components/ui/table/table.component'
import { CostService } from '@core/services/cost.service'
import type { Cost } from '@shared/models/api.types'
import { formatDateBR } from '@shared/utils/date.utils'

@Component({
  selector: 'app-costs-list',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    FormsModule,
    LucideAngularModule,
    ButtonComponent,
    SearchBarComponent,
    ConfirmationModalComponent,
    TableComponent,
    TableHeaderComponent,
    TableBodyComponent,
    TableRowComponent,
    TableHeadComponent,
    TableCellComponent
  ],
  templateUrl: './costs-list.component.html'
})
export class CostsListComponent implements OnInit {
  readonly PlusIcon = Plus
  readonly EyeIcon = Eye
  readonly Trash2Icon = Trash2

  costs: Cost[] = []
  searchTerm: string = ''
  filterCategory: string = 'todos'
  isLoading: boolean = true
  error: string = ''
  showDeleteModal: boolean = false
  costToDelete: Cost | null = null
  isDeleting: boolean = false

  constructor(
    private costService: CostService
  ) {}

  async ngOnInit(): Promise<void> {
    await this.loadCosts()
  }

  /**
   * @Function - loadCosts
   * @description - Load all costs from API
   * @author - Vitor Hugo
   * @returns - Promise<void>
   */
  async loadCosts(): Promise<void> {
    try {
      this.isLoading = true
      this.error = ''
      const response = await firstValueFrom(this.costService.getCosts())
      if (response.success && response.data) {
        this.costs = response.data as Cost[]
      } else {
        this.error = 'Erro ao carregar custos'
      }
    } catch (err: any) {
      this.error = err.message || 'Erro ao carregar custos'
    } finally {
      this.isLoading = false
    }
  }

  /**
   * @Function - filteredCosts
   * @description - Filter costs by search term and category
   * @author - Vitor Hugo
   * @returns - Cost[] - Filtered costs array
   */
  get filteredCosts(): Cost[] {
    let filtered = this.costs

    // Filter by category
    if (this.filterCategory !== 'todos') {
      filtered = filtered.filter(cost => cost.category === this.filterCategory)
    }

    // Filter by search term
    if (this.searchTerm) {
      const searchLower = this.searchTerm.toLowerCase()
      filtered = filtered.filter(cost =>
        cost.description.toLowerCase().includes(searchLower) ||
        (cost.event?.name && cost.event.name.toLowerCase().includes(searchLower))
      )
    }

    return filtered
  }

  /**
   * @Function - handleDeleteClick
   * @description - Open delete confirmation modal
   * @author - Vitor Hugo
   * @param - cost: Cost - Cost to delete
   * @returns - void
   */
  handleDeleteClick(cost: Cost): void {
    this.costToDelete = cost
    this.showDeleteModal = true
    this.error = ''
  }

  /**
   * @Function - handleConfirmDelete
   * @description - Confirm and execute cost deletion
   * @author - Vitor Hugo
   * @returns - Promise<void>
   */
  async handleConfirmDelete(): Promise<void> {
    if (!this.costToDelete) return

    try {
      this.isDeleting = true
      const response = await firstValueFrom(
        this.costService.deleteCost(this.costToDelete.id)
      )
      if (response.success) {
        this.costs = this.costs.filter(cost => cost.id !== this.costToDelete!.id)
        this.showDeleteModal = false
        this.costToDelete = null
      } else {
        this.error = response.message || 'Erro ao excluir custo'
        this.showDeleteModal = false
        this.costToDelete = null
      }
    } catch (err: any) {
      if (err.error?.error?.message) {
        this.error = err.error.error.message
      } else if (err.error?.message) {
        this.error = err.error.message
      } else if (err.message) {
        this.error = err.message
      } else {
        this.error = 'Erro ao excluir custo'
      }
      this.showDeleteModal = false
      this.costToDelete = null
    } finally {
      this.isDeleting = false
    }
  }

  /**
   * @Function - handleCancelDelete
   * @description - Cancel delete operation and close modal
   * @author - Vitor Hugo
   * @returns - void
   */
  handleCancelDelete(): void {
    this.showDeleteModal = false
    this.costToDelete = null
  }

  /**
   * @Function - formatDate
   * @description - Format date string to Brazilian format
   * @author - Vitor Hugo
   * @param - dateString: string - Date to format
   * @returns - string - Formatted date
   */
  formatDate(dateString: string): string {
    return formatDateBR(dateString)
  }

  /**
   * @Function - formatCurrency
   * @description - Format number to Brazilian currency format
   * @author - Vitor Hugo
   * @param - value: number | string - Value to format
   * @returns - string - Formatted currency
   */
  formatCurrency(value: number | string): string {
    const numValue = typeof value === 'string' ? parseFloat(value) : value
    return new Intl.NumberFormat('pt-BR', {
      style: 'currency',
      currency: 'BRL'
    }).format(numValue)
  }

  /**
   * @Function - translateCategory
   * @description - Translate category from English to Portuguese
   * @author - Vitor Hugo
   * @param - category: string - Category to translate
   * @returns - string - Translated category
   */
  translateCategory(category: string): string {
    const translations: Record<string, string> = {
      'staff': 'Pessoal',
      'food': 'Alimentação',
      'decoration': 'Decoração',
      'other': 'Outros'
    }
    return translations[category] || category
  }

  /**
   * @Function - getCategoryColor
   * @description - Get CSS classes for category badge
   * @author - Vitor Hugo
   * @param - category: string - Category value
   * @returns - string - CSS classes
   */
  getCategoryColor(category: string): string {
    const colors: Record<string, string> = {
      'staff': 'bg-blue-100 text-blue-800',
      'food': 'bg-green-100 text-green-800',
      'decoration': 'bg-purple-100 text-purple-800',
      'other': 'bg-gray-100 text-gray-800'
    }
    return colors[category] || 'bg-gray-100 text-gray-800'
  }
}



<div class="space-y-6">
  <!-- Header -->
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-3xl font-bold tracking-tight">Custos e Despesas</h1>
      <p class="text-muted-foreground">
        Gerencie os custos e despesas dos eventos
      </p>
    </div>
    <button appButton variant="outline" routerLink="/financeiro/custos/novo">
      <lucide-icon [img]="PlusIcon" class="mr-2 h-4 w-4"></lucide-icon>
      Novo Custo
    </button>
  </div>

  <!-- Filtros -->
  <div class="flex items-center space-x-2">
    <div class="flex-1">
      <app-search-bar
        placeholder="Buscar por descrição ou evento..."
        [(ngModel)]="searchTerm"
      ></app-search-bar>
    </div>
    <select
      [(ngModel)]="filterCategory"
      class="flex h-10 w-48 items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
    >
      <option value="todos">Todas as categorias</option>
      <option value="staff">Pessoal</option>
      <option value="food">Alimentação</option>
      <option value="decoration">Decoração</option>
      <option value="other">Outros</option>
    </select>
  </div>

  <!-- Error Message -->
  @if (error) {
    <div class="w-full p-3 text-sm text-red-600 bg-red-50 border border-red-200 rounded-md">
      {{ error }}
    </div>
  }

  <!-- Loading State -->
  @if (isLoading) {
    <div class="text-center py-8">
      <p class="text-muted-foreground">Carregando custos...</p>
    </div>
  }

  <!-- Tabela -->
  @if (!isLoading) {
    <div class="rounded-md border">
      <app-table>
        <thead appTableHeader>
          <tr appTableRow>
            <th appTableHead>Descrição</th>
            <th appTableHead>Evento</th>
            <th appTableHead>Valor</th>
            <th appTableHead>Categoria</th>
            <th appTableHead>Data</th>
            <th appTableHead class="text-right">Ações</th>
          </tr>
        </thead>
        <tbody appTableBody>
          @for (cost of filteredCosts; track cost.id) {
            <tr appTableRow>
              <td appTableCell class="font-medium">{{ cost.description }}</td>
              <td appTableCell>{{ cost.event?.name || '-' }}</td>
              <td appTableCell>{{ formatCurrency(cost.amount) }}</td>
              <td appTableCell>
                <span [class]="'inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ' + getCategoryColor(cost.category)">
                  {{ translateCategory(cost.category) }}
                </span>
              </td>
              <td appTableCell>{{ formatDate(cost.createdAt) }}</td>
              <td appTableCell class="text-right">
                <div class="flex items-center justify-end space-x-2">
                  <button appButton variant="ghost" size="sm" title="Ver detalhes">
                    <lucide-icon [img]="EyeIcon" class="h-4 w-4"></lucide-icon>
                  </button>
                  <button
                    appButton
                    variant="ghost"
                    size="sm"
                    (click)="handleDeleteClick(cost)"
                    title="Excluir"
                  >
                    <lucide-icon [img]="Trash2Icon" class="h-4 w-4"></lucide-icon>
                  </button>
                </div>
              </td>
            </tr>
          }
        </tbody>
      </app-table>
    </div>
  }

  <!-- Empty State -->
  @if (!isLoading && filteredCosts.length === 0) {
    <div class="text-center py-8">
      <p class="text-muted-foreground">
        {{ searchTerm || filterCategory !== 'todos' ? 'Nenhum custo encontrado.' : 'Nenhum custo cadastrado.' }}
      </p>
    </div>
  }

  <!-- Delete Confirmation Modal -->
  <app-confirmation-modal
    [isOpen]="showDeleteModal"
    (onClose)="handleCancelDelete()"
    (onConfirm)="handleConfirmDelete()"
    title="Excluir Custo"
    [message]="'Tem certeza que deseja excluir o custo &quot;' + (costToDelete?.description || '') + '&quot;? Esta ação não pode ser desfeita.'"
    confirmText="Excluir"
    cancelText="Cancelar"
    variant="danger"
    [loading]="isDeleting"
  ></app-confirmation-modal>
</div>
