// src/pages/register/packages/PackageForm.tsx
import { useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, Save, X } from 'lucide-react'
import { Button } from '@/components/ui/button/button'
import { Input } from '@/components/ui/input/input'
import { Label } from '@/components/ui/label/label'

interface PacoteFormData {
  nome: string
  tipo: 'Pacote' | 'Serviço'
  descricao: string
  preco: string
  duracao: string
  observacoes: string
}

export default function PacoteForm() {
  const navigate = useNavigate()
  const { id } = useParams()
  const isEditing = Boolean(id)

  const [formData, setFormData] = useState<PacoteFormData>({
    nome: '',
    tipo: 'Pacote',
    descricao: '',
    preco: '',
    duracao: '',
    observacoes: ''
  })

  const [errors, setErrors] = useState<Partial<PacoteFormData>>({})

  const handleInputChange = (field: keyof PacoteFormData, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }))
    // Limpar erro do campo quando usuário começar a digitar
    if (errors[field]) {
      setErrors(prev => ({ ...prev, [field]: undefined }))
    }
  }

  const validateForm = (): boolean => {
    const newErrors: Partial<PacoteFormData> = {}

    if (!formData.nome.trim()) {
      newErrors.nome = 'Nome é obrigatório'
    }

    if (!formData.descricao.trim()) {
      newErrors.descricao = 'Descrição é obrigatória'
    }

    if (!formData.preco.trim()) {
      newErrors.preco = 'Preço é obrigatório'
    } else if (isNaN(Number(formData.preco.replace(',', '.')))) {
      newErrors.preco = 'Preço deve ser um número válido'
    }

    if (!formData.duracao.trim()) {
      newErrors.duracao = 'Duração é obrigatória'
    }

    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!validateForm()) {
      return
    }

    // Implementar lógica de salvamento
    console.log('Salvando pacote/serviço:', formData)
    
    // Simular salvamento
    setTimeout(() => {
      navigate('/cadastros/pacotes')
    }, 1000)
  }

  const handleCancel = () => {
    navigate('/cadastros/pacotes')
  }

  return (
    <div className='space-y-6'>
      {/* Header */}
      <div className='flex items-center space-x-4'>
        <Button variant='ghost' size='sm' onClick={handleCancel}>
          <ArrowLeft className='h-4 w-4 mr-2' />
          Voltar
        </Button>
        <div>
          <h1 className='text-3xl font-bold tracking-tight'>
            {isEditing ? 'Editar Pacote/Serviço' : 'Novo Pacote/Serviço'}
          </h1>
          <p className='text-muted-foreground'>
            {isEditing 
              ? 'Atualize as informações do pacote/serviço' 
              : 'Preencha os dados do novo pacote/serviço'
            }
          </p>
        </div>
      </div>

      {/* Formulário */}
      <form onSubmit={handleSubmit} className='space-y-6'>
        <div className='grid grid-cols-1 md:grid-cols-2 gap-6'>
          {/* Nome */}
          <div className='space-y-2'>
            <Label htmlFor='nome'>Nome *</Label>
            <Input
              id='nome'
              value={formData.nome}
              onChange={(e) => handleInputChange('nome', e.target.value)}
              placeholder='Nome do pacote ou serviço'
              className={errors.nome ? 'border-red-500' : ''}
            />
            {errors.nome && (
              <p className='text-sm text-red-500'>{errors.nome}</p>
            )}
          </div>

          {/* Tipo */}
          <div className='space-y-2'>
            <Label htmlFor='tipo'>Tipo *</Label>
            <select
              id='tipo'
              value={formData.tipo}
              onChange={(e) => handleInputChange('tipo', e.target.value as 'Pacote' | 'Serviço')}
              className='flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50'
            >
              <option value='Pacote'>Pacote</option>
              <option value='Serviço'>Serviço</option>
            </select>
          </div>

          {/* Preço */}
          <div className='space-y-2'>
            <Label htmlFor='preco'>Preço *</Label>
            <Input
              id='preco'
              value={formData.preco}
              onChange={(e) => handleInputChange('preco', e.target.value)}
              placeholder='0,00'
              className={errors.preco ? 'border-red-500' : ''}
            />
            {errors.preco && (
              <p className='text-sm text-red-500'>{errors.preco}</p>
            )}
          </div>

          {/* Duração */}
          <div className='space-y-2'>
            <Label htmlFor='duracao'>Duração *</Label>
            <Input
              id='duracao'
              value={formData.duracao}
              onChange={(e) => handleInputChange('duracao', e.target.value)}
              placeholder='Ex: 4 horas, 1 dia'
              className={errors.duracao ? 'border-red-500' : ''}
            />
            {errors.duracao && (
              <p className='text-sm text-red-500'>{errors.duracao}</p>
            )}
          </div>
        </div>

        {/* Descrição */}
        <div className='space-y-2'>
          <Label htmlFor='descricao'>Descrição *</Label>
          <textarea
            id='descricao'
            value={formData.descricao}
            onChange={(e) => handleInputChange('descricao', e.target.value)}
            placeholder='Descreva o pacote ou serviço oferecido'
            className='flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50'
            rows={3}
          />
          {errors.descricao && (
            <p className='text-sm text-red-500'>{errors.descricao}</p>
          )}
        </div>

        {/* Observações */}
        <div className='space-y-2'>
          <Label htmlFor='observacoes'>Observações</Label>
          <textarea
            id='observacoes'
            value={formData.observacoes}
            onChange={(e) => handleInputChange('observacoes', e.target.value)}
            placeholder='Informações adicionais sobre o pacote/serviço'
            className='flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50'
            rows={3}
          />
        </div>

        {/* Botões */}
        <div className='flex items-center justify-end space-x-2 pt-6 border-t'>
          <Button type='button' variant='outline' onClick={handleCancel}>
            <X className='h-4 w-4 mr-2' />
            Cancelar
          </Button>
          <Button type='submit' variant='outline'>
            <Save className='h-4 w-4 mr-2' />
            {isEditing ? 'Atualizar' : 'Salvar'}
          </Button>
        </div>
      </form>
    </div>
  )
}

// src/app/features/register/packages/package-form/package-form.component.ts
import { Component, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { Router, ActivatedRoute } from '@angular/router'
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms'
import { LucideAngularModule, ArrowLeft, Save, X } from 'lucide-angular'
import { firstValueFrom } from 'rxjs'

import { ButtonComponent } from '@shared/components/ui/button/button.component'
import { LabelComponent } from '@shared/components/ui/label/label.component'
import { PackageService } from '@core/services/package.service'
import type { CreatePackageRequest, UpdatePackageRequest } from '@shared/models/api.types'

@Component({
  selector: 'app-package-form',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    LucideAngularModule,
    ButtonComponent,
    LabelComponent
  ],
  templateUrl: './package-form.component.html'
})
export class PackageFormComponent implements OnInit {
  readonly ArrowLeftIcon = ArrowLeft
  readonly SaveIcon = Save
  readonly XIcon = X

  packageForm!: FormGroup
  isEditing: boolean = false
  packageId: string | null = null
  isLoading: boolean = false
  isLoadingData: boolean = false
  errorMessage: string = ''

  constructor(
    private fb: FormBuilder,
    private packageService: PackageService,
    private router: Router,
    private route: ActivatedRoute
  ) {
    this.packageForm = this.fb.group({
      name: ['', [Validators.required]],
      type: ['', [Validators.required]],
      description: [''],
      price: ['', [Validators.required, Validators.min(0)]],
      duration: ['', [Validators.required]],
      notes: ['']
    })
  }

  async ngOnInit(): Promise<void> {
    this.packageId = this.route.snapshot.paramMap.get('id')
    this.isEditing = !!this.packageId

    if (this.isEditing && this.packageId) {
      await this.loadPackage(this.packageId)
    }
  }

  async loadPackage(id: string): Promise<void> {
    try {
      this.isLoadingData = true
      const response = await firstValueFrom(this.packageService.getPackageById(id))
      if (response.success && response.data) {
        const pkg = response.data
        this.packageForm.patchValue({
          name: pkg.name,
          type: pkg.type,
          description: pkg.description || '',
          price: pkg.price,
          duration: pkg.duration,
          notes: pkg.notes || ''
        })
      }
    } catch (error: any) {
      this.errorMessage = error.message || 'Erro ao carregar pacote'
    } finally {
      this.isLoadingData = false
    }
  }

  async handleSubmit(): Promise<void> {
    if (this.packageForm.invalid) {
      Object.keys(this.packageForm.controls).forEach(key => {
        this.packageForm.controls[key].markAsTouched()
      })
      return
    }

    this.isLoading = true
    this.errorMessage = ''

    try {
      const formValue = this.packageForm.value
      const price = parseFloat(formValue.price)
      
      if (this.isEditing && this.packageId) {
        const updateData: UpdatePackageRequest = {
          name: formValue.name,
          type: formValue.type,
          description: formValue.description || undefined,
          price: price,
          duration: formValue.duration,
          notes: formValue.notes || undefined
        }
        
        const response = await firstValueFrom(
          this.packageService.updatePackage(this.packageId, updateData)
        )
        
        if (response.success) {
          this.router.navigate(['/cadastros/pacotes'])
        } else {
          this.errorMessage = 'Erro ao atualizar pacote'
        }
      } else {
        const createData: CreatePackageRequest = {
          name: formValue.name,
          type: formValue.type,
          description: formValue.description || undefined,
          price: price,
          duration: formValue.duration,
          notes: formValue.notes || undefined
        }
        
        const response = await firstValueFrom(
          this.packageService.createPackage(createData)
        )
        
        if (response.success) {
          this.router.navigate(['/cadastros/pacotes'])
        } else {
          this.errorMessage = 'Erro ao criar pacote'
        }
      }
    } catch (error: any) {
      this.errorMessage = error.message || 'Erro ao salvar pacote'
    } finally {
      this.isLoading = false
    }
  }

  handleCancel(): void {
    this.router.navigate(['/cadastros/pacotes'])
  }

  hasError(fieldName: string): boolean {
    const field = this.packageForm.get(fieldName)
    return !!(field?.invalid && field.touched)
  }

  getFieldError(fieldName: string): string {
    const field = this.packageForm.get(fieldName)
    if (field?.hasError('required') && field.touched) {
      return 'Campo obrigatório'
    }
    if (field?.hasError('min') && field.touched) {
      return 'Valor deve ser maior que zero'
    }
    return ''
  }
}


<div class="space-y-6">
  <!-- Header -->
  <div class="flex items-center space-x-4">
    <button appButton variant="ghost" size="sm" (click)="handleCancel()">
      <lucide-icon [img]="ArrowLeftIcon" class="h-4 w-4 mr-2"></lucide-icon>
      Voltar
    </button>
    <div>
      <h1 class="text-3xl font-bold tracking-tight">
        {{ isEditing ? 'Editar Pacote' : 'Novo Pacote' }}
      </h1>
      <p class="text-muted-foreground">
        {{ isEditing ? 'Atualize as informações do pacote' : 'Preencha os dados do novo pacote' }}
      </p>
    </div>
  </div>

  <!-- Loading State -->
  @if (isLoadingData) {
    <div class="text-center py-8">
      <p class="text-muted-foreground">Carregando dados do pacote...</p>
    </div>
  }

  <!-- Error Message -->
  @if (errorMessage) {
    <div class="w-full p-3 text-sm text-red-600 bg-red-50 border border-red-200 rounded-md">
      {{ errorMessage }}
    </div>
  }

  <!-- Formulário -->
  @if (!isLoadingData) {
    <form [formGroup]="packageForm" (ngSubmit)="handleSubmit()" class="space-y-6">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <!-- Nome -->
        <div class="space-y-2">
          <label appLabel htmlFor="name">Nome *</label>
          <input
            type="text"
            id="name"
            formControlName="name"
            placeholder="Nome do pacote"
            [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('name') ? 'border-red-500' : '')"
          />
          @if (hasError('name')) {
            <p class="text-sm text-red-500">{{ getFieldError('name') }}</p>
          }
        </div>

        <!-- Tipo -->
        <div class="space-y-2">
          <label appLabel htmlFor="type">Tipo *</label>
          <select
            id="type"
            formControlName="type"
            [class]="'flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 ' + (hasError('type') ? 'border-red-500' : '')"
          >
            <option value="">Selecione o tipo</option>
            <option value="Pacote">Pacote</option>
            <option value="Serviço">Serviço</option>
          </select>
          @if (hasError('type')) {
            <p class="text-sm text-red-500">{{ getFieldError('type') }}</p>
          }
        </div>

        <!-- Preço -->
        <div class="space-y-2">
          <label appLabel htmlFor="price">Preço *</label>
          <input
            type="number"
            step="0.01"
            id="price"
            formControlName="price"
            placeholder="0,00"
            [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('price') ? 'border-red-500' : '')"
          />
          @if (hasError('price')) {
            <p class="text-sm text-red-500">{{ getFieldError('price') }}</p>
          }
        </div>

        <!-- Duração -->
        <div class="space-y-2">
          <label appLabel htmlFor="duration">Duração *</label>
          <input
            type="text"
            id="duration"
            formControlName="duration"
            placeholder="Ex: 4 horas, 6 horas"
            [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('duration') ? 'border-red-500' : '')"
          />
          @if (hasError('duration')) {
            <p class="text-sm text-red-500">{{ getFieldError('duration') }}</p>
          }
        </div>
      </div>

      <!-- Descrição -->
      <div class="space-y-2">
        <label appLabel htmlFor="description">Descrição</label>
        <textarea
          id="description"
          formControlName="description"
          placeholder="Descreva o pacote oferecido"
          class="flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
          rows="3"
        ></textarea>
      </div>

      <!-- Notas -->
      <div class="space-y-2">
        <label appLabel htmlFor="notes">Notas</label>
        <textarea
          id="notes"
          formControlName="notes"
          placeholder="Informações adicionais sobre o pacote"
          class="flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
          rows="3"
        ></textarea>
      </div>

      <!-- Botões -->
      <div class="flex items-center justify-end space-x-2 pt-6 border-t">
        <button appButton type="button" variant="outline" (click)="handleCancel()">
          <lucide-icon [img]="XIcon" class="h-4 w-4 mr-2"></lucide-icon>
          Cancelar
        </button>
        <button appButton type="submit" variant="outline" [disabled]="isLoading">
          <lucide-icon [img]="SaveIcon" class="h-4 w-4 mr-2"></lucide-icon>
          {{ isLoading ? 'Salvando...' : (isEditing ? 'Atualizar' : 'Salvar') }}
        </button>
      </div>
    </form>
  }
</div>
