// src/pages/register/contracts/ContractDetail.tsx
import { useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { ArrowLeft, Edit, FileText, Calendar, DollarSign, User, Calculator, Clock, CheckCircle, AlertCircle, XCircle } from 'lucide-react'
import { Button } from '@/components/ui/button/button'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/data-table/table'

// Mock data - substituir por dados reais da API
const mockContrato = {
  id: 1,
  evento: 'Casamento João & Maria',
  cliente: 'João Silva',
  valorTotal: 5000.00,
  parcelas: 5,
  primeiroVencimento: '2025-11-15',
  periodicidade: 'Mensal',
  comissaoPercentual: 10,
  comissaoTotal: 500.00,
  status: 'Ativo',
  dataCadastro: '2025-10-15',
  observacoes: 'Contrato para casamento com cerimônia e recepção.',
  parcelasDetalhes: [
    {
      numero: 1,
      dataVencimento: '2025-10-15',
      valor: 1000.00,
      status: 'Pago',
      dataPagamento: '2025-10-14'
    },
    {
      numero: 2,
      dataVencimento: '2025-10-15',
      valor: 1000.00,
      status: 'Pago',
      dataPagamento: '2025-10-14'
    },
    {
      numero: 3,
      dataVencimento: '2025-10-15',
      valor: 1000.00,
      status: 'A vencer'
    },
    {
      numero: 4,
      dataVencimento: '2025-10-15',
      valor: 1000.00,
      status: 'A vencer'
    },
    {
      numero: 5,
      dataVencimento: '2025-10-15',
      valor: 1000.00,
      status: 'A vencer'
    }
  ]
}

export default function ContractDetail() {
  const { id } = useParams()
  const [contrato] = useState(mockContrato)

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('pt-BR', {
      style: 'currency',
      currency: 'BRL'
    }).format(value)
  }

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('pt-BR')
  }

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'Pago':
        return <CheckCircle className='h-4 w-4 text-green-600' />
      case 'A vencer':
        return <Clock className='h-4 w-4 text-yellow-600' />
      case 'Atrasado':
        return <AlertCircle className='h-4 w-4 text-red-600' />
      default:
        return <XCircle className='h-4 w-4 text-gray-600' />
    }
  }

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Pago':
        return 'bg-green-100 text-green-800'
      case 'A vencer':
        return 'bg-yellow-100 text-yellow-800'
      case 'Atrasado':
        return 'bg-red-100 text-red-800'
      default:
        return 'bg-gray-100 text-gray-800'
    }
  }

  const getContractStatusColor = (status: string) => {
    switch (status) {
      case 'Ativo':
        return 'bg-green-100 text-green-800'
      case 'Finalizado':
        return 'bg-blue-100 text-blue-800'
      case 'Cancelado':
        return 'bg-red-100 text-red-800'
      default:
        return 'bg-gray-100 text-gray-800'
    }
  }

  const parcelasPagas = contrato.parcelasDetalhes.filter(p => p.status === 'Pago').length
  const parcelasPendentes = contrato.parcelasDetalhes.filter(p => p.status === 'A vencer').length
  const parcelasAtrasadas = contrato.parcelasDetalhes.filter(p => p.status === 'Atrasado').length
  const progressPercentage = Math.round((parcelasPagas / contrato.parcelas) * 100)

  return (
    <div className='space-y-6'>
      {/* Header */}
      <div className='flex items-center justify-between'>
        <div className='flex items-center space-x-4'>
          <Button variant='ghost' size='sm' asChild>
            <Link to='/cadastros/contratos'>
              <ArrowLeft className='h-4 w-4 mr-2' />
              Voltar
            </Link>
          </Button>
          <div>
            <h1 className='text-3xl font-bold tracking-tight'>Detalhes do Contrato</h1>
            <p className='text-muted-foreground'>
              Visualização completa do contrato e parcelas
            </p>
          </div>
        </div>
        <Button variant='outline' asChild>
          <Link to={`/cadastros/contratos/editar/${contrato.id}`}>
            <Edit className='h-4 w-4 mr-2' />
            Editar Contrato
          </Link>
        </Button>
      </div>

      <div className='grid grid-cols-1 lg:grid-cols-3 gap-6'>
        {/* Informações do Contrato */}
        <div className='lg:col-span-2 space-y-6'>
          {/* Dados Principais */}
          <div className='bg-white border rounded-lg p-6'>
            <h3 className='text-lg font-semibold flex items-center space-x-2 mb-4'>
              <FileText className='h-5 w-5' />
              <span>Informações do Contrato</span>
            </h3>
            
            <div className='grid grid-cols-1 md:grid-cols-2 gap-4'>
              <div>
                <label className='text-sm font-medium text-muted-foreground'>Evento</label>
                <p className='text-lg font-semibold'>{contrato.evento}</p>
              </div>
              
              <div>
                <label className='text-sm font-medium text-muted-foreground'>Cliente</label>
                <div className='flex items-center space-x-2'>
                  <User className='h-4 w-4 text-muted-foreground' />
                  <p className='text-lg font-semibold'>{contrato.cliente}</p>
                </div>
              </div>
              
              <div>
                <label className='text-sm font-medium text-muted-foreground'>Valor Total</label>
                <div className='flex items-center space-x-2'>
                  <DollarSign className='h-4 w-4 text-muted-foreground' />
                  <p className='text-lg font-semibold text-green-600'>{formatCurrency(contrato.valorTotal)}</p>
                </div>
              </div>
              
              <div>
                <label className='text-sm font-medium text-muted-foreground'>Status</label>
                <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${getContractStatusColor(contrato.status)}`}>
                  {contrato.status}
                </span>
              </div>
              
              <div>
                <label className='text-sm font-medium text-muted-foreground'>Parcelas</label>
                <div className='flex items-center space-x-2'>
                  <Calendar className='h-4 w-4 text-muted-foreground' />
                  <p className='text-lg font-semibold'>{contrato.parcelas}x {contrato.periodicidade}</p>
                </div>
              </div>
              
              <div>
                <label className='text-sm font-medium text-muted-foreground'>Primeiro Vencimento</label>
                <p className='text-lg font-semibold'>{formatDate(contrato.primeiroVencimento)}</p>
              </div>
              
              <div>
                <label className='text-sm font-medium text-muted-foreground'>Comissão</label>
                <div className='space-y-1'>
                  <p className='text-lg font-semibold text-blue-600'>{formatCurrency(contrato.comissaoTotal)}</p>
                  <p className='text-sm text-muted-foreground'>{contrato.comissaoPercentual}% do valor total</p>
                </div>
              </div>
              
              <div>
                <label className='text-sm font-medium text-muted-foreground'>Data de Cadastro</label>
                <p className='text-lg font-semibold'>{formatDate(contrato.dataCadastro)}</p>
              </div>
            </div>
            
            {contrato.observacoes && (
              <div className='mt-6'>
                <label className='text-sm font-medium text-muted-foreground'>Observações</label>
                <p className='mt-1 text-sm bg-gray-50 p-3 rounded-md'>{contrato.observacoes}</p>
              </div>
            )}
          </div>

          {/* Parcelas */}
          <div className='bg-white border rounded-lg p-6'>
            <h3 className='text-lg font-semibold flex items-center space-x-2 mb-4'>
              <Calculator className='h-5 w-5' />
              <span>Parcelas do Contrato</span>
            </h3>
            
            <div className='overflow-x-auto'>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Parcela</TableHead>
                    <TableHead>Vencimento</TableHead>
                    <TableHead>Valor</TableHead>
                    <TableHead>Status</TableHead>
                    <TableHead>Data Pagamento</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {contrato.parcelasDetalhes.map((parcela) => (
                    <TableRow key={parcela.numero}>
                      <TableCell className='font-medium'>{parcela.numero}</TableCell>
                      <TableCell>
                        <div className='flex items-center space-x-2'>
                          <Calendar className='h-4 w-4 text-muted-foreground' />
                          <span>{formatDate(parcela.dataVencimento)}</span>
                        </div>
                      </TableCell>
                      <TableCell className='font-medium'>
                        <div className='flex items-center space-x-2'>
                          <DollarSign className='h-4 w-4 text-muted-foreground' />
                          <span>{formatCurrency(parcela.valor)}</span>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className='flex items-center space-x-2'>
                          {getStatusIcon(parcela.status)}
                          <span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${getStatusColor(parcela.status)}`}>
                            {parcela.status}
                          </span>
                        </div>
                      </TableCell>
                      <TableCell>
                        {parcela.dataPagamento ? formatDate(parcela.dataPagamento) : '-'}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </div>
        </div>

        {/* Resumo e Estatísticas */}
        <div className='space-y-6'>
          {/* Resumo do Progresso */}
          <div className='bg-white border rounded-lg p-6'>
            <h3 className='text-lg font-semibold mb-4'>Resumo do Progresso</h3>
            
            <div className='space-y-4'>
              <div>
                <div className='flex justify-between text-sm mb-2'>
                  <span>Progresso Geral</span>
                  <span>{progressPercentage}%</span>
                </div>
                <div className='w-full bg-gray-200 rounded-full h-3'>
                  <div
                    className='bg-blue-600 h-3 rounded-full transition-all duration-300'
                    style={{ width: `${progressPercentage}%` }}
                  ></div>
                </div>
              </div>
              
              <div className='grid grid-cols-2 gap-4 text-center'>
                <div className='bg-green-50 p-3 rounded-lg'>
                  <div className='text-2xl font-bold text-green-600'>{parcelasPagas}</div>
                  <div className='text-sm text-green-600'>Pagas</div>
                </div>
                <div className='bg-yellow-50 p-3 rounded-lg'>
                  <div className='text-2xl font-bold text-yellow-600'>{parcelasPendentes}</div>
                  <div className='text-sm text-yellow-600'>A Vencer</div>
                </div>
              </div>
              
              {parcelasAtrasadas > 0 && (
                <div className='bg-red-50 p-3 rounded-lg text-center'>
                  <div className='text-2xl font-bold text-red-600'>{parcelasAtrasadas}</div>
                  <div className='text-sm text-red-600'>Atrasadas</div>
                </div>
              )}
            </div>
          </div>

          {/* Valores */}
          <div className='bg-white border rounded-lg p-6'>
            <h3 className='text-lg font-semibold mb-4'>Valores</h3>
            
            <div className='space-y-3'>
              <div className='flex justify-between'>
                <span className='text-muted-foreground'>Valor por parcela:</span>
                <span className='font-semibold'>{formatCurrency(contrato.valorTotal / contrato.parcelas)}</span>
              </div>
              
              <div className='flex justify-between'>
                <span className='text-muted-foreground'>Total pago:</span>
                <span className='font-semibold text-green-600'>
                  {formatCurrency(parcelasPagas * (contrato.valorTotal / contrato.parcelas))}
                </span>
              </div>
              
              <div className='flex justify-between'>
                <span className='text-muted-foreground'>Restante:</span>
                <span className='font-semibold text-orange-600'>
                  {formatCurrency(parcelasPendentes * (contrato.valorTotal / contrato.parcelas))}
                </span>
              </div>
              
              <div className='border-t pt-3'>
                <div className='flex justify-between'>
                  <span className='text-muted-foreground'>Comissão total:</span>
                  <span className='font-semibold text-blue-600'>{formatCurrency(contrato.comissaoTotal)}</span>
                </div>
              </div>
            </div>
          </div>

          {/* Ações Rápidas */}
          <div className='bg-white border rounded-lg p-6'>
            <h3 className='text-lg font-semibold mb-4'>Ações Rápidas</h3>
            
            <div className='space-y-2'>
              <Button variant='outline' className='w-full' asChild>
                <Link to={`/cadastros/contratos/editar/${contrato.id}`}>
                  <Edit className='h-4 w-4 mr-2' />
                  Editar Contrato
                </Link>
              </Button>
              
              <Button variant='outline' className='w-full'>
                <FileText className='h-4 w-4 mr-2' />
                Gerar PDF
              </Button>
              
              <Button variant='outline' className='w-full'>
                <DollarSign className='h-4 w-4 mr-2' />
                Registrar Pagamento
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

// src/app/features/register/contracts/contract-detail/contract-detail.component.ts
import { Component, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { Router, ActivatedRoute, RouterModule } from '@angular/router'
import { LucideAngularModule, ArrowLeft, Edit, FileText, User, Calendar, DollarSign, CreditCard, CheckCircle2, Clock, AlertCircle } from 'lucide-angular'
import { firstValueFrom } from 'rxjs'

import { ButtonComponent } from '@shared/components/ui/button/button.component'
import { 
  TableComponent, 
  TableHeaderComponent, 
  TableBodyComponent, 
  TableRowComponent, 
  TableHeadComponent, 
  TableCellComponent 
} from '@shared/components/ui/table/table.component'
import { ContractService } from '@core/services/contract.service'
import type { Contract, Installment } from '@shared/models/api.types'
import { formatDateBR } from '@shared/utils/date.utils'

interface ContractWithDetails extends Contract {
  event?: {
    id: string
    name: string
    eventDate: string
  }
  client?: {
    id: string
    name: string
  }
  installments?: Installment[]
}

@Component({
  selector: 'app-contract-detail',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    LucideAngularModule,
    ButtonComponent,
    TableComponent,
    TableHeaderComponent,
    TableBodyComponent,
    TableRowComponent,
    TableHeadComponent,
    TableCellComponent
  ],
  templateUrl: './contract-detail.component.html'
})
export class ContractDetailComponent implements OnInit {
  readonly ArrowLeftIcon = ArrowLeft
  readonly EditIcon = Edit
  readonly FileTextIcon = FileText
  readonly UserIcon = User
  readonly CalendarIcon = Calendar
  readonly DollarSignIcon = DollarSign
  readonly CreditCardIcon = CreditCard
  readonly CheckCircle2Icon = CheckCircle2
  readonly ClockIcon = Clock
  readonly AlertCircleIcon = AlertCircle

  contract: ContractWithDetails | null = null
  contractId: string | null = null
  isLoading: boolean = true
  error: string = ''

  constructor(
    private contractService: ContractService,
    private router: Router,
    private route: ActivatedRoute
  ) {}

  /**
   * @Function - ngOnInit
   * @description - Lifecycle hook that runs when component initializes, loads contract details
   * @author - Vitor Hugo
   * @returns - Promise<void>
   */
  async ngOnInit(): Promise<void> {
    this.contractId = this.route.snapshot.paramMap.get('id')
    if (this.contractId) {
      await this.loadContractDetails(this.contractId)
    } else {
      this.error = 'ID do contrato não encontrado'
      this.isLoading = false
    }
  }

  /**
   * @Function - loadContractDetails
   * @description - Loads complete contract details including event, client and installments
   * @author - Vitor Hugo
   * @param - id: string - Contract ID
   * @returns - Promise<void>
   */
  async loadContractDetails(id: string): Promise<void> {
    try {
      this.isLoading = true
      this.error = ''
      const response = await firstValueFrom(this.contractService.getContractById(id))
      
      if (response.success && response.data) {
        this.contract = response.data as ContractWithDetails
      } else {
        this.error = 'Erro ao carregar detalhes do contrato'
      }
    } catch (err: any) {
      if (err.error?.error?.message) {
        this.error = err.error.error.message
      } else if (err.error?.message) {
        this.error = err.error.message
      } else {
        this.error = err.message || 'Erro ao carregar detalhes do contrato'
      }
    } finally {
      this.isLoading = false
    }
  }

  /**
   * @Function - handleBack
   * @description - Navigates back to contracts list
   * @author - Vitor Hugo
   * @returns - void
   */
  handleBack(): void {
    this.router.navigate(['/cadastros/contratos'])
  }

  /**
   * @Function - handleEdit
   * @description - Navigates to contract edit page
   * @author - Vitor Hugo
   * @returns - void
   */
  handleEdit(): void {
    if (this.contractId) {
      this.router.navigate(['/cadastros/contratos/editar', this.contractId])
    }
  }

  /**
   * @Function - formatDate
   * @description - Formats ISO date string to Brazilian date format
   * @author - Vitor Hugo
   * @param - dateString: string - ISO date string
   * @returns - string - Formatted date in Brazilian format
   */
  formatDate(dateString: string): string {
    return formatDateBR(dateString)
  }

  /**
   * @Function - formatCurrency
   * @description - Formats number or string to Brazilian currency format
   * @author - Vitor Hugo
   * @param - value: number | string - Value to format
   * @returns - string - Formatted currency string
   */
  formatCurrency(value: number | string): string {
    const numValue = typeof value === 'string' ? parseFloat(value) : value
    return new Intl.NumberFormat('pt-BR', {
      style: 'currency',
      currency: 'BRL'
    }).format(numValue)
  }

  /**
   * @Function - getStatusBadgeClass
   * @description - Returns CSS classes for installment status badge
   * @author - Vitor Hugo
   * @param - status: string - Installment status (pending, paid, overdue)
   * @returns - string - CSS classes for badge styling
   */
  getStatusBadgeClass(status: string): string {
    const baseClasses = 'inline-flex items-center gap-1 rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors'
    
    switch (status.toLowerCase()) {
      case 'paid':
      case 'pago':
        return `${baseClasses} border-transparent bg-green-100 text-green-800`
      case 'pending':
      case 'pendente':
        return `${baseClasses} border-transparent bg-yellow-100 text-yellow-800`
      case 'overdue':
      case 'atrasado':
        return `${baseClasses} border-transparent bg-red-100 text-red-800`
      default:
        return `${baseClasses} border-transparent bg-gray-100 text-gray-800`
    }
  }

  /**
   * @Function - getStatusText
   * @description - Returns translated status text for display
   * @author - Vitor Hugo
   * @param - status: string - Installment status
   * @returns - string - Translated status text
   */
  getStatusText(status: string): string {
    const statusMap: Record<string, string> = {
      'paid': 'Pago',
      'pending': 'Pendente',
      'overdue': 'Atrasado',
      'pago': 'Pago',
      'pendente': 'Pendente',
      'atrasado': 'Atrasado'
    }
    return statusMap[status.toLowerCase()] || status
  }

  /**
   * @Function - getStatusIcon
   * @description - Returns appropriate icon for installment status
   * @author - Vitor Hugo
   * @param - status: string - Installment status
   * @returns - any - Lucide icon component
   */
  getStatusIcon(status: string): any {
    switch (status.toLowerCase()) {
      case 'paid':
      case 'pago':
        return this.CheckCircle2Icon
      case 'pending':
      case 'pendente':
        return this.ClockIcon
      case 'overdue':
      case 'atrasado':
        return this.AlertCircleIcon
      default:
        return this.ClockIcon
    }
  }

  /**
   * @Function - getPaidInstallmentsCount
   * @description - Counts the number of paid installments
   * @author - Vitor Hugo
   * @returns - number - Count of paid installments
   */
  getPaidInstallmentsCount(): number {
    if (!this.contract?.installments) return 0
    return this.contract.installments.filter(
      i => i.status.toLowerCase() === 'paid' || i.status.toLowerCase() === 'pago'
    ).length
  }

  /**
   * @Function - getTotalPaid
   * @description - Calculates total amount paid from installments
   * @author - Vitor Hugo
   * @returns - number - Total paid amount
   */
  getTotalPaid(): number {
    if (!this.contract?.installments) return 0
    return this.contract.installments
      .filter(i => i.status.toLowerCase() === 'paid' || i.status.toLowerCase() === 'pago')
      .reduce((sum, i) => {
        const amount = typeof i.paymentAmount === 'string' 
          ? parseFloat(i.paymentAmount) 
          : (i.paymentAmount || 0)
        return sum + amount
      }, 0)
  }

  /**
   * @Function - getRemainingAmount
   * @description - Calculates remaining amount to be paid
   * @author - Vitor Hugo
   * @returns - number - Remaining amount
   */
  getRemainingAmount(): number {
    if (!this.contract) return 0
    const total = typeof this.contract.totalAmount === 'string' 
      ? parseFloat(this.contract.totalAmount) 
      : this.contract.totalAmount
    return total - this.getTotalPaid()
  }

  /**
   * @Function - getOverdueInstallmentsCount
   * @description - Counts the number of overdue installments
   * @author - Vitor Hugo
   * @returns - number - Count of overdue installments
   */
  getOverdueInstallmentsCount(): number {
    if (!this.contract?.installments) return 0
    return this.contract.installments.filter(
      i => i.status.toLowerCase() === 'overdue' || i.status.toLowerCase() === 'atrasado'
    ).length
  }
}


<div class="space-y-6">
  <!-- Header -->
  <div class="flex items-center justify-between">
    <div class="flex items-center space-x-4">
      <button appButton variant="ghost" size="sm" (click)="handleBack()">
        <lucide-icon [img]="ArrowLeftIcon" class="h-4 w-4 mr-2"></lucide-icon>
        Voltar
      </button>
      <div>
        <h1 class="text-3xl font-bold tracking-tight">Detalhes do Contrato</h1>
        <p class="text-muted-foreground">
          Visualize todas as informações do contrato e parcelas
        </p>
      </div>
    </div>
    @if (!isLoading && contract) {
      <button appButton variant="outline" (click)="handleEdit()">
        <lucide-icon [img]="EditIcon" class="h-4 w-4 mr-2"></lucide-icon>
        Editar Contrato
      </button>
    }
  </div>

  <!-- Loading State -->
  @if (isLoading) {
    <div class="text-center py-8">
      <p class="text-muted-foreground">Carregando detalhes do contrato...</p>
    </div>
  }

  <!-- Error Message -->
  @if (error) {
    <div class="w-full p-4 text-sm text-red-600 bg-red-50 border border-red-200 rounded-md">
      {{ error }}
    </div>
  }

  <!-- Contract Details -->
  @if (!isLoading && contract) {
    <!-- Summary Cards -->
    <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
      <!-- Total Amount -->
      <div class="bg-white rounded-lg border p-4">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-gray-600">Valor Total</p>
            <p class="text-2xl font-bold text-gray-900 mt-1">
              {{ formatCurrency(contract.totalAmount) }}
            </p>
          </div>
          <div class="h-12 w-12 bg-blue-100 rounded-lg flex items-center justify-center">
            <lucide-icon [img]="DollarSignIcon" class="h-6 w-6 text-blue-600"></lucide-icon>
          </div>
        </div>
      </div>

      <!-- Total Paid -->
      <div class="bg-white rounded-lg border p-4">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-gray-600">Total Pago</p>
            <p class="text-2xl font-bold text-green-600 mt-1">
              {{ formatCurrency(getTotalPaid()) }}
            </p>
          </div>
          <div class="h-12 w-12 bg-green-100 rounded-lg flex items-center justify-center">
            <lucide-icon [img]="CheckCircle2Icon" class="h-6 w-6 text-green-600"></lucide-icon>
          </div>
        </div>
      </div>

      <!-- Remaining Amount -->
      <div class="bg-white rounded-lg border p-4">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-gray-600">A Receber</p>
            <p class="text-2xl font-bold text-orange-600 mt-1">
              {{ formatCurrency(getRemainingAmount()) }}
            </p>
          </div>
          <div class="h-12 w-12 bg-orange-100 rounded-lg flex items-center justify-center">
            <lucide-icon [img]="ClockIcon" class="h-6 w-6 text-orange-600"></lucide-icon>
          </div>
        </div>
      </div>

      <!-- Installments Progress -->
      <div class="bg-white rounded-lg border p-4">
        <div class="flex items-center justify-between">
          <div>
            <p class="text-sm font-medium text-gray-600">Parcelas Pagas</p>
            <p class="text-2xl font-bold text-gray-900 mt-1">
              {{ getPaidInstallmentsCount() }}/{{ contract.installmentCount }}
            </p>
          </div>
          <div class="h-12 w-12 bg-purple-100 rounded-lg flex items-center justify-center">
            <lucide-icon [img]="CreditCardIcon" class="h-6 w-6 text-purple-600"></lucide-icon>
          </div>
        </div>
      </div>
    </div>

    <!-- Contract Information -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
      <!-- Left Column - Contract Details -->
      <div class="bg-white rounded-lg border p-6 space-y-4">
        <div class="flex items-center gap-2 pb-4 border-b">
          <lucide-icon [img]="FileTextIcon" class="h-5 w-5 text-gray-600"></lucide-icon>
          <h2 class="text-lg font-semibold">Informações do Contrato</h2>
        </div>

        <div class="space-y-3">
          <div class="flex justify-between items-start">
            <span class="text-sm font-medium text-gray-600">Valor por Parcela:</span>
            <span class="text-sm font-semibold text-gray-900">{{ formatCurrency(contract.installmentAmount) }}</span>
          </div>

          <div class="flex justify-between items-start">
            <span class="text-sm font-medium text-gray-600">Quantidade de Parcelas:</span>
            <span class="text-sm font-semibold text-gray-900">{{ contract.installmentCount }}x</span>
          </div>

          <div class="flex justify-between items-start">
            <span class="text-sm font-medium text-gray-600">Periodicidade:</span>
            <span class="text-sm font-semibold text-gray-900">{{ contract.periodicity }}</span>
          </div>

          <div class="flex justify-between items-start">
            <span class="text-sm font-medium text-gray-600">Primeiro Vencimento:</span>
            <span class="text-sm font-semibold text-gray-900">{{ formatDate(contract.firstDueDate) }}</span>
          </div>

          <div class="flex justify-between items-start">
            <span class="text-sm font-medium text-gray-600">Comissão:</span>
            <span class="text-sm font-semibold text-gray-900">
              {{ contract.commissionPercentage }}% ({{ formatCurrency(contract.commissionAmount) }})
            </span>
          </div>

          <div class="flex justify-between items-start">
            <span class="text-sm font-medium text-gray-600">Data de Criação:</span>
            <span class="text-sm font-semibold text-gray-900">{{ formatDate(contract.createdAt) }}</span>
          </div>

          @if (getOverdueInstallmentsCount() > 0) {
            <div class="pt-3 border-t">
              <div class="flex items-center gap-2 p-3 bg-red-50 border border-red-200 rounded-lg">
                <lucide-icon [img]="AlertCircleIcon" class="h-5 w-5 text-red-600"></lucide-icon>
                <span class="text-sm font-medium text-red-800">
                  {{ getOverdueInstallmentsCount() }} parcela(s) atrasada(s)
                </span>
              </div>
            </div>
          }

          @if (contract.notes) {
            <div class="pt-3 border-t">
              <span class="text-sm font-medium text-gray-600">Observações:</span>
              <p class="text-sm text-gray-900 mt-1">{{ contract.notes }}</p>
            </div>
          }
        </div>
      </div>

      <!-- Right Column - Event and Client Details -->
      <div class="space-y-6">
        <!-- Event Information -->
        @if (contract.event) {
          <div class="bg-white rounded-lg border p-6 space-y-4">
            <div class="flex items-center gap-2 pb-4 border-b">
              <lucide-icon [img]="CalendarIcon" class="h-5 w-5 text-gray-600"></lucide-icon>
              <h2 class="text-lg font-semibold">Informações do Evento</h2>
            </div>

            <div class="space-y-3">
              <div class="flex justify-between items-start">
                <span class="text-sm font-medium text-gray-600">Nome do Evento:</span>
                <span class="text-sm font-semibold text-gray-900">{{ contract.event.name }}</span>
              </div>

              <div class="flex justify-between items-start">
                <span class="text-sm font-medium text-gray-600">Data do Evento:</span>
                <span class="text-sm font-semibold text-gray-900">{{ formatDate(contract.event.eventDate) }}</span>
              </div>
            </div>
          </div>
        }

        <!-- Client Information -->
        @if (contract.client) {
          <div class="bg-white rounded-lg border p-6 space-y-4">
            <div class="flex items-center gap-2 pb-4 border-b">
              <lucide-icon [img]="UserIcon" class="h-5 w-5 text-gray-600"></lucide-icon>
              <h2 class="text-lg font-semibold">Informações do Cliente</h2>
            </div>

            <div class="space-y-3">
              <div class="flex justify-between items-start">
                <span class="text-sm font-medium text-gray-600">Nome do Cliente:</span>
                <span class="text-sm font-semibold text-gray-900">{{ contract.client.name }}</span>
              </div>
            </div>
          </div>
        }
      </div>
    </div>

    <!-- Installments List -->
    @if (contract.installments && contract.installments.length > 0) {
      <div class="bg-white rounded-lg border p-6 space-y-4">
        <div class="flex items-center gap-2 pb-4 border-b">
          <lucide-icon [img]="CreditCardIcon" class="h-5 w-5 text-gray-600"></lucide-icon>
          <h2 class="text-lg font-semibold">Parcelas do Contrato</h2>
        </div>

        <div class="rounded-md border">
          <app-table>
            <thead appTableHeader>
              <tr appTableRow>
                <th appTableHead>Nº</th>
                <th appTableHead>Valor</th>
                <th appTableHead>Vencimento</th>
                <th appTableHead>Status</th>
                <th appTableHead>Data Pagamento</th>
                <th appTableHead>Valor Pago</th>
                <th appTableHead>Observações</th>
              </tr>
            </thead>
            <tbody appTableBody>
              @for (installment of contract.installments; track installment.id) {
                <tr appTableRow>
                  <td appTableCell class="font-medium">{{ installment.installmentNumber }}</td>
                  <td appTableCell>{{ formatCurrency(installment.amount) }}</td>
                  <td appTableCell>{{ formatDate(installment.dueDate) }}</td>
                  <td appTableCell>
                    <span [class]="getStatusBadgeClass(installment.status)">
                      <lucide-icon [img]="getStatusIcon(installment.status)" class="h-3 w-3"></lucide-icon>
                      {{ getStatusText(installment.status) }}
                    </span>
                  </td>
                  <td appTableCell>
                    {{ installment.paymentDate ? formatDate(installment.paymentDate) : '-' }}
                  </td>
                  <td appTableCell>
                    {{ installment.paymentAmount ? formatCurrency(installment.paymentAmount) : '-' }}
                  </td>
                  <td appTableCell>
                    {{ installment.notes || '-' }}
                  </td>
                </tr>
              }
            </tbody>
          </app-table>
        </div>
      </div>
    }
  }
</div>
