// src/app/features/register/events/events-list/events-list.component.ts
import { Component, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { RouterModule } from '@angular/router'
import { FormsModule } from '@angular/forms'
import { LucideAngularModule, Plus, Edit, Trash2, Eye, Calendar, MapPin, ClipboardCheck } from 'lucide-angular'
import { firstValueFrom } from 'rxjs'

import { ButtonComponent } from '@shared/components/ui/button/button.component'
import { SearchBarComponent } from '@shared/components/ui/search-bar/search-bar.component'
import { ConfirmationModalComponent } from '@shared/components/ui/confirmation-modal/confirmation-modal.component'
import { 
  TableComponent, 
  TableHeaderComponent, 
  TableBodyComponent, 
  TableRowComponent, 
  TableHeadComponent, 
  TableCellComponent 
} from '@shared/components/ui/table/table.component'
import { EventService } from '@core/services/event.service'
import { ClientService } from '@core/services/client.service'
import { PackageService } from '@core/services/package.service'
import { UnitService } from '@core/services/unit.service'
import type { Event, Client, Package, Unit } from '@shared/models/api.types'
import { formatDateBR } from '@shared/utils/date.utils'

@Component({
  selector: 'app-events-list',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    FormsModule,
    LucideAngularModule,
    ButtonComponent,
    SearchBarComponent,
    ConfirmationModalComponent,
    TableComponent,
    TableHeaderComponent,
    TableBodyComponent,
    TableRowComponent,
    TableHeadComponent,
    TableCellComponent
  ],
  templateUrl: './events-list.component.html'
})
export class EventsListComponent implements OnInit {
  readonly PlusIcon = Plus
  readonly EditIcon = Edit
  readonly Trash2Icon = Trash2
  readonly EyeIcon = Eye
  readonly CalendarIcon = Calendar
  readonly MapPinIcon = MapPin
  readonly ClipboardCheckIcon = ClipboardCheck

  events: Event[] = []
  clients: Client[] = []
  packages: Package[] = []
  units: Unit[] = []
  searchTerm: string = ''
  filterStatus: string = 'todos'
  filterUnitId: string = ''
  isLoading: boolean = true
  error: string = ''
  showDeleteModal: boolean = false
  eventToDelete: Event | null = null
  isDeleting: boolean = false

  constructor(
    private eventService: EventService,
    private clientService: ClientService,
    private packageService: PackageService,
    private unitService: UnitService
  ) {}

  async ngOnInit(): Promise<void> {
    await this.loadData()
  }

  async loadData(): Promise<void> {
    try {
      this.isLoading = true
      this.error = ''

      const unitId = this.filterUnitId || undefined
      const [eventsResponse, clientsResponse, packagesResponse, unitsResponse] = await Promise.all([
        firstValueFrom(this.eventService.getEvents(unitId)),
        firstValueFrom(this.clientService.getClients()),
        firstValueFrom(this.packageService.getPackages()),
        firstValueFrom(this.unitService.getUnits(true))
      ])

      if (eventsResponse.success && eventsResponse.data) {
        this.events = eventsResponse.data
      } else {
        this.error = 'Erro ao carregar eventos'
      }

      if (clientsResponse.success && clientsResponse.data) {
        this.clients = clientsResponse.data as Client[]
      }

      if (packagesResponse.success && packagesResponse.data) {
        this.packages = packagesResponse.data
      }

      if (unitsResponse.success && unitsResponse.data) {
        this.units = unitsResponse.data
      }
    } catch (err: any) {
      this.error = err.message || 'Erro ao carregar dados'
    } finally {
      this.isLoading = false
    }
  }

  /**
   * @Function - onUnitFilterChange
   * @description - Handles unit filter change and reloads events
   * @author - Vitor Hugo
   * @returns - Promise<void>
   */
  async onUnitFilterChange(): Promise<void> {
    await this.loadData()
  }

  get filteredEvents(): Event[] {
    let filtered = this.events

    // Filter by search term
    if (this.searchTerm) {
      const searchLower = this.searchTerm.toLowerCase()
      filtered = filtered.filter(event => {
        const client = this.getClientName(event.clientId)
        const packageName = this.getPackageName(event.packageId)
        
        return event.name.toLowerCase().includes(searchLower) ||
               client.toLowerCase().includes(searchLower) ||
               packageName.toLowerCase().includes(searchLower) ||
               (event.location && event.location.toLowerCase().includes(searchLower))
      })
    }

    // Filter by status
    if (this.filterStatus !== 'todos') {
      filtered = filtered.filter(event => event.status === this.filterStatus)
    }

    return filtered
  }

  /**
   * @Function - handleDeleteClick
   * @description - Initiates the delete process by opening the confirmation modal and clearing previous errors
   * @author - Vitor Hugo
   * @param - event: Event - The event to be deleted
   * @returns - void
   */
  handleDeleteClick(event: Event): void {
    this.eventToDelete = event
    this.showDeleteModal = true
    this.error = '' // Clear previous errors
  }

  /**
   * @Function - handleConfirmDelete
   * @description - Handles the confirmation of event deletion with proper error handling for dependency constraints
   * @author - Vitor Hugo
   * @returns - Promise<void>
   */
  async handleConfirmDelete(): Promise<void> {
    if (!this.eventToDelete) return

    try {
      this.isDeleting = true
      const response = await firstValueFrom(
        this.eventService.deleteEvent(this.eventToDelete.id)
      )
      if (response.success) {
        this.events = this.events.filter(event => event.id !== this.eventToDelete!.id)
        this.showDeleteModal = false
        this.eventToDelete = null
      } else {
        // Handle error from response when success is false
        this.error = response.message || response.errors?.[0] || 'Erro ao excluir evento'
        this.showDeleteModal = false
        this.eventToDelete = null
      }
    } catch (err: any) {
      // Extract error message from HTTP error response
      if (err.error?.error?.message) {
        // Backend returned structured error with error.error.message
        this.error = err.error.error.message
      } else if (err.error?.message) {
        // Backend returned error with error.message
        this.error = err.error.message
      } else if (err.message) {
        // Generic error message
        this.error = err.message
      } else {
        // Fallback error message
        this.error = 'Erro ao excluir evento'
      }
      // Close modal to show error message clearly
      this.showDeleteModal = false
      this.eventToDelete = null
    } finally {
      this.isDeleting = false
    }
  }

  handleCancelDelete(): void {
    this.showDeleteModal = false
    this.eventToDelete = null
  }

  getClientName(clientId: string): string {
    const client = this.clients.find(c => c.id === clientId)
    return client?.name || 'Cliente não encontrado'
  }

  getPackageName(packageId: string): string {
    const pkg = this.packages.find(p => p.id === packageId)
    return pkg?.name || 'Pacote não encontrado'
  }

  formatDate(dateString: string): string {
    return formatDateBR(dateString)
  }

  getStatusColor(status: string): string {
    switch (status) {
      case 'Confirmado':
        return 'bg-green-100 text-green-800'
      case 'Agendado':
        return 'bg-blue-100 text-blue-800'
      case 'Realizado':
        return 'bg-gray-100 text-gray-800'
      case 'Cancelado':
        return 'bg-red-100 text-red-800'
      default:
        return 'bg-gray-100 text-gray-800'
    }
  }

  /**
   * @Function - getUnitName
   * @description - Gets the unit name from an event
   * @author - Vitor Hugo
   * @param - event: Event - The event to get unit from
   * @returns - string
   */
  getUnitName(event: Event): string | null {
    if (event.unit) {
      return event.unit.code || event.unit.name
    }
    return null
  }

  /**
   * @Function - getUnitColor
   * @description - Gets the unit color from an event
   * @author - Vitor Hugo
   * @param - event: Event - The event to get unit color from
   * @returns - string
   */
  getUnitColor(event: Event): string {
    return event.unit?.color || '#6c757d'
  }
}


<div class="space-y-6">
  <!-- Header -->
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-3xl font-bold tracking-tight">Eventos e Reservas</h1>
      <p class="text-muted-foreground">
        Gerencie os eventos e reservas dos clientes
      </p>
    </div>
    <button appButton variant="outline" routerLink="/cadastros/eventos/novo">
      <lucide-icon [img]="PlusIcon" class="mr-2 h-4 w-4"></lucide-icon>
      Nova Reserva
    </button>
  </div>

  <!-- Filtros -->
  <div class="flex items-center space-x-2">
    <div class="flex-1">
      <app-search-bar
        placeholder="Buscar por cliente, pacote ou local..."
        [(ngModel)]="searchTerm"
      ></app-search-bar>
    </div>
    <select
      [(ngModel)]="filterUnitId"
      (ngModelChange)="onUnitFilterChange()"
      class="flex h-10 w-48 items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
    >
      <option value="">Todas as unidades</option>
      @for (unit of units; track unit.id) {
        <option [value]="unit.id">{{ unit.name }}</option>
      }
    </select>
    <select
      [(ngModel)]="filterStatus"
      class="flex h-10 w-48 items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
    >
      <option value="todos">Todos os status</option>
      <option value="Agendado">Agendado</option>
      <option value="Confirmado">Confirmado</option>
      <option value="Realizado">Realizado</option>
      <option value="Cancelado">Cancelado</option>
    </select>
  </div>

  <!-- Error Message -->
  @if (error) {
    <div class="w-full p-3 text-sm text-red-600 bg-red-50 border border-red-200 rounded-md">
      {{ error }}
    </div>
  }

  <!-- Loading State -->
  @if (isLoading) {
    <div class="flex items-center justify-center h-64">
      <div class="text-center">
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto"></div>
        <p class="mt-2 text-muted-foreground">Carregando eventos...</p>
      </div>
    </div>
  }

  <!-- Tabela -->
  @if (!isLoading) {
    <div class="rounded-md border">
      <app-table>
        <thead appTableHeader>
          <tr appTableRow>
            <th appTableHead>Nome</th>
            <th appTableHead>Cliente</th>
            <th appTableHead>Pacote</th>
            <th appTableHead>Unidade</th>
            <th appTableHead>Data</th>
            <th appTableHead>Local</th>
            <th appTableHead>Status</th>
            <th appTableHead class="text-right">Ações</th>
          </tr>
        </thead>
        <tbody appTableBody>
          @for (event of filteredEvents; track event.id) {
            <tr appTableRow>
              <td appTableCell class="font-medium">{{ event.name }}</td>
              <td appTableCell>{{ getClientName(event.clientId) }}</td>
              <td appTableCell>{{ getPackageName(event.packageId) }}</td>
              <td appTableCell>
                @if (event.unit) {
                  <span 
                    class="inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium text-white"
                    [style.backgroundColor]="getUnitColor(event)"
                  >
                    {{ getUnitName(event) }}
                  </span>
                } @else {
                  <span class="text-muted-foreground">-</span>
                }
              </td>
              <td appTableCell>
                <div class="flex items-center space-x-2">
                  <lucide-icon [img]="CalendarIcon" class="h-4 w-4 text-muted-foreground"></lucide-icon>
                  <span>{{ formatDate(event.eventDate) }}</span>
                </div>
              </td>
              <td appTableCell>
                <div class="flex items-center space-x-2">
                  <lucide-icon [img]="MapPinIcon" class="h-4 w-4 text-muted-foreground"></lucide-icon>
                  <span class="max-w-xs truncate">{{ event.location || 'Não informado' }}</span>
                </div>
              </td>
              <td appTableCell>
                <span [class]="'inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ' + getStatusColor(event.status)">
                  {{ event.status }}
                </span>
              </td>
              <td appTableCell class="text-right">
                <div class="flex items-center justify-end space-x-2">
                  <button 
                    appButton 
                    variant="ghost" 
                    size="sm"
                    [routerLink]="['/cadastros/eventos', event.id, 'checklist']"
                    title="Checklist do evento"
                  >
                    <lucide-icon [img]="ClipboardCheckIcon" class="h-4 w-4"></lucide-icon>
                  </button>
                  <button 
                    appButton 
                    variant="ghost" 
                    size="sm" 
                    [routerLink]="['/cadastros/eventos/editar', event.id]"
                    title="Editar evento"
                  >
                    <lucide-icon [img]="EditIcon" class="h-4 w-4"></lucide-icon>
                  </button>
                  <button
                    appButton
                    variant="ghost"
                    size="sm"
                    (click)="handleDeleteClick(event)"
                    title="Excluir evento"
                  >
                    <lucide-icon [img]="Trash2Icon" class="h-4 w-4"></lucide-icon>
                  </button>
                </div>
              </td>
            </tr>
          }
        </tbody>
      </app-table>
    </div>
  }

  <!-- Empty State -->
  @if (!isLoading && filteredEvents.length === 0) {
    <div class="text-center py-8">
      <p class="text-muted-foreground">
        {{ searchTerm ? 'Nenhum evento encontrado.' : 'Nenhum evento cadastrado.' }}
      </p>
    </div>
  }

  <!-- Confirmation Modal -->
  <app-confirmation-modal
    [isOpen]="showDeleteModal"
    (onClose)="handleCancelDelete()"
    (onConfirm)="handleConfirmDelete()"
    title="Excluir Evento"
    [message]="'Tem certeza que deseja excluir o evento &quot;' + (eventToDelete?.name || '') + '&quot;? Esta ação não pode ser desfeita.'"
    confirmText="Excluir"
    cancelText="Cancelar"
    variant="danger"
    [loading]="isDeleting"></app-confirmation-modal>
</div>

// src/pages/register/events/EventsList.tsx
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Plus, Edit, Trash2, Eye, Calendar, Clock, MapPin } from 'lucide-react'
import { Button } from '@/components/ui/button/button'
import SearchBar from '@/components/ui/search-bar/SearchBar'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from '@/components/ui/data-table/table'

// Mock data - substituir por dados reais da API
const mockEvents = [
  {
    id: 1,
    cliente: 'João Silva',
    pacote: 'Pacote Básico',
    data: '2024-02-15',
    horario: '19:00',
    local: 'Salão de Festas ABC',
    convidados: 50,
    status: 'Confirmado',
    valor: 2500.00,
    dataCadastro: '2024-01-15'
  },
  {
    id: 2,
    cliente: 'Maria Santos',
    pacote: 'Pacote Premium + DJ',
    data: '2024-02-20',
    horario: '20:00',
    local: 'Espaço Eventos XYZ',
    convidados: 100,
    status: 'Pendente',
    valor: 4500.00,
    dataCadastro: '2024-01-20'
  },
  {
    id: 3,
    cliente: 'Pedro Oliveira',
    pacote: 'Serviço de DJ',
    data: '2024-02-25',
    horario: '21:00',
    local: 'Casa do Cliente',
    convidados: 30,
    status: 'Cancelado',
    valor: 800.00,
    dataCadastro: '2024-01-25'
  }
]

export default function EventsList() {
  const [events] = useState(mockEvents)
  const [searchTerm, setSearchTerm] = useState('')
  const [filterStatus, setFilterStatus] = useState('todos')

  const filteredEvents = events.filter(event => {
    const matchesSearch = event.cliente.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         event.pacote.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         event.local.toLowerCase().includes(searchTerm.toLowerCase())
    const matchesStatus = filterStatus === 'todos' || event.status === filterStatus
    return matchesSearch && matchesStatus
  })

  const handleDelete = (id: number) => {
    // Implementar lógica de exclusão
    console.log('Excluir evento:', id)
  }

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('pt-BR', {
      style: 'currency',
      currency: 'BRL'
    }).format(value)
  }

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('pt-BR')
  }

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Confirmado':
        return 'bg-green-100 text-green-800'
      case 'Pendente':
        return 'bg-yellow-100 text-yellow-800'
      case 'Cancelado':
        return 'bg-red-100 text-red-800'
      default:
        return 'bg-gray-100 text-gray-800'
    }
  }

  return (
    <div className='space-y-6'>
      {/* Header */}
      <div className='flex items-center justify-between'>
        <div>
          <h1 className='text-3xl font-bold tracking-tight'>Eventos e Reservas</h1>
          <p className='text-muted-foreground'>
            Gerencie os eventos e reservas dos clientes
          </p>
        </div>
        <Button variant='outline' asChild>
          <Link to='/cadastros/eventos/novo'>
            <Plus className='mr-2 h-4 w-4' />
            Nova Reserva
          </Link>
        </Button>
      </div>

      {/* Filtros */}
      <div className='flex items-center space-x-2'>
        <div className='flex-1'>
          <SearchBar
            placeholder='Buscar por cliente, pacote ou local...'
            value={searchTerm}
            onChange={setSearchTerm}
          />
        </div>
        <select
          value={filterStatus}
          onChange={(e) => setFilterStatus(e.target.value)}
          className='flex h-10 w-48 items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50'
        >
          <option value='todos'>Todos os status</option>
          <option value='Confirmado'>Confirmado</option>
          <option value='Pendente'>Pendente</option>
          <option value='Cancelado'>Cancelado</option>
        </select>
      </div>

      {/* Tabela */}
      <div className='rounded-md border'>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Cliente</TableHead>
              <TableHead>Pacote</TableHead>
              <TableHead>Data</TableHead>
              <TableHead>Horário</TableHead>
              <TableHead>Local</TableHead>
              <TableHead>Convidados</TableHead>
              <TableHead>Valor</TableHead>
              <TableHead>Status</TableHead>
              <TableHead className='text-right'>Ações</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filteredEvents.map((evento) => (
              <TableRow key={evento.id}>
                <TableCell className='font-medium'>{evento.cliente}</TableCell>
                <TableCell>{evento.pacote}</TableCell>
                <TableCell>
                  <div className='flex items-center space-x-2'>
                    <Calendar className='h-4 w-4 text-muted-foreground' />
                    <span>{formatDate(evento.data)}</span>
                  </div>
                </TableCell>
                <TableCell>
                  <div className='flex items-center space-x-2'>
                    <Clock className='h-4 w-4 text-muted-foreground' />
                    <span>{evento.horario}</span>
                  </div>
                </TableCell>
                <TableCell>
                  <div className='flex items-center space-x-2'>
                    <MapPin className='h-4 w-4 text-muted-foreground' />
                    <span className='max-w-xs truncate'>{evento.local}</span>
                  </div>
                </TableCell>
                <TableCell>{evento.convidados} pessoas</TableCell>
                <TableCell className='font-medium'>{formatCurrency(evento.valor)}</TableCell>
                <TableCell>
                  <span
                    className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${getStatusColor(evento.status)}`}
                  >
                    {evento.status}
                  </span>
                </TableCell>
                <TableCell className='text-right'>
                  <div className='flex items-center justify-end space-x-2'>
                    <Button variant='ghost' size='sm'>
                      <Eye className='h-4 w-4' />
                    </Button>
                    <Button variant='ghost' size='sm' asChild>
                      <Link to={`/cadastros/eventos/editar/${evento.id}`}>
                        <Edit className='h-4 w-4' />
                      </Link>
                    </Button>
                    <Button
                      variant='ghost'
                      size='sm'
                      onClick={() => handleDelete(evento.id)}
                    >
                      <Trash2 className='h-4 w-4' />
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      {/* Paginação - implementar quando necessário */}
      {filteredEvents.length === 0 && (
        <div className='text-center py-8'>
          <p className='text-muted-foreground'>
            {searchTerm ? 'Nenhum evento encontrado.' : 'Nenhum evento cadastrado.'}
          </p>
        </div>
      )}
    </div>
  )
}
