// src/app/features/register/events/events-form/events-form.component.ts
import { Component, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { Router, ActivatedRoute } from '@angular/router'
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms'
import { LucideAngularModule, ArrowLeft, Save, X } from 'lucide-angular'
import { firstValueFrom } from 'rxjs'

import { ButtonComponent } from '@shared/components/ui/button/button.component'
import { LabelComponent } from '@shared/components/ui/label/label.component'
import { EventService } from '@core/services/event.service'
import { ClientService } from '@core/services/client.service'
import { PackageService } from '@core/services/package.service'
import { UnitService } from '@core/services/unit.service'
import type { Client, Package, Unit, CreateEventRequest, UpdateEventRequest } from '@shared/models/api.types'

@Component({
  selector: 'app-events-form',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    LucideAngularModule,
    ButtonComponent,
    LabelComponent
  ],
  templateUrl: './events-form.component.html'
})
export class EventsFormComponent implements OnInit {
  readonly ArrowLeftIcon = ArrowLeft
  readonly SaveIcon = Save
  readonly XIcon = X

  eventForm!: FormGroup
  clients: Client[] = []
  packages: Package[] = []
  units: Unit[] = []
  isEditing: boolean = false
  eventId: string | null = null
  isLoading: boolean = false
  isLoadingData: boolean = true
  errorMessage: string = ''

  constructor(
    private fb: FormBuilder,
    private eventService: EventService,
    private clientService: ClientService,
    private packageService: PackageService,
    private unitService: UnitService,
    private router: Router,
    private route: ActivatedRoute
  ) {
    this.eventForm = this.fb.group({
      clientId: ['', [Validators.required]],
      packageId: ['', [Validators.required]],
      unitId: [''],
      name: ['', [Validators.required]],
      eventDate: ['', [Validators.required]],
      eventTime: ['', [Validators.required]],
      location: ['', [Validators.required]],
      guestCount: ['', [Validators.required, Validators.min(1)]],
      status: ['Pendente'],
      notes: ['']
    })
  }

  async ngOnInit(): Promise<void> {
    this.eventId = this.route.snapshot.paramMap.get('id')
    this.isEditing = !!this.eventId

    await this.loadClientsAndPackages()

    if (this.isEditing && this.eventId) {
      await this.loadEvent(this.eventId)
    }
    
    this.isLoadingData = false
  }

  async loadClientsAndPackages(): Promise<void> {
    try {
      const [clientsResponse, packagesResponse, unitsResponse] = await Promise.all([
        firstValueFrom(this.clientService.getClients()),
        firstValueFrom(this.packageService.getPackages()),
        firstValueFrom(this.unitService.getUnits(true))
      ])

      if (clientsResponse.success && clientsResponse.data) {
        this.clients = clientsResponse.data as Client[]
      }

      if (packagesResponse.success && packagesResponse.data) {
        this.packages = packagesResponse.data
      }

      if (unitsResponse.success && unitsResponse.data) {
        this.units = unitsResponse.data
      }
    } catch (err: any) {
      this.errorMessage = err.message || 'Erro ao carregar dados'
    }
  }

  async loadEvent(id: string): Promise<void> {
    try {
      const response = await firstValueFrom(this.eventService.getEventById(id))
      if (response.success && response.data) {
        const event = response.data
        this.eventForm.patchValue({
          clientId: event.clientId,
          packageId: event.packageId,
          unitId: event.unitId || '',
          name: event.name,
          eventDate: event.eventDate.split('T')[0],
          eventTime: this.formatTimeToString(event.eventTime),
          location: event.location,
          guestCount: event.guestCount,
          status: event.status,
          notes: event.notes || ''
        })
      } else {
        this.errorMessage = 'Erro ao carregar evento'
      }
    } catch (err: any) {
      this.errorMessage = err.message || 'Erro ao carregar evento'
    }
  }

  formatTimeToString(time: any): string {
    if (!time) return ''
    if (typeof time === 'string') {
      if (time.match(/^\d{2}:\d{2}$/)) return time
      if (time.includes('T')) {
        const date = new Date(time)
        return date.toTimeString().slice(0, 5)
      }
      return time
    }
    if (time instanceof Date) {
      return time.toTimeString().slice(0, 5)
    }
    return String(time)
  }

  async handleSubmit(): Promise<void> {
    if (this.eventForm.invalid) {
      Object.keys(this.eventForm.controls).forEach(key => {
        this.eventForm.controls[key].markAsTouched()
      })
      return
    }

    this.isLoading = true
    this.errorMessage = ''

    try {
      const formValue = this.eventForm.value
      const eventData = {
        clientId: formValue.clientId,
        packageId: formValue.packageId,
        unitId: formValue.unitId || undefined,
        name: formValue.name,
        eventDate: formValue.eventDate,
        eventTime: this.formatTimeToString(formValue.eventTime),
        location: formValue.location,
        guestCount: Number(formValue.guestCount),
        status: formValue.status,
        notes: formValue.notes || undefined
      }

      let response
      if (this.isEditing && this.eventId) {
        const updateData: UpdateEventRequest = eventData
        response = await firstValueFrom(this.eventService.updateEvent(this.eventId, updateData))
      } else {
        const createData: CreateEventRequest = eventData
        response = await firstValueFrom(this.eventService.createEvent(createData))
      }

      if (response.success) {
        this.router.navigate(['/cadastros/eventos'])
      } else {
        this.errorMessage = 'Erro ao salvar evento'
      }
    } catch (err: any) {
      this.errorMessage = err.message || 'Erro ao salvar evento'
    } finally {
      this.isLoading = false
    }
  }

  handleCancel(): void {
    this.router.navigate(['/cadastros/eventos'])
  }

  hasError(fieldName: string): boolean {
    const field = this.eventForm.get(fieldName)
    return !!(field?.invalid && field.touched)
  }

  getFieldError(fieldName: string): string {
    const field = this.eventForm.get(fieldName)
    if (field?.hasError('required') && field.touched) {
      return 'Campo obrigatório'
    }
    if (field?.hasError('min') && field.touched) {
      return 'Valor deve ser maior que zero'
    }
    return ''
  }

  formatCurrency(value: number): string {
    return new Intl.NumberFormat('pt-BR', {
      style: 'currency',
      currency: 'BRL'
    }).format(value)
  }
}


<div class="space-y-6">
  <!-- Header -->
  <div class="flex items-center space-x-4">
    <button appButton variant="ghost" size="sm" (click)="handleCancel()">
      <lucide-icon [img]="ArrowLeftIcon" class="h-4 w-4 mr-2"></lucide-icon>
      Voltar
    </button>
    <div>
      <h1 class="text-3xl font-bold tracking-tight">
        {{ isEditing ? 'Editar Evento' : 'Nova Reserva' }}
      </h1>
      <p class="text-muted-foreground">
        {{ isEditing ? 'Atualize as informações do evento' : 'Preencha os dados da nova reserva' }}
      </p>
    </div>
  </div>

  <!-- Loading State -->
  @if (isLoadingData) {
    <div class="flex items-center justify-center h-64">
      <div class="text-center">
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto"></div>
        <p class="mt-2 text-muted-foreground">Carregando...</p>
      </div>
    </div>
  }

  <!-- Error message -->
  @if (errorMessage) {
    <div class="bg-red-50 border border-red-200 rounded-md p-4">
      <p class="text-red-600">{{ errorMessage }}</p>
    </div>
  }

  <!-- Formulário -->
  @if (!isLoadingData) {
    <form [formGroup]="eventForm" (ngSubmit)="handleSubmit()" class="space-y-6">
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <!-- Cliente -->
        <div class="space-y-2">
          <label appLabel htmlFor="clientId">Cliente *</label>
          <select
            id="clientId"
            formControlName="clientId"
            [class]="'flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 ' + (hasError('clientId') ? 'border-red-500' : '')"
          >
            <option value="">Selecione um cliente</option>
            @for (client of clients; track client.id) {
              <option [value]="client.id">{{ client.name }}</option>
            }
          </select>
          @if (hasError('clientId')) {
            <p class="text-sm text-red-500">{{ getFieldError('clientId') }}</p>
          }
        </div>

        <!-- Pacote -->
        <div class="space-y-2">
          <label appLabel htmlFor="packageId">Pacote/Serviço *</label>
          <select
            id="packageId"
            formControlName="packageId"
            [class]="'flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 ' + (hasError('packageId') ? 'border-red-500' : '')"
          >
            <option value="">Selecione um pacote</option>
            @for (pkg of packages; track pkg.id) {
              <option [value]="pkg.id">
                {{ pkg.name }} - {{ formatCurrency(pkg.price) }}
              </option>
            }
          </select>
          @if (hasError('packageId')) {
            <p class="text-sm text-red-500">{{ getFieldError('packageId') }}</p>
          }
        </div>

        <!-- Unidade -->
        <div class="space-y-2">
          <label appLabel htmlFor="unitId">Unidade</label>
          <select
            id="unitId"
            formControlName="unitId"
            class="flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
          >
            <option value="">Todas as unidades</option>
            @for (unit of units; track unit.id) {
              <option [value]="unit.id">
                {{ unit.name }}@if (unit.code) { ({{ unit.code }})}
              </option>
            }
          </select>
        </div>

        <!-- Nome do Evento -->
        <div class="space-y-2">
          <label appLabel htmlFor="name">Nome do Evento *</label>
          <input
            type="text"
            id="name"
            formControlName="name"
            placeholder="Ex: Casamento João e Maria"
            [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('name') ? 'border-red-500' : '')"
          />
          @if (hasError('name')) {
            <p class="text-sm text-red-500">{{ getFieldError('name') }}</p>
          }
        </div>

        <!-- Data -->
        <div class="space-y-2">
          <label appLabel htmlFor="eventDate">Data *</label>
          <input
            type="date"
            id="eventDate"
            formControlName="eventDate"
            [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('eventDate') ? 'border-red-500' : '')"
          />
          @if (hasError('eventDate')) {
            <p class="text-sm text-red-500">{{ getFieldError('eventDate') }}</p>
          }
        </div>

        <!-- Horário -->
        <div class="space-y-2">
          <label appLabel htmlFor="eventTime">Horário *</label>
          <input
            type="time"
            id="eventTime"
            formControlName="eventTime"
            [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('eventTime') ? 'border-red-500' : '')"
          />
          @if (hasError('eventTime')) {
            <p class="text-sm text-red-500">{{ getFieldError('eventTime') }}</p>
          }
        </div>

        <!-- Local -->
        <div class="space-y-2">
          <label appLabel htmlFor="location">Local *</label>
          <input
            type="text"
            id="location"
            formControlName="location"
            placeholder="Ex: Salão de Festas Jardim das Flores"
            [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('location') ? 'border-red-500' : '')"
          />
          @if (hasError('location')) {
            <p class="text-sm text-red-500">{{ getFieldError('location') }}</p>
          }
        </div>

        <!-- Número de Convidados -->
        <div class="space-y-2">
          <label appLabel htmlFor="guestCount">Número de Convidados *</label>
          <input
            type="number"
            min="1"
            id="guestCount"
            formControlName="guestCount"
            placeholder="Ex: 150"
            [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('guestCount') ? 'border-red-500' : '')"
          />
          @if (hasError('guestCount')) {
            <p class="text-sm text-red-500">{{ getFieldError('guestCount') }}</p>
          }
        </div>

        <!-- Status -->
        <div class="space-y-2">
          <label appLabel htmlFor="status">Status</label>
          <select
            id="status"
            formControlName="status"
            class="flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
          >
            <option value="Pendente">Pendente</option>
            <option value="Confirmado">Confirmado</option>
            <option value="Realizado">Realizado</option>
            <option value="Cancelado">Cancelado</option>
          </select>
        </div>
      </div>

      <!-- Notas -->
      <div class="space-y-2">
        <label appLabel htmlFor="notes">Notas</label>
        <textarea
          id="notes"
          formControlName="notes"
          placeholder="Informações adicionais sobre o evento (ex: Decoração em tons de azul e branco)"
          class="flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
          rows="3"
        ></textarea>
      </div>

      <!-- Botões -->
      <div class="flex items-center justify-end space-x-2 pt-6 border-t">
        <button appButton type="button" variant="outline" (click)="handleCancel()" [disabled]="isLoading">
          <lucide-icon [img]="XIcon" class="h-4 w-4 mr-2"></lucide-icon>
          Cancelar
        </button>
        <button appButton type="submit" variant="outline" [disabled]="isLoading">
          <lucide-icon [img]="SaveIcon" class="h-4 w-4 mr-2"></lucide-icon>
          {{ isLoading ? 'Salvando...' : (isEditing ? 'Atualizar' : 'Salvar') }}
        </button>
      </div>
    </form>
  }
</div>

// src/pages/register/events/EventsForm.tsx
import { useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, Save, X } from 'lucide-react'
import { Button } from '@/components/ui/button/button'
import { Input } from '@/components/ui/input/input'
import { Label } from '@/components/ui/label/label'

interface EventFormData {
  cliente: string
  pacote: string
  data: string
  horario: string
  local: string
  convidados: string
  observacoes: string
  status: 'Confirmado' | 'Pendente' | 'Cancelado'
}

export default function EventForm() {
  const navigate = useNavigate()
  const { id } = useParams()
  const isEditing = Boolean(id)

  const [formData, setFormData] = useState<EventFormData>({
    cliente: '',
    pacote: '',
    data: '',
    horario: '',
    local: '',
    convidados: '',
    observacoes: '',
    status: 'Pendente'
  })

  const [errors, setErrors] = useState<Partial<EventFormData>>({})

  // Mock data para selects - substituir por dados reais da API
  const mockClients = ['João Silva', 'Maria Santos', 'Pedro Oliveira']
  const mockPacotes = ['Pacote Básico', 'Pacote Premium', 'Serviço de DJ', 'Decoração Premium']

  const handleInputChange = (field: keyof EventFormData, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }))
    // Limpar erro do campo quando usuário começar a digitar
    if (errors[field]) {
      setErrors(prev => ({ ...prev, [field]: undefined }))
    }
  }

  const validateForm = (): boolean => {
    const newErrors: Partial<EventFormData> = {}

    if (!formData.cliente.trim()) {
      newErrors.cliente = 'Cliente é obrigatório'
    }

    if (!formData.pacote.trim()) {
      newErrors.pacote = 'Pacote é obrigatório'
    }

    if (!formData.data.trim()) {
      newErrors.data = 'Data é obrigatória'
    }

    if (!formData.horario.trim()) {
      newErrors.horario = 'Horário é obrigatório'
    }

    if (!formData.local.trim()) {
      newErrors.local = 'Local é obrigatório'
    }

    if (!formData.convidados.trim()) {
      newErrors.convidados = 'Número de convidados é obrigatório'
    } else if (isNaN(Number(formData.convidados)) || Number(formData.convidados) <= 0) {
      newErrors.convidados = 'Número de convidados deve ser um número válido'
    }

    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!validateForm()) {
      return
    }

    // Implementar lógica de salvamento
    console.log('Salvando evento:', formData)
    
    // Simular salvamento
    setTimeout(() => {
      navigate('/cadastros/eventos')
    }, 1000)
  }

  const handleCancel = () => {
    navigate('/cadastros/eventos')
  }

  return (
    <div className='space-y-6'>
      {/* Header */}
      <div className='flex items-center space-x-4'>
        <Button variant='ghost' size='sm' onClick={handleCancel}>
          <ArrowLeft className='h-4 w-4 mr-2' />
          Voltar
        </Button>
        <div>
          <h1 className='text-3xl font-bold tracking-tight'>
            {isEditing ? 'Editar Evento' : 'Nova Reserva'}
          </h1>
          <p className='text-muted-foreground'>
            {isEditing 
              ? 'Atualize as informações do evento' 
              : 'Preencha os dados da nova reserva'
            }
          </p>
        </div>
      </div>

      {/* Formulário */}
      <form onSubmit={handleSubmit} className='space-y-6'>
        <div className='grid grid-cols-1 md:grid-cols-2 gap-6'>
          {/* Cliente */}
          <div className='space-y-2'>
            <Label htmlFor='cliente'>Cliente *</Label>
            <select
              id='cliente'
              value={formData.cliente}
              onChange={(e) => handleInputChange('cliente', e.target.value)}
              className={`flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 ${errors.cliente ? 'border-red-500' : ''}`}
            >
              <option value=''>Selecione um cliente</option>
              {mockClients.map((cliente) => (
                <option key={cliente} value={cliente}>
                  {cliente}
                </option>
              ))}
            </select>
            {errors.cliente && (
              <p className='text-sm text-red-500'>{errors.cliente}</p>
            )}
          </div>

          {/* Pacote */}
          <div className='space-y-2'>
            <Label htmlFor='pacote'>Pacote/Serviço *</Label>
            <select
              id='pacote'
              value={formData.pacote}
              onChange={(e) => handleInputChange('pacote', e.target.value)}
              className={`flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 ${errors.pacote ? 'border-red-500' : ''}`}
            >
              <option value=''>Selecione um pacote</option>
              {mockPacotes.map((pacote) => (
                <option key={pacote} value={pacote}>
                  {pacote}
                </option>
              ))}
            </select>
            {errors.pacote && (
              <p className='text-sm text-red-500'>{errors.pacote}</p>
            )}
          </div>

          {/* Data */}
          <div className='space-y-2'>
            <Label htmlFor='data'>Data *</Label>
            <Input
              id='data'
              type='date'
              value={formData.data}
              onChange={(e) => handleInputChange('data', e.target.value)}
              className={errors.data ? 'border-red-500' : ''}
            />
            {errors.data && (
              <p className='text-sm text-red-500'>{errors.data}</p>
            )}
          </div>

          {/* Horário */}
          <div className='space-y-2'>
            <Label htmlFor='horario'>Horário *</Label>
            <Input
              id='horario'
              type='time'
              value={formData.horario}
              onChange={(e) => handleInputChange('horario', e.target.value)}
              className={errors.horario ? 'border-red-500' : ''}
            />
            {errors.horario && (
              <p className='text-sm text-red-500'>{errors.horario}</p>
            )}
          </div>

          {/* Local */}
          <div className='space-y-2'>
            <Label htmlFor='local'>Local *</Label>
            <Input
              id='local'
              value={formData.local}
              onChange={(e) => handleInputChange('local', e.target.value)}
              placeholder='Local do evento'
              className={errors.local ? 'border-red-500' : ''}
            />
            {errors.local && (
              <p className='text-sm text-red-500'>{errors.local}</p>
            )}
          </div>

          {/* Convidados */}
          <div className='space-y-2'>
            <Label htmlFor='convidados'>Número de Convidados *</Label>
            <Input
              id='convidados'
              type='number'
              value={formData.convidados}
              onChange={(e) => handleInputChange('convidados', e.target.value)}
              placeholder='Ex: 50'
              min='1'
              className={errors.convidados ? 'border-red-500' : ''}
            />
            {errors.convidados && (
              <p className='text-sm text-red-500'>{errors.convidados}</p>
            )}
          </div>

          {/* Status */}
          <div className='space-y-2'>
            <Label htmlFor='status'>Status</Label>
            <select
              id='status'
              value={formData.status}
              onChange={(e) => handleInputChange('status', e.target.value as 'Confirmado' | 'Pendente' | 'Cancelado')}
              className='flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50'
            >
              <option value='Pendente'>Pendente</option>
              <option value='Confirmado'>Confirmado</option>
              <option value='Cancelado'>Cancelado</option>
            </select>
          </div>
        </div>

        {/* Observações */}
        <div className='space-y-2'>
          <Label htmlFor='observacoes'>Observações</Label>
          <textarea
            id='observacoes'
            value={formData.observacoes}
            onChange={(e) => handleInputChange('observacoes', e.target.value)}
            placeholder='Informações adicionais sobre o evento'
            className='flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50'
            rows={3}
          />
        </div>

        {/* Botões */}
        <div className='flex items-center justify-end space-x-2 pt-6 border-t'>
          <Button type='button' variant='outline' onClick={handleCancel}>
            <X className='h-4 w-4 mr-2' />
            Cancelar
          </Button>
          <Button type='submit' variant='outline'>
            <Save className='h-4 w-4 mr-2' />
            {isEditing ? 'Atualizar' : 'Salvar'}
          </Button>
        </div>
      </form>
    </div>
  )
}
