// src/pages/register/users/UserList.tsx
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Plus, Edit, Trash2, Eye, User, Shield, UserCheck } from 'lucide-react'
import { Button } from '@/components/ui/button/button'
import SearchBar from '@/components/ui/search-bar/SearchBar'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from '@/components/ui/data-table/table'

// Mock data - substituir por dados reais da API
const mockUsuarios = [
  {
    id: 1,
    nome: 'Admin Sistema',
    email: 'admin@easybuffet.com',
    perfil: 'Administrador',
    status: 'Ativo',
    ultimoAcesso: '2024-01-15T10:30:00',
    dataCadastro: '2024-01-01'
  },
  {
    id: 2,
    nome: 'João Atendimento',
    email: 'joao@easybuffet.com',
    perfil: 'Atendimento',
    status: 'Ativo',
    ultimoAcesso: '2024-01-14T15:45:00',
    dataCadastro: '2024-01-05'
  },
  {
    id: 3,
    nome: 'Maria Vendas',
    email: 'maria@easybuffet.com',
    perfil: 'Vendedor',
    status: 'Inativo',
    ultimoAcesso: '2024-01-10T09:20:00',
    dataCadastro: '2024-01-08'
  }
]

export default function UsuariosList() {
  const [usuarios] = useState(mockUsuarios)
  const [searchTerm, setSearchTerm] = useState('')
  const [filterPerfil, setFilterPerfil] = useState('todos')
  const [filterStatus, setFilterStatus] = useState('todos')

  const filteredUsuarios = usuarios.filter(usuario => {
    const matchesSearch = usuario.nome.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         usuario.email.toLowerCase().includes(searchTerm.toLowerCase())
    const matchesPerfil = filterPerfil === 'todos' || usuario.perfil === filterPerfil
    const matchesStatus = filterStatus === 'todos' || usuario.status === filterStatus
    return matchesSearch && matchesPerfil && matchesStatus
  })

  const handleDelete = (id: number) => {
    // Implementar lógica de exclusão
    console.log('Excluir usuário:', id)
  }

  const formatDateTime = (dateString: string) => {
    return new Date(dateString).toLocaleString('pt-BR')
  }

  const getPerfilIcon = (perfil: string) => {
    switch (perfil) {
      case 'Administrador':
        return <Shield className='h-4 w-4 text-red-600' />
      case 'Atendimento':
        return <UserCheck className='h-4 w-4 text-blue-600' />
      case 'Vendedor':
        return <User className='h-4 w-4 text-green-600' />
      default:
        return <User className='h-4 w-4 text-gray-600' />
    }
  }

  const getPerfilColor = (perfil: string) => {
    switch (perfil) {
      case 'Administrador':
        return 'bg-red-100 text-red-800'
      case 'Atendimento':
        return 'bg-blue-100 text-blue-800'
      case 'Vendedor':
        return 'bg-green-100 text-green-800'
      default:
        return 'bg-gray-100 text-gray-800'
    }
  }

  return (
    <div className='space-y-6'>
      {/* Header */}
      <div className='flex items-center justify-between'>
        <div>
          <h1 className='text-3xl font-bold tracking-tight'>Usuários</h1>
          <p className='text-muted-foreground'>
            Gerencie os usuários e perfis de acesso ao sistema
          </p>
        </div>
        <Button variant='outline' asChild>
          <Link to='/cadastros/usuarios/novo'>
            <Plus className='mr-2 h-4 w-4' />
            Novo Usuário
          </Link>
        </Button>
      </div>

      {/* Filtros */}
      <div className='flex items-center space-x-2'>
        <div className='flex-1'>
          <SearchBar
            placeholder='Buscar por nome ou email...'
            value={searchTerm}
            onChange={setSearchTerm}
          />
        </div>
        <select
          value={filterPerfil}
          onChange={(e) => setFilterPerfil(e.target.value)}
          className='flex h-10 w-48 items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50'
        >
          <option value='todos'>Todos os perfis</option>
          <option value='Administrador'>Administrador</option>
          <option value='Atendimento'>Atendimento</option>
          <option value='Vendedor'>Vendedor</option>
        </select>
        <select
          value={filterStatus}
          onChange={(e) => setFilterStatus(e.target.value)}
          className='flex h-10 w-48 items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50'
        >
          <option value='todos'>Todos os status</option>
          <option value='Ativo'>Ativo</option>
          <option value='Inativo'>Inativo</option>
        </select>
      </div>

      {/* Tabela */}
      <div className='rounded-md border'>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Nome</TableHead>
              <TableHead>Email</TableHead>
              <TableHead>Perfil</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Último Acesso</TableHead>
              <TableHead>Data Cadastro</TableHead>
              <TableHead className='text-right'>Ações</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filteredUsuarios.map((usuario) => (
              <TableRow key={usuario.id}>
                <TableCell className='font-medium'>
                  <div className='flex items-center space-x-2'>
                    <User className='h-4 w-4 text-muted-foreground' />
                    <span>{usuario.nome}</span>
                  </div>
                </TableCell>
                <TableCell>{usuario.email}</TableCell>
                <TableCell>
                  <div className='flex items-center space-x-2'>
                    {getPerfilIcon(usuario.perfil)}
                    <span
                      className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${getPerfilColor(usuario.perfil)}`}
                    >
                      {usuario.perfil}
                    </span>
                  </div>
                </TableCell>
                <TableCell>
                  <span
                    className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${
                      usuario.status === 'Ativo'
                        ? 'bg-green-100 text-green-800'
                        : 'bg-red-100 text-red-800'
                    }`}
                  >
                    {usuario.status}
                  </span>
                </TableCell>
                <TableCell className='text-sm text-muted-foreground'>
                  {formatDateTime(usuario.ultimoAcesso)}
                </TableCell>
                <TableCell className='text-sm text-muted-foreground'>
                  {new Date(usuario.dataCadastro).toLocaleDateString('pt-BR')}
                </TableCell>
                <TableCell className='text-right'>
                  <div className='flex items-center justify-end space-x-2'>
                    <Button variant='ghost' size='sm'>
                      <Eye className='h-4 w-4' />
                    </Button>
                    <Button variant='ghost' size='sm' asChild>
                      <Link to={`/cadastros/usuarios/editar/${usuario.id}`}>
                        <Edit className='h-4 w-4' />
                      </Link>
                    </Button>
                    <Button
                      variant='ghost'
                      size='sm'
                      onClick={() => handleDelete(usuario.id)}
                    >
                      <Trash2 className='h-4 w-4' />
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      {/* Paginação - implementar quando necessário */}
      {filteredUsuarios.length === 0 && (
        <div className='text-center py-8'>
          <p className='text-muted-foreground'>
            {searchTerm ? 'Nenhum usuário encontrado.' : 'Nenhum usuário cadastrado.'}
          </p>
        </div>
      )}
    </div>
  )
}

// src/app/features/register/users/user-list/user-list.component.ts
import { Component, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { Router, RouterModule } from '@angular/router'
import { FormsModule } from '@angular/forms'
import { LucideAngularModule, Plus, Edit, Trash2, Shield } from 'lucide-angular'
import { firstValueFrom } from 'rxjs'

import { ButtonComponent } from '@shared/components/ui/button/button.component'
import { SearchBarComponent } from '@shared/components/ui/search-bar/search-bar.component'
import { ConfirmationModalComponent } from '@shared/components/ui/confirmation-modal/confirmation-modal.component'
import { 
  TableComponent, 
  TableHeaderComponent, 
  TableBodyComponent, 
  TableRowComponent, 
  TableHeadComponent, 
  TableCellComponent 
} from '@shared/components/ui/table/table.component'
import { UserService } from '@core/services/user.service'
import type { User } from '@shared/models/api.types'
import { formatDateBR } from '@shared/utils/date.utils'

@Component({
  selector: 'app-user-list',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    FormsModule,
    LucideAngularModule,
    ButtonComponent,
    SearchBarComponent,
    ConfirmationModalComponent,
    TableComponent,
    TableHeaderComponent,
    TableBodyComponent,
    TableRowComponent,
    TableHeadComponent,
    TableCellComponent
  ],
  templateUrl: './user-list.component.html'
})
export class UserListComponent implements OnInit {
  readonly PlusIcon = Plus
  readonly EditIcon = Edit
  readonly Trash2Icon = Trash2
  readonly ShieldIcon = Shield

  users: User[] = []
  searchTerm: string = ''
  isLoading: boolean = true
  error: string = ''
  showDeleteModal: boolean = false
  userToDelete: User | null = null
  isDeleting: boolean = false

  constructor(
    private userService: UserService,
    private router: Router
  ) {}

  /**
   * @Function - ngOnInit
   * @description - Lifecycle hook that runs when component initializes, loads users
   * @author - Vitor Hugo
   * @returns - Promise<void>
   */
  async ngOnInit(): Promise<void> {
    await this.loadUsers()
  }

  /**
   * @Function - loadUsers
   * @description - Fetches all users from the API and updates the component state
   * @author - Vitor Hugo
   * @returns - Promise<void>
   */
  async loadUsers(): Promise<void> {
    try {
      this.isLoading = true
      this.error = ''
      const response = await firstValueFrom(this.userService.getUsers())
      if (response.success && response.data) {
        this.users = response.data as User[]
      } else {
        this.error = 'Erro ao carregar usuários'
      }
    } catch (err: any) {
      this.error = err.message || 'Erro ao carregar usuários'
    } finally {
      this.isLoading = false
    }
  }

  /**
   * @Function - filteredUsers
   * @description - Filters users based on search term (name, email, role)
   * @author - Vitor Hugo
   * @returns - User[] - Filtered array of users
   */
  get filteredUsers(): User[] {
    if (!this.searchTerm) {
      return this.users
    }
    
    const searchLower = this.searchTerm.toLowerCase()
    return this.users.filter(user =>
      user.name.toLowerCase().includes(searchLower) ||
      user.email.toLowerCase().includes(searchLower) ||
      user.role.toLowerCase().includes(searchLower)
    )
  }

  /**
   * @Function - handleDeleteClick
   * @description - Initiates the delete process by opening the confirmation modal
   * @author - Vitor Hugo
   * @param - user: User - The user to be deleted
   * @returns - void
   */
  handleDeleteClick(user: User): void {
    this.userToDelete = user
    this.showDeleteModal = true
    this.error = ''
  }

  /**
   * @Function - handleConfirmDelete
   * @description - Handles the confirmation of user deletion with proper error handling
   * @author - Vitor Hugo
   * @returns - Promise<void>
   */
  async handleConfirmDelete(): Promise<void> {
    if (!this.userToDelete) return

    try {
      this.isDeleting = true
      const response = await firstValueFrom(
        this.userService.deleteUser(this.userToDelete.id)
      )
      if (response.success) {
        this.users = this.users.filter(user => user.id !== this.userToDelete!.id)
        this.showDeleteModal = false
        this.userToDelete = null
      } else {
        this.error = response.message || response.errors?.[0] || 'Erro ao excluir usuário'
        this.showDeleteModal = false
        this.userToDelete = null
      }
    } catch (err: any) {
      if (err.error?.error?.message) {
        this.error = err.error.error.message
      } else if (err.error?.message) {
        this.error = err.error.message
      } else if (err.message) {
        this.error = err.message
      } else {
        this.error = 'Erro ao excluir usuário'
      }
      this.showDeleteModal = false
      this.userToDelete = null
    } finally {
      this.isDeleting = false
    }
  }

  /**
   * @Function - handleCancelDelete
   * @description - Cancels the delete operation and closes the modal
   * @author - Vitor Hugo
   * @returns - void
   */
  handleCancelDelete(): void {
    this.showDeleteModal = false
    this.userToDelete = null
  }

  /**
   * @Function - formatDate
   * @description - Formats ISO date string to Brazilian date format
   * @author - Vitor Hugo
   * @param - dateString: string - ISO date string
   * @returns - string - Formatted date in Brazilian format
   */
  formatDate(dateString: string): string {
    return formatDateBR(dateString)
  }

  /**
   * @Function - getRoleBadgeClass
   * @description - Returns the CSS class for role badge based on user role
   * @author - Vitor Hugo
   * @param - role: string - User role (Administrador or Auxiliar)
   * @returns - string - CSS classes for badge styling
   */
  getRoleBadgeClass(role: string): string {
    return role === 'Administrador'
      ? 'inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 border-transparent bg-purple-100 text-purple-800'
      : 'inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 border-transparent bg-blue-100 text-blue-800'
  }

  /**
   * @Function - getStatusBadgeClass
   * @description - Returns the CSS class for status badge based on user status
   * @author - Vitor Hugo
   * @param - status: string - User status (Ativo or Inativo)
   * @returns - string - CSS classes for badge styling
   */
  getStatusBadgeClass(status: string): string {
    return status === 'Ativo'
      ? 'inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 border-transparent bg-green-100 text-green-800'
      : 'inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 border-transparent bg-gray-100 text-gray-800'
  }
}


<div class="space-y-6">
  <!-- Header -->
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-3xl font-bold tracking-tight">Usuários</h1>
      <p class="text-muted-foreground">
        Gerencie os usuários e permissões do sistema
      </p>
    </div>
    <button appButton variant="outline" routerLink="/cadastros/usuarios/novo">
      <lucide-icon [img]="PlusIcon" class="mr-2 h-4 w-4"></lucide-icon>
      Novo Usuário
    </button>
  </div>

  <!-- Filtros -->
  <div class="flex items-center space-x-2">
    <div class="flex-1">
      <app-search-bar
        placeholder="Buscar por nome, email ou função..."
        [(ngModel)]="searchTerm"
      ></app-search-bar>
    </div>
  </div>

  <!-- Error Message -->
  @if (error) {
    <div class="w-full p-3 text-sm text-red-600 bg-red-50 border border-red-200 rounded-md">
      {{ error }}
    </div>
  }

  <!-- Loading State -->
  @if (isLoading) {
    <div class="text-center py-8">
      <p class="text-muted-foreground">Carregando usuários...</p>
    </div>
  }

  <!-- Tabela -->
  @if (!isLoading) {
    <div class="rounded-md border">
    <app-table>
      <thead appTableHeader>
        <tr appTableRow>
          <th appTableHead>Nome</th>
          <th appTableHead>Email</th>
          <th appTableHead>Telefone</th>
          <th appTableHead>Função</th>
          <th appTableHead>Status</th>
          <th appTableHead>Data Cadastro</th>
          <th appTableHead class="text-right">Ações</th>
        </tr>
      </thead>
      <tbody appTableBody>
        @for (user of filteredUsers; track user.id) {
          <tr appTableRow>
            <td appTableCell class="font-medium">{{ user.name }}</td>
            <td appTableCell>{{ user.email }}</td>
            <td appTableCell>{{ user.phone || '-' }}</td>
            <td appTableCell>
              <span [class]="getRoleBadgeClass(user.role)">
                {{ user.role }}
              </span>
            </td>
            <td appTableCell>
              <span [class]="getStatusBadgeClass(user.status)">
                {{ user.status }}
              </span>
            </td>
            <td appTableCell>{{ formatDate(user.createdAt) }}</td>
            <td appTableCell class="text-right">
              <div class="flex items-center justify-end space-x-2">
                <button 
                  appButton 
                  variant="ghost" 
                  size="sm" 
                  [routerLink]="['/cadastros/usuarios/editar', user.id]"
                  title="Editar usuário"
                >
                  <lucide-icon [img]="EditIcon" class="h-4 w-4"></lucide-icon>
                </button>
                <button
                  appButton
                  variant="ghost"
                  size="sm"
                  (click)="handleDeleteClick(user)"
                  title="Excluir usuário"
                >
                  <lucide-icon [img]="Trash2Icon" class="h-4 w-4"></lucide-icon>
                </button>
              </div>
            </td>
          </tr>
        }
      </tbody>
    </app-table>
    </div>
  }

  <!-- Empty State -->
  @if (!isLoading && filteredUsers.length === 0) {
    <div class="text-center py-8">
      <p class="text-muted-foreground">
        {{ searchTerm ? 'Nenhum usuário encontrado.' : 'Nenhum usuário cadastrado.' }}
      </p>
    </div>
  }

  <!-- Confirmation Modal -->
  <app-confirmation-modal
    [isOpen]="showDeleteModal"
    (onClose)="handleCancelDelete()"
    (onConfirm)="handleConfirmDelete()"
    title="Excluir Usuário"
    [message]="'Tem certeza que deseja excluir o usuário &quot;' + (userToDelete?.name || '') + '&quot;? Esta ação não pode ser desfeita.'"
    confirmText="Excluir"
    cancelText="Cancelar"
    variant="danger"
    [loading]="isDeleting"></app-confirmation-modal>
</div>
