// src/pages/register/contracts/ContractForm.tsx
import { useState, useEffect } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, Save, X, FileText, Calendar, DollarSign, Calculator } from 'lucide-react'
import { Button } from '@/components/ui/button/button'
import { Input } from '@/components/ui/input/input'
import { Label } from '@/components/ui/label/label'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/data-table/table'

interface ContratoFormData {
  evento: string
  cliente: string
  valorTotal: string
  parcelas: string
  primeiroVencimento: string
  periodicidade: 'Mensal' | 'Bimestral' | 'Trimestral'
  comissaoPercentual: string
  observacoes: string
}

interface Parcela {
  numero: number
  dataVencimento: string
  valor: number
  status: 'A vencer' | 'Pago' | 'Atrasado'
}

export default function ContractForm() {
  const navigate = useNavigate()
  const { id } = useParams()
  const isEditing = Boolean(id)

  const [formData, setFormData] = useState<ContratoFormData>({
    evento: '',
    cliente: '',
    valorTotal: '',
    parcelas: '',
    primeiroVencimento: '',
    periodicidade: 'Mensal',
    comissaoPercentual: '',
    observacoes: ''
  })

  const [errors, setErrors] = useState<Partial<ContratoFormData>>({})
  const [parcelasPreview, setParcelasPreview] = useState<Parcela[]>([])

  // Mock data para selects - substituir por dados reais da API
  const mockEventos = [
    { id: 1, nome: 'Casamento João & Maria', cliente: 'João Silva' },
    { id: 2, nome: 'Aniversário Pedro', cliente: 'Pedro Oliveira' },
    { id: 3, nome: 'Formatura Ana', cliente: 'Ana Santos' }
  ]

  const handleInputChange = (field: keyof ContratoFormData, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }))
    // Limpar erro do campo quando usuário começar a digitar
    if (errors[field]) {
      setErrors(prev => ({ ...prev, [field]: undefined }))
    }
  }

  const calculateParcelas = () => {
    if (!formData.valorTotal || !formData.parcelas || !formData.primeiroVencimento) {
      setParcelasPreview([])
      return
    }

    const valorTotal = parseFloat(formData.valorTotal.replace(',', '.'))
    const numeroParcelas = parseInt(formData.parcelas)
    const primeiroVencimento = new Date(formData.primeiroVencimento)

    if (isNaN(valorTotal) || isNaN(numeroParcelas) || valorTotal <= 0 || numeroParcelas <= 0) {
      setParcelasPreview([])
      return
    }

    const valorParcela = valorTotal / numeroParcelas
    const parcelas: Parcela[] = []

    for (let i = 0; i < numeroParcelas; i++) {
      const dataVencimento = new Date(primeiroVencimento)
      
      // Calcular data baseada na periodicidade
      switch (formData.periodicidade) {
        case 'Mensal':
          dataVencimento.setMonth(dataVencimento.getMonth() + i)
          break
        case 'Bimestral':
          dataVencimento.setMonth(dataVencimento.getMonth() + (i * 2))
          break
        case 'Trimestral':
          dataVencimento.setMonth(dataVencimento.getMonth() + (i * 3))
          break
      }

      parcelas.push({
        numero: i + 1,
        dataVencimento: dataVencimento.toISOString().split('T')[0],
        valor: valorParcela,
        status: 'A vencer'
      })
    }

    setParcelasPreview(parcelas)
  }

  const calculateComissao = () => {
    if (!formData.valorTotal || !formData.comissaoPercentual) {
      return 0
    }

    const valorTotal = parseFloat(formData.valorTotal.replace(',', '.'))
    const percentualComissao = parseFloat(formData.comissaoPercentual.replace(',', '.'))

    if (isNaN(valorTotal) || isNaN(percentualComissao)) {
      return 0
    }

    return (valorTotal * percentualComissao) / 100
  }

  useEffect(() => {
    calculateParcelas()
  }, [formData.valorTotal, formData.parcelas, formData.primeiroVencimento, formData.periodicidade])

  const validateForm = (): boolean => {
    const newErrors: Partial<ContratoFormData> = {}

    if (!formData.evento.trim()) {
      newErrors.evento = 'Evento é obrigatório'
    }

    if (!formData.cliente.trim()) {
      newErrors.cliente = 'Cliente é obrigatório'
    }

    if (!formData.valorTotal.trim()) {
      newErrors.valorTotal = 'Valor total é obrigatório'
    } else if (isNaN(parseFloat(formData.valorTotal.replace(',', '.'))) || parseFloat(formData.valorTotal.replace(',', '.')) <= 0) {
      newErrors.valorTotal = 'Valor total deve ser um número válido maior que zero'
    }

    if (!formData.parcelas.trim()) {
      newErrors.parcelas = 'Número de parcelas é obrigatório'
    } else if (isNaN(parseInt(formData.parcelas)) || parseInt(formData.parcelas) <= 0) {
      newErrors.parcelas = 'Número de parcelas deve ser um número válido maior que zero'
    }

    if (!formData.primeiroVencimento.trim()) {
      newErrors.primeiroVencimento = 'Primeiro vencimento é obrigatório'
    }

    if (!formData.comissaoPercentual.trim()) {
      newErrors.comissaoPercentual = 'Percentual de comissão é obrigatório'
    } else if (isNaN(parseFloat(formData.comissaoPercentual.replace(',', '.'))) || parseFloat(formData.comissaoPercentual.replace(',', '.')) < 0) {
      newErrors.comissaoPercentual = 'Percentual de comissão deve ser um número válido'
    }

    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!validateForm()) {
      return
    }

    // Implementar lógica de salvamento
    console.log('Salvando contrato:', formData)
    console.log('Parcelas:', parcelasPreview)
    console.log('Comissão total:', calculateComissao())
    
    // Simular salvamento
    setTimeout(() => {
      navigate('/cadastros/contratos')
    }, 1000)
  }

  const handleCancel = () => {
    navigate('/cadastros/contratos')
  }

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('pt-BR', {
      style: 'currency',
      currency: 'BRL'
    }).format(value)
  }

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('pt-BR')
  }

  return (
    <div className='space-y-6'>
      {/* Header */}
      <div className='flex items-center space-x-4'>
        <Button variant='ghost' size='sm' onClick={handleCancel}>
          <ArrowLeft className='h-4 w-4 mr-2' />
          Voltar
        </Button>
        <div>
          <h1 className='text-3xl font-bold tracking-tight'>
            {isEditing ? 'Editar Contrato' : 'Novo Contrato'}
          </h1>
          <p className='text-muted-foreground'>
            {isEditing 
              ? 'Atualize as informações do contrato' 
              : 'Preencha os dados do novo contrato'
            }
          </p>
        </div>
      </div>

      <div className='grid grid-cols-1 lg:grid-cols-2 gap-6'>
        {/* Formulário */}
        <form onSubmit={handleSubmit} className='space-y-6'>
          <div className='space-y-4'>
            <h3 className='text-lg font-semibold flex items-center space-x-2'>
              <FileText className='h-5 w-5' />
              <span>Dados do Contrato</span>
            </h3>

            <div className='grid grid-cols-1 md:grid-cols-2 gap-4'>
              {/* Evento */}
              <div className='space-y-2'>
                <Label htmlFor='evento'>Evento *</Label>
                <select
                  id='evento'
                  value={formData.evento}
                  onChange={(e) => {
                    const eventoSelecionado = mockEventos.find(evento => evento.nome === e.target.value)
                    handleInputChange('evento', e.target.value)
                    if (eventoSelecionado) {
                      handleInputChange('cliente', eventoSelecionado.cliente)
                    }
                  }}
                  className={`flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 ${errors.evento ? 'border-red-500' : ''}`}
                >
                  <option value=''>Selecione um evento</option>
                  {mockEventos.map((evento) => (
                    <option key={evento.id} value={evento.nome}>
                      {evento.nome}
                    </option>
                  ))}
                </select>
                {errors.evento && (
                  <p className='text-sm text-red-500'>{errors.evento}</p>
                )}
              </div>

              {/* Cliente */}
              <div className='space-y-2'>
                <Label htmlFor='cliente'>Cliente *</Label>
                <Input
                  id='cliente'
                  value={formData.cliente}
                  onChange={(e) => handleInputChange('cliente', e.target.value)}
                  placeholder='Nome do cliente'
                  className={errors.cliente ? 'border-red-500' : ''}
                />
                {errors.cliente && (
                  <p className='text-sm text-red-500'>{errors.cliente}</p>
                )}
              </div>

              {/* Valor Total */}
              <div className='space-y-2'>
                <Label htmlFor='valorTotal'>Valor Total *</Label>
                <Input
                  id='valorTotal'
                  value={formData.valorTotal}
                  onChange={(e) => handleInputChange('valorTotal', e.target.value)}
                  placeholder='0,00'
                  className={errors.valorTotal ? 'border-red-500' : ''}
                />
                {errors.valorTotal && (
                  <p className='text-sm text-red-500'>{errors.valorTotal}</p>
                )}
              </div>

              {/* Parcelas */}
              <div className='space-y-2'>
                <Label htmlFor='parcelas'>Número de Parcelas *</Label>
                <Input
                  id='parcelas'
                  type='number'
                  value={formData.parcelas}
                  onChange={(e) => handleInputChange('parcelas', e.target.value)}
                  placeholder='Ex: 5'
                  min='1'
                  className={errors.parcelas ? 'border-red-500' : ''}
                />
                {errors.parcelas && (
                  <p className='text-sm text-red-500'>{errors.parcelas}</p>
                )}
              </div>

              {/* Primeiro Vencimento */}
              <div className='space-y-2'>
                <Label htmlFor='primeiroVencimento'>Primeiro Vencimento *</Label>
                <Input
                  id='primeiroVencimento'
                  type='date'
                  value={formData.primeiroVencimento}
                  onChange={(e) => handleInputChange('primeiroVencimento', e.target.value)}
                  className={errors.primeiroVencimento ? 'border-red-500' : ''}
                />
                {errors.primeiroVencimento && (
                  <p className='text-sm text-red-500'>{errors.primeiroVencimento}</p>
                )}
              </div>

              {/* Periodicidade */}
              <div className='space-y-2'>
                <Label htmlFor='periodicidade'>Periodicidade *</Label>
                <select
                  id='periodicidade'
                  value={formData.periodicidade}
                  onChange={(e) => handleInputChange('periodicidade', e.target.value as 'Mensal' | 'Bimestral' | 'Trimestral')}
                  className='flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50'
                >
                  <option value='Mensal'>Mensal</option>
                  <option value='Bimestral'>Bimestral</option>
                  <option value='Trimestral'>Trimestral</option>
                </select>
              </div>

              {/* Comissão */}
              <div className='space-y-2'>
                <Label htmlFor='comissaoPercentual'>Comissão (%) *</Label>
                <Input
                  id='comissaoPercentual'
                  value={formData.comissaoPercentual}
                  onChange={(e) => handleInputChange('comissaoPercentual', e.target.value)}
                  placeholder='Ex: 10'
                  className={errors.comissaoPercentual ? 'border-red-500' : ''}
                />
                {errors.comissaoPercentual && (
                  <p className='text-sm text-red-500'>{errors.comissaoPercentual}</p>
                )}
                {formData.comissaoPercentual && !errors.comissaoPercentual && (
                  <p className='text-sm text-green-600 font-medium'>
                    Total da comissão: {formatCurrency(calculateComissao())}
                  </p>
                )}
              </div>
            </div>

            {/* Observações */}
            <div className='space-y-2'>
              <Label htmlFor='observacoes'>Observações</Label>
              <textarea
                id='observacoes'
                value={formData.observacoes}
                onChange={(e) => handleInputChange('observacoes', e.target.value)}
                placeholder='Informações adicionais sobre o contrato'
                className='flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50'
                rows={3}
              />
            </div>
          </div>

          {/* Botões */}
          <div className='flex items-center justify-end space-x-2 pt-6 border-t'>
            <Button type='button' variant='outline' onClick={handleCancel}>
              <X className='h-4 w-4 mr-2' />
              Cancelar
            </Button>
            <Button type='submit' variant='outline'>
              <Save className='h-4 w-4 mr-2' />
              {isEditing ? 'Atualizar' : 'Salvar'}
            </Button>
          </div>
        </form>

        {/* Preview das Parcelas */}
        <div className='space-y-4'>
          <h3 className='text-lg font-semibold flex items-center space-x-2'>
            <Calculator className='h-5 w-5' />
            <span>Preview das Parcelas</span>
          </h3>

          {parcelasPreview.length > 0 ? (
            <div className='space-y-4'>
              <div className='bg-blue-50 p-4 rounded-lg'>
                <div className='flex items-center justify-between'>
                  <span className='font-medium'>Valor por parcela:</span>
                  <span className='font-bold text-blue-600'>
                    {formatCurrency(parcelasPreview[0]?.valor || 0)}
                  </span>
                </div>
                <div className='flex items-center justify-between mt-2'>
                  <span className='font-medium'>Total de parcelas:</span>
                  <span className='font-bold'>{parcelasPreview.length}</span>
                </div>
              </div>

              <div className='max-h-96 overflow-y-auto border rounded-lg'>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Parcela</TableHead>
                      <TableHead>Vencimento</TableHead>
                      <TableHead>Valor</TableHead>
                      <TableHead>Status</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {parcelasPreview.map((parcela) => (
                      <TableRow key={parcela.numero}>
                        <TableCell className='font-medium'>{parcela.numero}</TableCell>
                        <TableCell>
                          <div className='flex items-center space-x-2'>
                            <Calendar className='h-4 w-4 text-muted-foreground' />
                            <span>{formatDate(parcela.dataVencimento)}</span>
                          </div>
                        </TableCell>
                        <TableCell className='font-medium'>
                          <div className='flex items-center space-x-2'>
                            <DollarSign className='h-4 w-4 text-muted-foreground' />
                            <span>{formatCurrency(parcela.valor)}</span>
                          </div>
                        </TableCell>
                        <TableCell>
                          <span className='inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium bg-yellow-100 text-yellow-800'>
                            {parcela.status}
                          </span>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            </div>
          ) : (
            <div className='text-center py-8 text-muted-foreground'>
              <Calculator className='h-12 w-12 mx-auto mb-4 opacity-50' />
              <p>Preencha os dados do contrato para visualizar as parcelas</p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// src/app/features/register/contracts/contract-form/contract-form.component.ts
import { Component, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { Router, ActivatedRoute } from '@angular/router'
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms'
import { LucideAngularModule, ArrowLeft, Save, X, FileText } from 'lucide-angular'
import { firstValueFrom } from 'rxjs'

import { ButtonComponent } from '@shared/components/ui/button/button.component'
import { LabelComponent } from '@shared/components/ui/label/label.component'
import { ContractService } from '@core/services/contract.service'
import { EventService } from '@core/services/event.service'
import { ClientService } from '@core/services/client.service'
import { SellerService } from '@core/services/seller.service'
import type { Event, Client, Seller, CreateContractRequest, UpdateContractRequest } from '@shared/models/api.types'

@Component({
  selector: 'app-contract-form',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    LucideAngularModule,
    ButtonComponent,
    LabelComponent
  ],
  templateUrl: './contract-form.component.html'
})
export class ContractFormComponent implements OnInit {
  readonly ArrowLeftIcon = ArrowLeft
  readonly SaveIcon = Save
  readonly XIcon = X
  readonly FileTextIcon = FileText

  contractForm!: FormGroup
  events: Event[] = []
  clients: Client[] = []
  sellers: Seller[] = []
  isEditing: boolean = false
  contractId: string | null = null
  isLoading: boolean = false
  isLoadingData: boolean = true
  errorMessage: string = ''
  fixedCommissionAmount: number = 0 // Valor fixo da comissão quando em edição

  constructor(
    private fb: FormBuilder,
    private contractService: ContractService,
    private eventService: EventService,
    private clientService: ClientService,
    private sellerService: SellerService,
    private router: Router,
    private route: ActivatedRoute
  ) {
    this.contractForm = this.fb.group({
      eventId: ['', [Validators.required]],
      clientId: ['', [Validators.required]],
      sellerId: [''],
      totalAmount: ['', [Validators.required, Validators.min(0)]],
      installmentCount: ['', [Validators.required, Validators.min(1)]],
      firstDueDate: ['', [Validators.required]],
      periodicity: ['Mensal'],
      commissionPercentage: ['', [Validators.required, Validators.min(0), Validators.max(100)]],
      notes: [''],
      status: ['Pendente'],
      signedAt: ['']
    })
  }

  async ngOnInit(): Promise<void> {
    this.contractId = this.route.snapshot.paramMap.get('id')
    this.isEditing = !!this.contractId

    await this.loadData()

    if (this.isEditing && this.contractId) {
      await this.loadContract(this.contractId)
    }
    
    this.isLoadingData = false
  }

  /**
   * @Function - loadData
   * @description - Loads events, clients and sellers data for the form
   * @author - Vitor Hugo
   * @returns - Promise<void>
   */
  async loadData(): Promise<void> {
    try {
      const [eventsResponse, clientsResponse, sellersResponse] = await Promise.all([
        firstValueFrom(this.eventService.getEvents()),
        firstValueFrom(this.clientService.getClients()),
        firstValueFrom(this.sellerService.getSellers())
      ])

      if (eventsResponse.success && eventsResponse.data) {
        this.events = eventsResponse.data
      }

      if (clientsResponse.success && clientsResponse.data) {
        this.clients = clientsResponse.data as Client[]
      }

      if (sellersResponse.success && sellersResponse.data) {
        this.sellers = Array.isArray(sellersResponse.data) 
          ? sellersResponse.data 
          : (sellersResponse.data as any).data || []
      }
    } catch (err: any) {
      this.errorMessage = err.message || 'Erro ao carregar dados'
    }
  }

  /**
   * @Function - loadContract
   * @description - Loads contract data for editing
   * @author - Vitor Hugo
   * @param - id: string - Contract ID
   * @returns - Promise<void>
   */
  async loadContract(id: string): Promise<void> {
    try {
      const response = await firstValueFrom(this.contractService.getContractById(id))
      if (response.success && response.data) {
        const contract = response.data
        // Armazena o valor fixo da comissão
        this.fixedCommissionAmount = contract.commissionAmount || 0
        this.contractForm.patchValue({
          eventId: contract.eventId,
          clientId: contract.clientId,
          sellerId: contract.sellerId || '',
          totalAmount: contract.totalAmount,
          installmentCount: contract.installmentCount,
          firstDueDate: contract.firstDueDate.split('T')[0],
          periodicity: contract.periodicity,
          commissionPercentage: contract.commissionPercentage,
          notes: contract.notes || '',
          status: contract.status,
          signedAt: contract.signedAt || ''
        })
        // Desabilita o campo de comissão no modo edição
        if (this.isEditing) {
          this.contractForm.get('commissionPercentage')?.disable()
        }
      }
    } catch (error: any) {
      this.errorMessage = error.message || 'Erro ao carregar contrato'
    }
  }

  async handleSubmit(): Promise<void> {
    if (this.contractForm.invalid) {
      Object.keys(this.contractForm.controls).forEach(key => {
        this.contractForm.controls[key].markAsTouched()
      })
      return
    }

    this.isLoading = true
    this.errorMessage = ''

    try {
      const formValue = this.contractForm.value
      
      if (this.isEditing && this.contractId) {
        const updateData: UpdateContractRequest = {
          status: formValue.status,
          ...(formValue.status === 'Assinado' && formValue.signedAt && { signedAt: formValue.signedAt }),
          ...(formValue.sellerId ? { sellerId: formValue.sellerId } : { sellerId: null })
        }
        
        const response = await firstValueFrom(
          this.contractService.updateContract(this.contractId, updateData)
        )
        
        if (response.success) {
          this.router.navigate(['/cadastros/contratos'])
        } else {
          this.errorMessage = 'Erro ao atualizar contrato'
        }
      } else {
        const createData: CreateContractRequest = {
          eventId: formValue.eventId,
          clientId: formValue.clientId,
          totalAmount: parseFloat(formValue.totalAmount),
          installmentCount: parseInt(formValue.installmentCount),
          firstDueDate: formValue.firstDueDate,
          periodicity: formValue.periodicity,
          commissionPercentage: parseFloat(formValue.commissionPercentage),
          notes: formValue.notes || undefined,
          ...(formValue.sellerId ? { sellerId: formValue.sellerId } : {})
        }
        
        const response = await firstValueFrom(
          this.contractService.createContract(createData)
        )
        
        if (response.success) {
          this.router.navigate(['/cadastros/contratos'])
        } else {
          this.errorMessage = 'Erro ao criar contrato'
        }
      }
    } catch (error: any) {
      this.errorMessage = error.message || 'Erro ao salvar contrato'
    } finally {
      this.isLoading = false
    }
  }

  handleCancel(): void {
    this.router.navigate(['/cadastros/contratos'])
  }

  hasError(fieldName: string): boolean {
    const field = this.contractForm.get(fieldName)
    return !!(field?.invalid && field.touched)
  }

  getFieldError(fieldName: string): string {
    const field = this.contractForm.get(fieldName)
    if (field?.hasError('required') && field.touched) {
      return 'Campo obrigatório'
    }
    if (field?.hasError('min') && field.touched) {
      return 'Valor mínimo não atendido'
    }
    if (field?.hasError('max') && field.touched) {
      return 'Valor máximo excedido'
    }
    return ''
  }

  get installmentAmount(): number {
    const total = this.contractForm.get('totalAmount')?.value
    const count = this.contractForm.get('installmentCount')?.value
    return (total && count) ? parseFloat(total) / parseInt(count) : 0
  }

  get commissionAmount(): number {
    // Se estiver editando, retorna o valor fixo da comissão
    if (this.isEditing && this.fixedCommissionAmount > 0) {
      return this.fixedCommissionAmount
    }
    // Caso contrário, calcula baseado no formulário (criação)
    const total = this.contractForm.get('totalAmount')?.value
    const percentage = this.contractForm.get('commissionPercentage')?.value
    return (total && percentage) ? parseFloat(total) * parseFloat(percentage) / 100 : 0
  }

  formatCurrency(value: number): string {
    return new Intl.NumberFormat('pt-BR', {
      style: 'currency',
      currency: 'BRL'
    }).format(value)
  }

  get showSignedAtField(): boolean {
    return this.contractForm.get('status')?.value === 'Assinado'
  }
}


<div class="space-y-6">
  <!-- Header -->
  <div class="flex items-center space-x-4">
    <button appButton variant="ghost" size="sm" (click)="handleCancel()">
      <lucide-icon [img]="ArrowLeftIcon" class="h-4 w-4 mr-2"></lucide-icon>
      Voltar
    </button>
    <div>
      <h1 class="text-3xl font-bold tracking-tight">
        {{ isEditing ? 'Editar Contrato' : 'Novo Contrato' }}
      </h1>
      <p class="text-muted-foreground">
        {{ isEditing ? 'Atualize as informações do contrato' : 'Preencha os dados do novo contrato' }}
      </p>
    </div>
  </div>

  <!-- Error Message -->
  @if (errorMessage) {
    <div class="w-full p-3 text-sm text-red-600 bg-red-50 border border-red-200 rounded-md">
      {{ errorMessage }}
    </div>
  }

  <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
    <!-- Formulário -->
    @if (!isLoadingData) {
      <form [formGroup]="contractForm" (ngSubmit)="handleSubmit()" class="space-y-6">
        <div class="space-y-4">
          <h3 class="text-lg font-semibold flex items-center space-x-2">
            <lucide-icon [img]="FileTextIcon" class="h-5 w-5"></lucide-icon>
            <span>Dados do Contrato</span>
          </h3>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <!-- Evento -->
            <div class="space-y-2">
              <label appLabel htmlFor="eventId">Evento *</label>
              <select
                id="eventId"
                formControlName="eventId"
                [disabled]="isLoadingData"
                [class]="'flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 ' + (hasError('eventId') ? 'border-red-500' : '')"
              >
                <option value="">{{ isLoadingData ? 'Carregando eventos...' : 'Selecione um evento' }}</option>
                @for (event of events; track event.id) {
                  <option [value]="event.id">{{ event.name }}</option>
                }
              </select>
              @if (hasError('eventId')) {
                <p class="text-sm text-red-500">{{ getFieldError('eventId') }}</p>
              }
            </div>

            <!-- Cliente -->
            <div class="space-y-2">
              <label appLabel htmlFor="clientId">Cliente *</label>
              <select
                id="clientId"
                formControlName="clientId"
                [disabled]="isLoadingData"
                [class]="'flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 ' + (hasError('clientId') ? 'border-red-500' : '')"
              >
                <option value="">{{ isLoadingData ? 'Carregando clientes...' : 'Selecione um cliente' }}</option>
                @for (client of clients; track client.id) {
                  <option [value]="client.id">{{ client.name }}</option>
                }
              </select>
              @if (hasError('clientId')) {
                <p class="text-sm text-red-500">{{ getFieldError('clientId') }}</p>
              }
            </div>

            <!-- Vendedor -->
            <div class="space-y-2">
              <label appLabel htmlFor="sellerId">Vendedor(a)</label>
              <select
                id="sellerId"
                formControlName="sellerId"
                [disabled]="isLoadingData"
                class="flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
              >
                <option value="">{{ isLoadingData ? 'Carregando vendedores...' : 'Selecione um vendedor (opcional)' }}</option>
                @for (seller of sellers; track seller.id) {
                  <option [value]="seller.id">{{ seller.name }}</option>
                }
              </select>
            </div>

            <!-- Valor Total -->
            <div class="space-y-2">
              <label appLabel htmlFor="totalAmount">Valor Total *</label>
              <input
                type="number"
                step="0.01"
                min="0"
                id="totalAmount"
                formControlName="totalAmount"
                placeholder="0.00"
                [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('totalAmount') ? 'border-red-500' : '')"
              />
              @if (hasError('totalAmount')) {
                <p class="text-sm text-red-500">{{ getFieldError('totalAmount') }}</p>
              }
            </div>

            <!-- Número de Parcelas -->
            <div class="space-y-2">
              <label appLabel htmlFor="installmentCount">Número de Parcelas *</label>
              <input
                type="number"
                min="1"
                id="installmentCount"
                formControlName="installmentCount"
                placeholder="1"
                [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('installmentCount') ? 'border-red-500' : '')"
              />
              @if (hasError('installmentCount')) {
                <p class="text-sm text-red-500">{{ getFieldError('installmentCount') }}</p>
              }
            </div>

            <!-- Data da Primeira Parcela -->
            <div class="space-y-2">
              <label appLabel htmlFor="firstDueDate">Data da Primeira Parcela *</label>
              <input
                type="date"
                id="firstDueDate"
                formControlName="firstDueDate"
                [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('firstDueDate') ? 'border-red-500' : '')"
              />
              @if (hasError('firstDueDate')) {
                <p class="text-sm text-red-500">{{ getFieldError('firstDueDate') }}</p>
              }
            </div>

            <!-- Periodicidade -->
            <div class="space-y-2">
              <label appLabel htmlFor="periodicity">Periodicidade *</label>
              <select
                id="periodicity"
                formControlName="periodicity"
                class="flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
              >
                <option value="Mensal">Mensal</option>
                <option value="Bimestral">Bimestral</option>
                <option value="Trimestral">Trimestral</option>
                <option value="Semestral">Semestral</option>
                <option value="Anual">Anual</option>
              </select>
            </div>

            <!-- Percentual de Comissão -->
            <div class="space-y-2">
              <label appLabel htmlFor="commissionPercentage">
                Percentual de Comissão (%) *
                @if (isEditing) {
                  <span class="text-xs text-muted-foreground ml-2" title="Comissão fixada na criação do contrato e não pode ser alterada">
                    (Somente leitura)
                  </span>
                }
              </label>
              <input
                type="number"
                step="0.01"
                min="0"
                max="100"
                id="commissionPercentage"
                formControlName="commissionPercentage"
                placeholder="0.00"
                [disabled]="isEditing"
                [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('commissionPercentage') ? 'border-red-500' : '')"
              />
              @if (isEditing) {
                <p class="text-xs text-amber-600 bg-amber-50 border border-amber-200 rounded-md p-2">
                  ℹ️ A comissão foi fixada na criação do contrato e não pode ser alterada. O valor da comissão permanece baseado no valor inicial do contrato.
                </p>
              }
              @if (hasError('commissionPercentage')) {
                <p class="text-sm text-red-500">{{ getFieldError('commissionPercentage') }}</p>
              }
            </div>

            <!-- Observações -->
            <div class="space-y-2 md:col-span-2">
              <label appLabel htmlFor="notes">Observações</label>
              <textarea
                id="notes"
                formControlName="notes"
                placeholder="Observações adicionais sobre o contrato..."
                class="flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                rows="3"
              ></textarea>
            </div>

            <!-- Status -->
            <div class="space-y-2">
              <label appLabel htmlFor="status">Status *</label>
              <select
                id="status"
                formControlName="status"
                class="flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
              >
                <option value="Pendente">Pendente</option>
                <option value="Assinado">Assinado</option>
                <option value="Cancelado">Cancelado</option>
              </select>
            </div>

            <!-- Data de Assinatura (condicional) -->
            @if (showSignedAtField) {
              <div class="space-y-2">
                <label appLabel htmlFor="signedAt">Data de Assinatura *</label>
                <input
                  type="date"
                  id="signedAt"
                  formControlName="signedAt"
                  [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('signedAt') ? 'border-red-500' : '')"
                />
                @if (hasError('signedAt')) {
                  <p class="text-sm text-red-500">{{ getFieldError('signedAt') }}</p>
                }
              </div>
            }
          </div>
        </div>

        <!-- Botões -->
        <div class="flex items-center justify-end space-x-2 pt-6 border-t">
          <button appButton type="button" variant="outline" (click)="handleCancel()" [disabled]="isLoading">
            <lucide-icon [img]="XIcon" class="h-4 w-4 mr-2"></lucide-icon>
            Cancelar
          </button>
          <button appButton type="submit" variant="outline" [disabled]="isLoading">
            <lucide-icon [img]="SaveIcon" class="h-4 w-4 mr-2"></lucide-icon>
            {{ isLoading ? 'Salvando...' : (isEditing ? 'Atualizar' : 'Salvar') }}
          </button>
        </div>
      </form>
    }

    <!-- Resumo do Contrato -->
    <div class="space-y-4">
      <h3 class="text-lg font-semibold flex items-center space-x-2">
        <lucide-icon [img]="FileTextIcon" class="h-5 w-5"></lucide-icon>
        <span>Resumo do Contrato</span>
      </h3>

      <div class="bg-blue-50 p-4 rounded-lg space-y-3">
        <div class="grid grid-cols-2 gap-4 text-sm">
          <div>
            <span class="font-medium text-blue-900">Valor por Parcela:</span>
            <p class="text-lg font-bold text-blue-700">
              {{ installmentAmount > 0 ? formatCurrency(installmentAmount) : 'R$ 0,00' }}
            </p>
          </div>
          <div>
            <span class="font-medium text-blue-900">Comissão Total:</span>
            <p class="text-lg font-bold text-blue-700">
              {{ commissionAmount > 0 ? formatCurrency(commissionAmount) : 'R$ 0,00' }}
            </p>
            @if (isEditing) {
              <p class="text-xs text-amber-600 mt-1">Valor fixo da criação</p>
            }
          </div>
        </div>
        
        <div class="pt-2 border-t border-blue-200">
          <p class="text-sm text-blue-800 mb-2">
            <strong>Valor Total:</strong> {{ contractForm.get('totalAmount')?.value ? formatCurrency(contractForm.get('totalAmount')?.value) : 'R$ 0,00' }}
          </p>
          <p class="text-sm text-blue-800 mb-2">
            <strong>Parcelas:</strong> {{ contractForm.get('installmentCount')?.value || '0' }} x {{ contractForm.get('periodicity')?.value }}
          </p>
          <p class="text-sm text-blue-800">
            <strong>Comissão:</strong> {{ contractForm.get('commissionPercentage')?.value || '0' }}%
          </p>
        </div>
      </div>

      <div class="bg-green-50 p-4 rounded-lg">
        <p class="text-sm text-green-800 mb-2">
          <strong>✨ Criação Automática de Parcelas</strong>
        </p>
        <p class="text-sm text-green-700">
          O sistema criará automaticamente todas as parcelas baseadas na periodicidade escolhida. 
          Você poderá gerenciar as parcelas na seção Financeiro após a criação do contrato.
        </p>
      </div>
    </div>
  </div>
</div>
