// src/pages/register/clients/ClientForm.tsx
import { useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, Save, X } from 'lucide-react'
import { Button } from '@/components/ui/button/button'
import { Input } from '@/components/ui/input/input'
import { Label } from '@/components/ui/label/label'

interface ClientFormData {
  name: string
  email: string
  telefone: string
  endereco: string
  observacoes: string
}

export default function ClientForm() {
  const navigate = useNavigate()
  const { id } = useParams()
  const isEditing = Boolean(id)

  const [formData, setFormData] = useState<ClientFormData>({
    name: '',
    email: '',
    telefone: '',
    endereco: '',
    observacoes: ''
  })

  const [errors, setErrors] = useState<Partial<ClientFormData>>({})

  const handleInputChange = (field: keyof ClientFormData, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }))
    // Limpar erro do campo quando usuário começar a digitar
    if (errors[field]) {
      setErrors(prev => ({ ...prev, [field]: undefined }))
    }
  }

  const validateForm = (): boolean => {
    const newErrors: Partial<ClientFormData> = {}

    if (!formData.name.trim()) {
      newErrors.name = 'Nome é obrigatório'
    }

    if (!formData.email.trim()) {
      newErrors.email = 'Email é obrigatório'
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = 'Email inválido'
    }

    if (!formData.telefone.trim()) {
      newErrors.telefone = 'Telefone é obrigatório'
    }

    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!validateForm()) {
      return
    }

    // Implementar lógica de salvamento
    console.log('Salvando cliente:', formData)
    
    // Simular salvamento
    setTimeout(() => {
      navigate('/cadastros/clientes')
    }, 1000)
  }

  const handleCancel = () => {
    navigate('/cadastros/clientes')
  }

  return (
    <div className='space-y-6'>
      {/* Header */}
      <div className='flex items-center space-x-4'>
        <Button variant='ghost' size='sm' onClick={handleCancel}>
          <ArrowLeft className='h-4 w-4 mr-2' />
          Voltar
        </Button>
        <div>
          <h1 className='text-3xl font-bold tracking-tight'>
            {isEditing ? 'Editar Cliente' : 'Novo Cliente'}
          </h1>
          <p className='text-muted-foreground'>
            {isEditing 
              ? 'Atualize as informações do cliente' 
              : 'Preencha os dados do novo cliente'
            }
          </p>
        </div>
      </div>

      {/* Formulário */}
      <form onSubmit={handleSubmit} className='space-y-6'>
        <div className='grid grid-cols-1 md:grid-cols-2 gap-6'>
          {/* Nome */}
          <div className='space-y-2'>
            <Label htmlFor='name'>Nome *</Label>
            <Input
              id='name'
              value={formData.name}
              onChange={(e) => handleInputChange('name', e.target.value)}
              placeholder='Nome completo do cliente'
              className={errors.name ? 'border-red-500' : ''}
            />
            {errors.name && (
              <p className='text-sm text-red-500'>{errors.name}</p>
            )}
          </div>

          {/* Email */}
          <div className='space-y-2'>
            <Label htmlFor='email'>Email *</Label>
            <Input
              id='email'
              type='email'
              value={formData.email}
              onChange={(e) => handleInputChange('email', e.target.value)}
              placeholder='email@exemplo.com'
              className={errors.email ? 'border-red-500' : ''}
            />
            {errors.email && (
              <p className='text-sm text-red-500'>{errors.email}</p>
            )}
          </div>

          {/* Telefone */}
          <div className='space-y-2'>
            <Label htmlFor='telefone'>Telefone *</Label>
            <Input
              id='telefone'
              value={formData.telefone}
              onChange={(e) => handleInputChange('telefone', e.target.value)}
              placeholder='(11) 99999-9999'
              className={errors.telefone ? 'border-red-500' : ''}
            />
            {errors.telefone && (
              <p className='text-sm text-red-500'>{errors.telefone}</p>
            )}
          </div>

          {/* Endereço */}
          <div className='space-y-2'>
            <Label htmlFor='endereco'>Endereço</Label>
            <Input
              id='endereco'
              value={formData.endereco}
              onChange={(e) => handleInputChange('endereco', e.target.value)}
              placeholder='Endereço completo'
            />
          </div>
        </div>

        {/* Observações */}
        <div className='space-y-2'>
          <Label htmlFor='observacoes'>Observações</Label>
          <textarea
            id='observacoes'
            value={formData.observacoes}
            onChange={(e) => handleInputChange('observacoes', e.target.value)}
            placeholder='Informações adicionais sobre o cliente'
            className='flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50'
            rows={3}
          />
        </div>

        {/* Botões */}
        <div className='flex items-center justify-end space-x-2 pt-6 border-t'>
          <Button type='button' variant='outline' onClick={handleCancel}>
            <X className='h-4 w-4 mr-2' />
            Cancelar
          </Button>
          <Button variant='outline' type='submit'>
            <Save className='h-4 w-4 mr-2' />
            {isEditing ? 'Atualizar' : 'Salvar'}
          </Button>
        </div>
      </form>
    </div>
  )
}

// src/app/features/register/clients/client-form/client-form.component.ts
import { Component, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { Router, ActivatedRoute } from '@angular/router'
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms'
import { LucideAngularModule, ArrowLeft, Save, X } from 'lucide-angular'
import { firstValueFrom } from 'rxjs'

import { ButtonComponent } from '@shared/components/ui/button/button.component'
import { LabelComponent } from '@shared/components/ui/label/label.component'
import { PhoneMaskDirective } from '@shared/directives/phone-mask.directive'
import { phoneValidator } from '@shared/validators'
import { ClientService } from '@core/services/client.service'
import type { CreateClientRequest, UpdateClientRequest } from '@shared/models/api.types'

@Component({
  selector: 'app-client-form',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    LucideAngularModule,
    ButtonComponent,
    LabelComponent,
    PhoneMaskDirective
  ],
  templateUrl: './client-form.component.html'
})
export class ClientFormComponent implements OnInit {
  readonly ArrowLeftIcon = ArrowLeft
  readonly SaveIcon = Save
  readonly XIcon = X

  clientForm!: FormGroup
  isEditing: boolean = false
  clientId: string | null = null
  isLoading: boolean = false
  isLoadingData: boolean = false
  errorMessage: string = ''

  constructor(
    private fb: FormBuilder,
    private clientService: ClientService,
    private router: Router,
    private route: ActivatedRoute
  ) {
    this.clientForm = this.fb.group({
      name: ['', [Validators.required]],
      email: ['', [Validators.required, Validators.email]],
      phone: ['', [Validators.required, phoneValidator()]],
      address: ['']
    })
  }

  async ngOnInit(): Promise<void> {
    this.clientId = this.route.snapshot.paramMap.get('id')
    this.isEditing = !!this.clientId

    if (this.isEditing && this.clientId) {
      await this.loadClient(this.clientId)
    }
  }

  async loadClient(id: string): Promise<void> {
    try {
      this.isLoadingData = true
      const response = await firstValueFrom(this.clientService.getClientById(id))
      if (response.success && response.data) {
        const client = response.data
        this.clientForm.patchValue({
          name: client.name,
          email: client.email || '',
          phone: client.phone || '',
          address: client.address || ''
        })
      }
    } catch (error: any) {
      this.errorMessage = error.message || 'Erro ao carregar cliente'
    } finally {
      this.isLoadingData = false
    }
  }

  async handleSubmit(): Promise<void> {
    if (this.clientForm.invalid) {
      Object.keys(this.clientForm.controls).forEach(key => {
        this.clientForm.controls[key].markAsTouched()
      })
      return
    }

    this.isLoading = true
    this.errorMessage = ''

    try {
      const formValue = this.clientForm.value
      
      if (this.isEditing && this.clientId) {
        const updateData: UpdateClientRequest = {
          name: formValue.name,
          email: formValue.email || undefined,
          phone: formValue.phone || undefined,
          address: formValue.address || undefined
        }
        
        const response = await firstValueFrom(
          this.clientService.updateClient(this.clientId, updateData)
        )
        
        if (response.success) {
          this.router.navigate(['/cadastros/clientes'])
        } else {
          this.errorMessage = 'Erro ao atualizar cliente'
        }
      } else {
        const createData: CreateClientRequest = {
          name: formValue.name,
          email: formValue.email || undefined,
          phone: formValue.phone || undefined,
          address: formValue.address || undefined
        }
        
        const response = await firstValueFrom(
          this.clientService.createClient(createData)
        )
        
        if (response.success) {
          this.router.navigate(['/cadastros/clientes'])
        } else {
          this.errorMessage = 'Erro ao criar cliente'
        }
      }
    } catch (error: any) {
      this.errorMessage = error.message || 'Erro ao salvar cliente'
    } finally {
      this.isLoading = false
    }
  }

  handleCancel(): void {
    this.router.navigate(['/cadastros/clientes'])
  }

  getFieldError(fieldName: string): string {
    const field = this.clientForm.get(fieldName)
    if (field?.hasError('required') && field.touched) {
      const fieldLabels: Record<string, string> = {
        name: 'Nome',
        email: 'Email',
        phone: 'Telefone'
      }
      return `${fieldLabels[fieldName] || 'Campo'} é obrigatório`
    }
    if (field?.hasError('email') && field.touched) {
      return 'Email inválido'
    }
    if (field?.hasError('invalidPhone') && field.touched) {
      return 'Telefone inválido. Use o formato (XX) XXXXX-XXXX'
    }
    return ''
  }

  hasError(fieldName: string): boolean {
    const field = this.clientForm.get(fieldName)
    return !!(field?.invalid && field.touched)
  }
}


<div class="space-y-6">
  <!-- Header -->
  <div class="flex items-center space-x-4">
    <button appButton variant="ghost" size="sm" (click)="handleCancel()">
      <lucide-icon [img]="ArrowLeftIcon" class="h-4 w-4 mr-2"></lucide-icon>
      Voltar
    </button>
    <div>
      <h1 class="text-3xl font-bold tracking-tight">
        {{ isEditing ? 'Editar Cliente' : 'Novo Cliente' }}
      </h1>
      <p class="text-muted-foreground">
        {{ isEditing ? 'Atualize as informações do cliente' : 'Preencha os dados do novo cliente' }}
      </p>
    </div>
  </div>

  <!-- Loading State -->
  @if (isLoadingData) {
    <div class="text-center py-8">
      <p class="text-muted-foreground">Carregando dados do cliente...</p>
    </div>
  }

  <!-- Error Message -->
  @if (errorMessage) {
    <div class="w-full p-3 text-sm text-red-600 bg-red-50 border border-red-200 rounded-md">
      {{ errorMessage }}
    </div>
  }

  <!-- Formulário -->
  @if (!isLoadingData) {
    <form [formGroup]="clientForm" (ngSubmit)="handleSubmit()" class="space-y-6">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
      <!-- Nome -->
      <div class="space-y-2">
        <label appLabel htmlFor="name">Nome *</label>
        <input
          type="text"
          id="name"
          formControlName="name"
          placeholder="Nome completo do cliente"
          [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('name') ? 'border-red-500' : '')"
        />
        @if (hasError('name')) {
          <p class="text-sm text-red-500">{{ getFieldError('name') }}</p>
        }
      </div>

      <!-- Email -->
      <div class="space-y-2">
        <label appLabel htmlFor="email">Email *</label>
        <input
          type="email"
          id="email"
          formControlName="email"
          placeholder="email@exemplo.com"
          [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('email') ? 'border-red-500' : '')"
        />
        @if (hasError('email')) {
          <p class="text-sm text-red-500">{{ getFieldError('email') }}</p>
        }
      </div>

      <!-- Telefone -->
      <div class="space-y-2">
        <label appLabel htmlFor="phone">Telefone *</label>
        <input
          type="tel"
          id="phone"
          formControlName="phone"
          appPhoneMask
          placeholder="(11) 99999-9999"
          [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('phone') ? 'border-red-500' : '')"
        />
        @if (hasError('phone')) {
          <p class="text-sm text-red-500">{{ getFieldError('phone') }}</p>
        }
      </div>

      <!-- Endereço -->
      <div class="space-y-2 md:col-span-2">
        <label appLabel htmlFor="address">Endereço</label>
        <input
          type="text"
          id="address"
          formControlName="address"
          placeholder="Endereço completo"
          class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm"
        />
      </div>
    </div>

    <!-- Botões -->
    <div class="flex items-center justify-end space-x-2 pt-6 border-t">
      <button appButton type="button" variant="outline" (click)="handleCancel()">
        <lucide-icon [img]="XIcon" class="h-4 w-4 mr-2"></lucide-icon>
        Cancelar
      </button>
      <button appButton type="submit" variant="outline" [disabled]="isLoading">
        <lucide-icon [img]="SaveIcon" class="h-4 w-4 mr-2"></lucide-icon>
        {{ isLoading ? 'Salvando...' : (isEditing ? 'Atualizar' : 'Salvar') }}
      </button>
    </div>
    </form>
  }
</div>
