// src/pages/register/contracts/ContractsList.tsx
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Plus, Edit, Trash2, Eye, FileText, Calendar, DollarSign, User } from 'lucide-react'
import { Button } from '@/components/ui/button/button'
import SearchBar from '@/components/ui/search-bar/SearchBar'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from '@/components/ui/data-table/table'

// Mock data - substituir por dados reais da API
const mockContratos = [
  {
    id: 1,
    evento: 'Casamento João & Maria',
    cliente: 'João Silva',
    valorTotal: 5000.00,
    parcelas: 5,
    primeiroVencimento: '2025-10-15',
    periodicidade: 'Mensal',
    comissaoPercentual: 10,
    comissaoTotal: 500.00,
    status: 'Ativo',
    dataCadastro: '2025-10-15',
    parcelasPagas: 2,
    parcelasPendentes: 3
  },
  {
    id: 2,
    evento: 'Aniversário Pedro',
    cliente: 'Pedro Oliveira',
    valorTotal: 2500.00,
    parcelas: 3,
    primeiroVencimento: '2025-10-01',
    periodicidade: 'Mensal',
    comissaoPercentual: 8,
    comissaoTotal: 200.00,
    status: 'Ativo',
    dataCadastro: '2025-10-20',
    parcelasPagas: 1,
    parcelasPendentes: 2
  },
  {
    id: 3,
    evento: 'Formatura Ana',
    cliente: 'Ana Santos',
    valorTotal: 8000.00,
    parcelas: 8,
    primeiroVencimento: '2025-10-10',
    periodicidade: 'Mensal',
    comissaoPercentual: 12,
    comissaoTotal: 960.00,
    status: 'Finalizado',
    dataCadastro: '2025-11-25',
    parcelasPagas: 8,
    parcelasPendentes: 0
  }
]

export default function ContractsList() {
  const [contratos] = useState(mockContratos)
  const [searchTerm, setSearchTerm] = useState('')
  const [filterStatus, setFilterStatus] = useState('todos')

  const filteredContratos = contratos.filter(contrato => {
    const matchesSearch = contrato.evento.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         contrato.cliente.toLowerCase().includes(searchTerm.toLowerCase())
    const matchesStatus = filterStatus === 'todos' || contrato.status === filterStatus
    return matchesSearch && matchesStatus
  })

  const handleDelete = (id: number) => {
    // Implementar lógica de exclusão
    console.log('Excluir contrato:', id)
  }

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('pt-BR', {
      style: 'currency',
      currency: 'BRL'
    }).format(value)
  }

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('pt-BR')
  }

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'Ativo':
        return 'bg-green-100 text-green-800'
      case 'Finalizado':
        return 'bg-blue-100 text-blue-800'
      case 'Cancelado':
        return 'bg-red-100 text-red-800'
      default:
        return 'bg-gray-100 text-gray-800'
    }
  }

  const getProgressPercentage = (pagas: number, total: number) => {
    return total > 0 ? Math.round((pagas / total) * 100) : 0
  }

  return (
    <div className='space-y-6'>
      {/* Header */}
      <div className='flex items-center justify-between'>
        <div>
          <h1 className='text-3xl font-bold tracking-tight'>Contratos</h1>
          <p className='text-muted-foreground'>
            Gerencie os contratos e parcelamentos dos eventos
          </p>
        </div>
        <Button variant='outline' asChild>
          <Link to='/cadastros/contratos/novo'>
            <Plus className='mr-2 h-4 w-4' />
            Novo Contrato
          </Link>
        </Button>
      </div>

      {/* Filtros */}
      <div className='flex items-center space-x-2'>
        <div className='flex-1'>
          <SearchBar
            placeholder='Buscar por evento ou cliente...'
            value={searchTerm}
            onChange={setSearchTerm}
          />
        </div>
        <select
          value={filterStatus}
          onChange={(e) => setFilterStatus(e.target.value)}
          className='flex h-10 w-48 items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50'
        >
          <option value='todos'>Todos os status</option>
          <option value='Ativo'>Ativo</option>
          <option value='Finalizado'>Finalizado</option>
          <option value='Cancelado'>Cancelado</option>
        </select>
      </div>

      {/* Tabela */}
      <div className='rounded-md border'>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Evento</TableHead>
              <TableHead>Cliente</TableHead>
              <TableHead>Valor Total</TableHead>
              <TableHead>Parcelas</TableHead>
              <TableHead>1º Vencimento</TableHead>
              <TableHead>Comissão</TableHead>
              <TableHead>Progresso</TableHead>
              <TableHead>Status</TableHead>
              <TableHead className='text-right'>Ações</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filteredContratos.map((contrato) => (
              <TableRow key={contrato.id}>
                <TableCell className='font-medium'>
                  <div className='flex items-center space-x-2'>
                    <FileText className='h-4 w-4 text-muted-foreground' />
                    <span>{contrato.evento}</span>
                  </div>
                </TableCell>
                <TableCell>
                  <div className='flex items-center space-x-2'>
                    <User className='h-4 w-4 text-muted-foreground' />
                    <span>{contrato.cliente}</span>
                  </div>
                </TableCell>
                <TableCell className='font-medium'>{formatCurrency(contrato.valorTotal)}</TableCell>
                <TableCell>
                  <div className='flex items-center space-x-2'>
                    <Calendar className='h-4 w-4 text-muted-foreground' />
                    <span>{contrato.parcelas}x</span>
                  </div>
                </TableCell>
                <TableCell>{formatDate(contrato.primeiroVencimento)}</TableCell>
                <TableCell>
                  <div className='flex items-center space-x-2'>
                    <DollarSign className='h-4 w-4 text-muted-foreground' />
                    <div>
                      <div className='text-sm font-medium'>{formatCurrency(contrato.comissaoTotal)}</div>
                      <div className='text-xs text-muted-foreground'>{contrato.comissaoPercentual}%</div>
                    </div>
                  </div>
                </TableCell>
                <TableCell>
                  <div className='space-y-1'>
                    <div className='flex justify-between text-xs'>
                      <span>{contrato.parcelasPagas}/{contrato.parcelas}</span>
                      <span>{getProgressPercentage(contrato.parcelasPagas, contrato.parcelas)}%</span>
                    </div>
                    <div className='w-full bg-gray-200 rounded-full h-2'>
                      <div
                        className='bg-blue-600 h-2 rounded-full'
                        style={{ width: `${getProgressPercentage(contrato.parcelasPagas, contrato.parcelas)}%` }}
                      ></div>
                    </div>
                  </div>
                </TableCell>
                <TableCell>
                  <span
                    className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${getStatusColor(contrato.status)}`}
                  >
                    {contrato.status}
                  </span>
                </TableCell>
                <TableCell className='text-right'>
                  <div className='flex items-center justify-end space-x-2'>
                    <Button variant='ghost' size='sm' asChild>
                      <Link to={`/cadastros/contratos/visualizar/${contrato.id}`}>
                        <Eye className='h-4 w-4' />
                      </Link>
                    </Button>
                    
                    <Button variant='ghost' size='sm' asChild>
                      <Link to={`/cadastros/contratos/editar/${contrato.id}`}>
                        <Edit className='h-4 w-4' />
                      </Link>
                    </Button>
                    
                    <Button
                      variant='ghost'
                      size='sm'
                      onClick={() => handleDelete(contrato.id)}
                    >
                      <Trash2 className='h-4 w-4' />
                    </Button>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>

      {/* Paginação - implementar quando necessário */}
      {filteredContratos.length === 0 && (
        <div className='text-center py-8'>
          <p className='text-muted-foreground'>
            {searchTerm ? 'Nenhum contrato encontrado.' : 'Nenhum contrato cadastrado.'}
          </p>
        </div>
      )}
    </div>
  )
}

// src/app/features/register/contracts/contracts-list/contracts-list.component.ts
import { Component, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { RouterModule } from '@angular/router'
import { FormsModule } from '@angular/forms'
import { LucideAngularModule, Plus, Edit, Trash2, Eye, FileText, Calendar, DollarSign, User } from 'lucide-angular'
import { firstValueFrom } from 'rxjs'

import { ButtonComponent } from '@shared/components/ui/button/button.component'
import { SearchBarComponent } from '@shared/components/ui/search-bar/search-bar.component'
import { ConfirmationModalComponent } from '@shared/components/ui/confirmation-modal/confirmation-modal.component'
import { 
  TableComponent, 
  TableHeaderComponent, 
  TableBodyComponent, 
  TableRowComponent, 
  TableHeadComponent, 
  TableCellComponent 
} from '@shared/components/ui/table/table.component'
import { ContractService } from '@core/services/contract.service'
import { EventService } from '@core/services/event.service'
import { ClientService } from '@core/services/client.service'
import type { Contract, Event, Client } from '@shared/models/api.types'
import { formatDateBR } from '@shared/utils/date.utils'

@Component({
  selector: 'app-contracts-list',
  standalone: true,
  imports: [
    CommonModule,
    RouterModule,
    FormsModule,
    LucideAngularModule,
    ButtonComponent,
    SearchBarComponent,
    ConfirmationModalComponent,
    TableComponent,
    TableHeaderComponent,
    TableBodyComponent,
    TableRowComponent,
    TableHeadComponent,
    TableCellComponent
  ],
  templateUrl: './contracts-list.component.html'
})
export class ContractsListComponent implements OnInit {
  readonly PlusIcon = Plus
  readonly EditIcon = Edit
  readonly Trash2Icon = Trash2
  readonly EyeIcon = Eye
  readonly FileTextIcon = FileText
  readonly CalendarIcon = Calendar
  readonly DollarSignIcon = DollarSign
  readonly UserIcon = User

  contracts: Contract[] = []
  events: Event[] = []
  clients: Client[] = []
  searchTerm: string = ''
  filterStatus: string = 'todos'
  isLoading: boolean = true
  error: string = ''
  showDeleteModal: boolean = false
  contractToDelete: Contract | null = null
  isDeleting: boolean = false

  constructor(
    private contractService: ContractService,
    private eventService: EventService,
    private clientService: ClientService
  ) {}

  async ngOnInit(): Promise<void> {
    await this.loadData()
  }

  async loadData(): Promise<void> {
    try {
      this.isLoading = true
      this.error = ''

      const [contractsResponse, eventsResponse, clientsResponse] = await Promise.all([
        firstValueFrom(this.contractService.getContracts()),
        firstValueFrom(this.eventService.getEvents()),
        firstValueFrom(this.clientService.getClients())
      ])

      if (contractsResponse.success && contractsResponse.data) {
        this.contracts = contractsResponse.data
      } else {
        this.error = 'Erro ao carregar contratos'
      }

      if (eventsResponse.success && eventsResponse.data) {
        this.events = eventsResponse.data
      }

      if (clientsResponse.success && clientsResponse.data) {
        this.clients = clientsResponse.data as Client[]
      }
    } catch (err: any) {
      this.error = err.message || 'Erro ao carregar dados'
    } finally {
      this.isLoading = false
    }
  }

  get filteredContracts(): Contract[] {
    let filtered = this.contracts

    // Filter by search term
    if (this.searchTerm) {
      const searchLower = this.searchTerm.toLowerCase()
      filtered = filtered.filter(contract => {
        const event = this.getEventName(contract.eventId)
        const client = this.getClientName(contract.clientId)
        
        return event.toLowerCase().includes(searchLower) ||
               client.toLowerCase().includes(searchLower)
      })
    }

    // Filter by status
    if (this.filterStatus !== 'todos') {
      filtered = filtered.filter(contract => (contract.status || 'Pendente') === this.filterStatus)
    }

    return filtered
  }

  /**
   * @Function - handleDeleteClick
   * @description - Initiates the delete process by opening the confirmation modal and clearing previous errors
   * @author - Vitor Hugo
   * @param - contract: Contract - The contract to be deleted
   * @returns - void
   */
  handleDeleteClick(contract: Contract): void {
    this.contractToDelete = contract
    this.showDeleteModal = true
    this.error = '' // Clear previous errors
  }

  /**
   * @Function - handleConfirmDelete
   * @description - Handles the confirmation of contract deletion with proper error handling for dependency constraints
   * @author - Vitor Hugo
   * @returns - Promise<void>
   */
  async handleConfirmDelete(): Promise<void> {
    if (!this.contractToDelete) return

    try {
      this.isDeleting = true
      const response = await firstValueFrom(
        this.contractService.deleteContract(this.contractToDelete.id)
      )
      if (response.success) {
        this.contracts = this.contracts.filter(contract => contract.id !== this.contractToDelete!.id)
        this.showDeleteModal = false
        this.contractToDelete = null
      } else {
        // Handle error from response when success is false
        this.error = response.message || response.errors?.[0] || 'Erro ao excluir contrato'
        this.showDeleteModal = false
        this.contractToDelete = null
      }
    } catch (err: any) {
      // Extract error message from HTTP error response
      if (err.error?.error?.message) {
        // Backend returned structured error with error.error.message
        this.error = err.error.error.message
      } else if (err.error?.message) {
        // Backend returned error with error.message
        this.error = err.error.message
      } else if (err.message) {
        // Generic error message
        this.error = err.message
      } else {
        // Fallback error message
        this.error = 'Erro ao excluir contrato'
      }
      // Close modal to show error message clearly
      this.showDeleteModal = false
      this.contractToDelete = null
    } finally {
      this.isDeleting = false
    }
  }

  handleCancelDelete(): void {
    this.showDeleteModal = false
    this.contractToDelete = null
  }

  getEventName(eventId: string): string {
    const event = this.events.find(e => e.id === eventId)
    return event?.name || 'Evento não encontrado'
  }

  getClientName(clientId: string): string {
    const client = this.clients.find(c => c.id === clientId)
    return client?.name || 'Cliente não encontrado'
  }

  formatCurrency(value: number): string {
    return new Intl.NumberFormat('pt-BR', {
      style: 'currency',
      currency: 'BRL'
    }).format(value)
  }

  formatDate(dateString: string): string {
    return formatDateBR(dateString)
  }

  getStatusColor(status: string): string {
    switch (status) {
      case 'Assinado':
        return 'bg-green-100 text-green-800'
      case 'Pendente':
        return 'bg-yellow-100 text-yellow-800'
      case 'Cancelado':
        return 'bg-red-100 text-red-800'
      default:
        return 'bg-gray-100 text-gray-800'
    }
  }
}


<div class="space-y-6">
  <!-- Header -->
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-3xl font-bold tracking-tight">Contratos</h1>
      <p class="text-muted-foreground">
        Gerencie os contratos e parcelamentos dos eventos
      </p>
    </div>
    <button appButton variant="outline" routerLink="/cadastros/contratos/novo">
      <lucide-icon [img]="PlusIcon" class="mr-2 h-4 w-4"></lucide-icon>
      Novo Contrato
    </button>
  </div>

  <!-- Filtros -->
  <div class="flex items-center space-x-2">
    <div class="flex-1">
      <app-search-bar
        placeholder="Buscar por evento ou cliente..."
        [(ngModel)]="searchTerm"
      ></app-search-bar>
    </div>
    <select
      [(ngModel)]="filterStatus"
      class="flex h-10 w-48 items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
    >
      <option value="todos">Todos os status</option>
      <option value="Pendente">Pendente</option>
      <option value="Assinado">Assinado</option>
      <option value="Cancelado">Cancelado</option>
    </select>
  </div>

  <!-- Error Message -->
  @if (error) {
    <div class="w-full p-3 text-sm text-red-600 bg-red-50 border border-red-200 rounded-md">
      {{ error }}
    </div>
  }

  <!-- Loading State -->
  @if (isLoading) {
    <div class="flex items-center justify-center h-64">
      <div class="text-center">
        <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary mx-auto"></div>
        <p class="mt-2 text-muted-foreground">Carregando contratos...</p>
      </div>
    </div>
  }

  <!-- Tabela -->
  @if (!isLoading) {
    <div class="rounded-md border">
      <app-table>
        <thead appTableHeader>
          <tr appTableRow>
            <th appTableHead>Evento</th>
            <th appTableHead>Cliente</th>
            <th appTableHead>Valor Total</th>
            <th appTableHead>Status</th>
            <th appTableHead>Data de Criação</th>
            <th appTableHead class="text-right">Ações</th>
          </tr>
        </thead>
        <tbody appTableBody>
          @for (contract of filteredContracts; track contract.id) {
            <tr appTableRow>
              <td appTableCell class="font-medium">
                <div class="flex items-center space-x-2">
                  <lucide-icon [img]="FileTextIcon" class="h-4 w-4 text-muted-foreground"></lucide-icon>
                  <span>{{ getEventName(contract.eventId) }}</span>
                </div>
              </td>
              <td appTableCell>
                <div class="flex items-center space-x-2">
                  <lucide-icon [img]="UserIcon" class="h-4 w-4 text-muted-foreground"></lucide-icon>
                  <span>{{ getClientName(contract.clientId) }}</span>
                </div>
              </td>
              <td appTableCell class="font-medium">
                <div class="flex items-center space-x-2">
                  <lucide-icon [img]="DollarSignIcon" class="h-4 w-4 text-muted-foreground"></lucide-icon>
                  <span>{{ formatCurrency(contract.totalAmount) }}</span>
                </div>
              </td>
              <td appTableCell>
                <span [class]="'inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ' + getStatusColor(contract.status || 'Pendente')">
                  {{ contract.status || 'Pendente' }}
                </span>
              </td>
              <td appTableCell>
                <div class="flex items-center space-x-2">
                  <lucide-icon [img]="CalendarIcon" class="h-4 w-4 text-muted-foreground"></lucide-icon>
                  <span>{{ formatDate(contract.createdAt) }}</span>
                </div>
              </td>
              <td appTableCell class="text-right">
                <div class="flex items-center justify-end space-x-2">
                  <button appButton variant="ghost" size="sm" [routerLink]="['/cadastros/contratos/visualizar', contract.id]">
                    <lucide-icon [img]="EyeIcon" class="h-4 w-4"></lucide-icon>
                  </button>
                  <button 
                    appButton 
                    variant="ghost" 
                    size="sm" 
                    [routerLink]="['/cadastros/contratos/editar', contract.id]"
                  >
                    <lucide-icon [img]="EditIcon" class="h-4 w-4"></lucide-icon>
                  </button>
                  <button
                    appButton
                    variant="ghost"
                    size="sm"
                    (click)="handleDeleteClick(contract)"
                  >
                    <lucide-icon [img]="Trash2Icon" class="h-4 w-4"></lucide-icon>
                  </button>
                </div>
              </td>
            </tr>
          }
        </tbody>
      </app-table>
    </div>
  }

  <!-- Empty State -->
  @if (!isLoading && filteredContracts.length === 0) {
    <div class="text-center py-8">
      <p class="text-muted-foreground">
        {{ searchTerm ? 'Nenhum contrato encontrado.' : 'Nenhum contrato cadastrado.' }}
      </p>
    </div>
  }

  <!-- Confirmation Modal -->
  <app-confirmation-modal
    [isOpen]="showDeleteModal"
    (onClose)="handleCancelDelete()"
    (onConfirm)="handleConfirmDelete()"
    title="Excluir Contrato"
    message="Tem certeza que deseja excluir este contrato? Esta ação não pode ser desfeita."
    confirmText="Excluir"
    cancelText="Cancelar"
    variant="danger"
    [loading]="isDeleting"
  />
</div>
