// src/pages/register/users/UserForm.tsx
import { useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ArrowLeft, Save, X, Eye, EyeOff } from 'lucide-react'
import { Button } from '@/components/ui/button/button'
import { Input } from '@/components/ui/input/input'
import { Label } from '@/components/ui/label/label'

interface UserFormData {
  nome: string
  email: string
  senha: string
  confirmarSenha: string
  perfil: 'Administrador' | 'Atendimento' | 'Vendedor'
  status: 'Ativo' | 'Inativo'
  observacoes: string
}

export default function UserForm() {
  const navigate = useNavigate()
  const { id } = useParams()
  const isEditing = Boolean(id)

  const [formData, setFormData] = useState<UserFormData>({
    nome: '',
    email: '',
    senha: '',
    confirmarSenha: '',
    perfil: 'Atendimento',
    status: 'Ativo',
    observacoes: ''
  })

  const [errors, setErrors] = useState<Partial<UserFormData>>({})
  const [showPassword, setShowPassword] = useState(false)
  const [showConfirmPassword, setShowConfirmPassword] = useState(false)

  const handleInputChange = (field: keyof UserFormData, value: string) => {
    setFormData(prev => ({ ...prev, [field]: value }))
    // Limpar erro do campo quando usuário começar a digitar
    if (errors[field]) {
      setErrors(prev => ({ ...prev, [field]: undefined }))
    }
  }

  const validateForm = (): boolean => {
    const newErrors: Partial<UserFormData> = {}

    if (!formData.nome.trim()) {
      newErrors.nome = 'Nome é obrigatório'
    }

    if (!formData.email.trim()) {
      newErrors.email = 'Email é obrigatório'
    } else if (!/\S+@\S+\.\S+/.test(formData.email)) {
      newErrors.email = 'Email inválido'
    }

    if (!isEditing && !formData.senha.trim()) {
      newErrors.senha = 'Senha é obrigatória'
    } else if (formData.senha && formData.senha.length < 6) {
      newErrors.senha = 'Senha deve ter pelo menos 6 caracteres'
    }

    if (!isEditing && formData.senha !== formData.confirmarSenha) {
      newErrors.confirmarSenha = 'Senhas não coincidem'
    }

    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!validateForm()) {
      return
    }

    // Implementar lógica de salvamento
    console.log('Salvando usuário:', formData)
    
    // Simular salvamento
    setTimeout(() => {
      navigate('/cadastros/usuarios')
    }, 1000)
  }

  const handleCancel = () => {
    navigate('/cadastros/usuarios')
  }

  return (
    <div className='space-y-6'>
      {/* Header */}
      <div className='flex items-center space-x-4'>
        <Button variant='ghost' size='sm' onClick={handleCancel}>
          <ArrowLeft className='h-4 w-4 mr-2' />
          Voltar
        </Button>
        <div>
          <h1 className='text-3xl font-bold tracking-tight'>
            {isEditing ? 'Editar Usuário' : 'Novo Usuário'}
          </h1>
          <p className='text-muted-foreground'>
            {isEditing 
              ? 'Atualize as informações do usuário' 
              : 'Preencha os dados do novo usuário'
            }
          </p>
        </div>
      </div>

      {/* Formulário */}
      <form onSubmit={handleSubmit} className='space-y-6'>
        <div className='grid grid-cols-1 md:grid-cols-2 gap-6'>
          {/* Nome */}
          <div className='space-y-2'>
            <Label htmlFor='nome'>Nome *</Label>
            <Input
              id='nome'
              value={formData.nome}
              onChange={(e) => handleInputChange('nome', e.target.value)}
              placeholder='Nome completo do usuário'
              className={errors.nome ? 'border-red-500' : ''}
            />
            {errors.nome && (
              <p className='text-sm text-red-500'>{errors.nome}</p>
            )}
          </div>

          {/* Email */}
          <div className='space-y-2'>
            <Label htmlFor='email'>Email *</Label>
            <Input
              id='email'
              type='email'
              value={formData.email}
              onChange={(e) => handleInputChange('email', e.target.value)}
              placeholder='email@exemplo.com'
              className={errors.email ? 'border-red-500' : ''}
            />
            {errors.email && (
              <p className='text-sm text-red-500'>{errors.email}</p>
            )}
          </div>

          {/* Perfil */}
          <div className='space-y-2'>
            <Label htmlFor='perfil'>Perfil *</Label>
            <select
              id='perfil'
              value={formData.perfil}
              onChange={(e) => handleInputChange('perfil', e.target.value as 'Administrador' | 'Atendimento' | 'Vendedor')}
              className='flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50'
            >
              <option value='Atendimento'>Atendimento</option>
              <option value='Vendedor'>Vendedor</option>
              <option value='Administrador'>Administrador</option>
            </select>
          </div>

          {/* Status */}
          <div className='space-y-2'>
            <Label htmlFor='status'>Status</Label>
            <select
              id='status'
              value={formData.status}
              onChange={(e) => handleInputChange('status', e.target.value as 'Ativo' | 'Inativo')}
              className='flex h-10 w-full items-center justify-between rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50'
            >
              <option value='Ativo'>Ativo</option>
              <option value='Inativo'>Inativo</option>
            </select>
          </div>

          {/* Senha */}
          <div className='space-y-2'>
            <Label htmlFor='senha'>
              Senha {!isEditing && '*'}
            </Label>
            <div className='relative'>
              <Input
                id='senha'
                type={showPassword ? 'text' : 'password'}
                value={formData.senha}
                onChange={(e) => handleInputChange('senha', e.target.value)}
                placeholder={isEditing ? 'Deixe em branco para manter a senha atual' : 'Digite a senha'}
                className={errors.senha ? 'border-red-500' : ''}
              />
              <Button
                type='button'
                variant='ghost'
                size='sm'
                className='absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent'
                onClick={() => setShowPassword(!showPassword)}
              >
                {showPassword ? (
                  <EyeOff className='h-4 w-4' />
                ) : (
                  <Eye className='h-4 w-4' />
                )}
              </Button>
            </div>
            {errors.senha && (
              <p className='text-sm text-red-500'>{errors.senha}</p>
            )}
          </div>

          {/* Confirmar Senha */}
          {!isEditing && (
            <div className='space-y-2'>
              <Label htmlFor='confirmarSenha'>Confirmar Senha *</Label>
              <div className='relative'>
                <Input
                  id='confirmarSenha'
                  type={showConfirmPassword ? 'text' : 'password'}
                  value={formData.confirmarSenha}
                  onChange={(e) => handleInputChange('confirmarSenha', e.target.value)}
                  placeholder='Confirme a senha'
                  className={errors.confirmarSenha ? 'border-red-500' : ''}
                />
                <Button
                  type='button'
                  variant='ghost'
                  size='sm'
                  className='absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent'
                  onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                >
                  {showConfirmPassword ? (
                    <EyeOff className='h-4 w-4' />
                  ) : (
                    <Eye className='h-4 w-4' />
                  )}
                </Button>
              </div>
              {errors.confirmarSenha && (
                <p className='text-sm text-red-500'>{errors.confirmarSenha}</p>
              )}
            </div>
          )}
        </div>

        {/* Observações */}
        <div className='space-y-2'>
          <Label htmlFor='observacoes'>Observações</Label>
          <textarea
            id='observacoes'
            value={formData.observacoes}
            onChange={(e) => handleInputChange('observacoes', e.target.value)}
            placeholder='Informações adicionais sobre o usuário'
            className='flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50'
            rows={3}
          />
        </div>

        {/* Botões */}
        <div className='flex items-center justify-end space-x-2 pt-6 border-t'>
          <Button type='button' variant='outline' onClick={handleCancel}>
            <X className='h-4 w-4 mr-2' />
            Cancelar
          </Button>
          <Button type='submit' variant='outline'>
            <Save className='h-4 w-4 mr-2' />
            {isEditing ? 'Atualizar' : 'Salvar'}
          </Button>
        </div>
      </form>
    </div>
  )
}

// src/app/features/register/users/user-form/user-form.component.ts
import { Component, OnInit } from '@angular/core'
import { CommonModule } from '@angular/common'
import { Router, ActivatedRoute } from '@angular/router'
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms'
import { LucideAngularModule, ArrowLeft, Save, X } from 'lucide-angular'
import { firstValueFrom } from 'rxjs'

import { ButtonComponent } from '@shared/components/ui/button/button.component'
import { LabelComponent } from '@shared/components/ui/label/label.component'
import { PhoneMaskDirective } from '@shared/directives/phone-mask.directive'
import { phoneValidator } from '@shared/validators'
import { UserService } from '@core/services/user.service'
import type { CreateUserRequest, UpdateUserRequest, UserPermissions } from '@shared/models/api.types'

@Component({
  selector: 'app-user-form',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    LucideAngularModule,
    ButtonComponent,
    LabelComponent,
    PhoneMaskDirective
  ],
  templateUrl: './user-form.component.html'
})
export class UserFormComponent implements OnInit {
  readonly ArrowLeftIcon = ArrowLeft
  readonly SaveIcon = Save
  readonly XIcon = X

  userForm!: FormGroup
  permissionsForm!: FormGroup
  isEditing: boolean = false
  userId: string | null = null
  isLoading: boolean = false
  isLoadingData: boolean = false
  errorMessage: string = ''

  constructor(
    private fb: FormBuilder,
    private userService: UserService,
    private router: Router,
    private route: ActivatedRoute
  ) {
    this.initializeForms()
  }

  /**
   * @Function - initializeForms
   * @description - Initializes the user form and permissions form with validators
   * @author - Vitor Hugo
   * @returns - void
   */
  private initializeForms(): void {
    this.userForm = this.fb.group({
      name: ['', [Validators.required, Validators.minLength(3)]],
      email: ['', [Validators.required, Validators.email]],
      password: ['', []],
      phone: ['', [phoneValidator()]],
      role: ['Auxiliar', [Validators.required]],
      status: ['Ativo', [Validators.required]]
    })

    this.permissionsForm = this.fb.group({
      dashboardView: [true],
      cadastrosCreate: [false],
      cadastrosEdit: [false],
      cadastrosDelete: [false],
      cadastrosView: [true],
      financeiroCreate: [false],
      financeiroEdit: [false],
      financeiroDelete: [false],
      financeiroView: [false],
      relatoriosView: [false],
      relatoriosExport: [false]
    })
  }

  /**
   * @Function - ngOnInit
   * @description - Lifecycle hook that runs when component initializes
   * @author - Vitor Hugo
   * @returns - Promise<void>
   */
  async ngOnInit(): Promise<void> {
    this.userId = this.route.snapshot.paramMap.get('id')
    this.isEditing = !!this.userId

    if (this.isEditing && this.userId) {
      this.userForm.get('password')?.clearValidators()
      this.userForm.get('password')?.updateValueAndValidity()
      await this.loadUser(this.userId)
    } else {
      this.userForm.get('password')?.setValidators([Validators.required, Validators.minLength(6)])
      this.userForm.get('password')?.updateValueAndValidity()
    }
  }

  /**
   * @Function - loadUser
   * @description - Loads user data from API and populates the form
   * @author - Vitor Hugo
   * @param - id: string - User ID to load
   * @returns - Promise<void>
   */
  async loadUser(id: string): Promise<void> {
    try {
      this.isLoadingData = true
      const response = await firstValueFrom(this.userService.getUserById(id))
      if (response.success && response.data) {
        const user = response.data
        this.userForm.patchValue({
          name: user.name,
          email: user.email,
          phone: user.phone || '',
          role: user.role,
          status: user.status
        })

        if (user.permissions) {
          this.permissionsForm.patchValue({
            dashboardView: user.permissions.dashboard.view,
            cadastrosCreate: user.permissions.cadastros.create,
            cadastrosEdit: user.permissions.cadastros.edit,
            cadastrosDelete: user.permissions.cadastros.delete,
            cadastrosView: user.permissions.cadastros.view,
            financeiroCreate: user.permissions.financeiro.create,
            financeiroEdit: user.permissions.financeiro.edit,
            financeiroDelete: user.permissions.financeiro.delete,
            financeiroView: user.permissions.financeiro.view,
            relatoriosView: user.permissions.relatorios.view,
            relatoriosExport: user.permissions.relatorios.export
          })
        }
      }
    } catch (error: any) {
      this.errorMessage = error.message || 'Erro ao carregar usuário'
    } finally {
      this.isLoadingData = false
    }
  }

  /**
   * @Function - getPermissionsObject
   * @description - Converts form values to UserPermissions object
   * @author - Vitor Hugo
   * @returns - UserPermissions - Structured permissions object
   */
  private getPermissionsObject(): UserPermissions {
    const perms = this.permissionsForm.value
    return {
      dashboard: {
        view: perms.dashboardView
      },
      cadastros: {
        create: perms.cadastrosCreate,
        edit: perms.cadastrosEdit,
        delete: perms.cadastrosDelete,
        view: perms.cadastrosView
      },
      financeiro: {
        create: perms.financeiroCreate,
        edit: perms.financeiroEdit,
        delete: perms.financeiroDelete,
        view: perms.financeiroView
      },
      relatorios: {
        view: perms.relatoriosView,
        export: perms.relatoriosExport
      }
    }
  }

  /**
   * @Function - handleSubmit
   * @description - Handles form submission for creating or updating a user
   * @author - Vitor Hugo
   * @returns - Promise<void>
   */
  async handleSubmit(): Promise<void> {
    if (this.userForm.invalid) {
      Object.keys(this.userForm.controls).forEach(key => {
        this.userForm.controls[key].markAsTouched()
      })
      return
    }

    this.isLoading = true
    this.errorMessage = ''

    try {
      const formValue = this.userForm.value
      
      if (this.isEditing && this.userId) {
        const updateData: UpdateUserRequest = {
          name: formValue.name,
          email: formValue.email,
          phone: formValue.phone || undefined,
          status: formValue.status
        }
        
        const response = await firstValueFrom(
          this.userService.updateUser(this.userId, updateData)
        )
        
        if (response.success) {
          const permissions = this.getPermissionsObject()
          await firstValueFrom(
            this.userService.updateUserPermissions(this.userId, { permissions })
          )
          this.router.navigate(['/cadastros/usuarios'])
        } else {
          this.errorMessage = 'Erro ao atualizar usuário'
        }
      } else {
        const createData: CreateUserRequest = {
          name: formValue.name,
          email: formValue.email,
          password: formValue.password,
          phone: formValue.phone || undefined,
          role: formValue.role,
          permissions: this.getPermissionsObject()
        }
        
        const response = await firstValueFrom(
          this.userService.createUser(createData)
        )
        
        if (response.success) {
          this.router.navigate(['/cadastros/usuarios'])
        } else {
          this.errorMessage = 'Erro ao criar usuário'
        }
      }
    } catch (error: any) {
      if (error.error?.error?.message) {
        this.errorMessage = error.error.error.message
      } else if (error.error?.message) {
        this.errorMessage = error.error.message
      } else {
        this.errorMessage = error.message || 'Erro ao salvar usuário'
      }
    } finally {
      this.isLoading = false
    }
  }

  /**
   * @Function - handleCancel
   * @description - Navigates back to users list
   * @author - Vitor Hugo
   * @returns - void
   */
  handleCancel(): void {
    this.router.navigate(['/cadastros/usuarios'])
  }

  /**
   * @Function - getFieldError
   * @description - Returns the error message for a form field
   * @author - Vitor Hugo
   * @param - fieldName: string - Name of the form field
   * @returns - string - Error message or empty string
   */
  getFieldError(fieldName: string): string {
    const field = this.userForm.get(fieldName)
    if (field?.hasError('required') && field.touched) {
      const fieldLabels: Record<string, string> = {
        name: 'Nome',
        email: 'Email',
        password: 'Senha',
        phone: 'Telefone',
        role: 'Função'
      }
      return `${fieldLabels[fieldName] || 'Campo'} é obrigatório`
    }
    if (field?.hasError('email') && field.touched) {
      return 'Email inválido'
    }
    if (field?.hasError('minlength') && field.touched) {
      if (fieldName === 'password') {
        return 'Senha deve ter pelo menos 6 caracteres'
      }
      return 'Nome deve ter pelo menos 3 caracteres'
    }
    if (field?.hasError('invalidPhone') && field.touched) {
      return 'Telefone inválido. Use o formato (XX) XXXXX-XXXX'
    }
    return ''
  }

  /**
   * @Function - hasError
   * @description - Checks if a form field has an error and has been touched
   * @author - Vitor Hugo
   * @param - fieldName: string - Name of the form field
   * @returns - boolean - True if field has error and is touched
   */
  hasError(fieldName: string): boolean {
    const field = this.userForm.get(fieldName)
    return !!(field?.invalid && field.touched)
  }

  /**
   * @Function - setRolePermissions
   * @description - Sets default permissions based on selected role
   * @author - Vitor Hugo
   * @param - event: Event - Change event from role select
   * @returns - void
   */
  setRolePermissions(event: Event): void {
    const role = (event.target as HTMLSelectElement).value
    
    if (role === 'Administrador') {
      this.permissionsForm.patchValue({
        dashboardView: true,
        cadastrosCreate: true,
        cadastrosEdit: true,
        cadastrosDelete: true,
        cadastrosView: true,
        financeiroCreate: true,
        financeiroEdit: true,
        financeiroDelete: true,
        financeiroView: true,
        relatoriosView: true,
        relatoriosExport: true
      })
    } else {
      this.permissionsForm.patchValue({
        dashboardView: true,
        cadastrosCreate: false,
        cadastrosEdit: false,
        cadastrosDelete: false,
        cadastrosView: true,
        financeiroCreate: false,
        financeiroEdit: false,
        financeiroDelete: false,
        financeiroView: false,
        relatoriosView: false,
        relatoriosExport: false
      })
    }
  }
}


<div class="space-y-6">
  <!-- Header -->
  <div class="flex items-center space-x-4">
    <button appButton variant="ghost" size="sm" (click)="handleCancel()">
      <lucide-icon [img]="ArrowLeftIcon" class="h-4 w-4 mr-2"></lucide-icon>
      Voltar
    </button>
    <div>
      <h1 class="text-3xl font-bold tracking-tight">
        {{ isEditing ? 'Editar Usuário' : 'Novo Usuário' }}
      </h1>
      <p class="text-muted-foreground">
        {{ isEditing ? 'Atualize as informações do usuário' : 'Preencha os dados do novo usuário' }}
      </p>
    </div>
  </div>

  <!-- Loading State -->
  @if (isLoadingData) {
    <div class="text-center py-8">
      <p class="text-muted-foreground">Carregando dados do usuário...</p>
    </div>
  }

  <!-- Error Message -->
  @if (errorMessage) {
    <div class="w-full p-3 text-sm text-red-600 bg-red-50 border border-red-200 rounded-md">
      {{ errorMessage }}
    </div>
  }

  <!-- Formulário -->
  @if (!isLoadingData) {
    <form [formGroup]="userForm" (ngSubmit)="handleSubmit()" class="space-y-6">
    <!-- Dados Básicos -->
    <div class="space-y-4">
      <h2 class="text-xl font-semibold">Dados Básicos</h2>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        <!-- Nome -->
        <div class="space-y-2">
          <label appLabel htmlFor="name">Nome *</label>
          <input
            type="text"
            id="name"
            formControlName="name"
            placeholder="Nome completo do usuário"
            [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('name') ? 'border-red-500' : '')"
          />
          @if (hasError('name')) {
            <p class="text-sm text-red-500">{{ getFieldError('name') }}</p>
          }
        </div>

        <!-- Email -->
        <div class="space-y-2">
          <label appLabel htmlFor="email">Email *</label>
          <input
            type="email"
            id="email"
            formControlName="email"
            placeholder="email@exemplo.com"
            [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('email') ? 'border-red-500' : '')"
          />
          @if (hasError('email')) {
            <p class="text-sm text-red-500">{{ getFieldError('email') }}</p>
          }
        </div>

        <!-- Senha -->
        <div class="space-y-2">
          <label appLabel htmlFor="password">
            {{ isEditing ? 'Senha (deixe em branco para não alterar)' : 'Senha *' }}
          </label>
          <input
            type="password"
            id="password"
            formControlName="password"
            placeholder="••••••••"
            [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('password') ? 'border-red-500' : '')"
          />
          @if (hasError('password')) {
            <p class="text-sm text-red-500">{{ getFieldError('password') }}</p>
          }
        </div>

        <!-- Telefone -->
        <div class="space-y-2">
          <label appLabel htmlFor="phone">Telefone</label>
          <input
            type="tel"
            id="phone"
            formControlName="phone"
            appPhoneMask
            placeholder="(11) 99999-9999"
            [class]="'flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm ' + (hasError('phone') ? 'border-red-500' : '')"
          />
          @if (hasError('phone')) {
            <p class="text-sm text-red-500">{{ getFieldError('phone') }}</p>
          }
        </div>

        <!-- Função -->
        <div class="space-y-2">
          <label appLabel htmlFor="role">Função *</label>
          <select
            id="role"
            formControlName="role"
            (change)="setRolePermissions($event)"
            [disabled]="isEditing"
            class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm"
          >
            <option value="Auxiliar">Auxiliar</option>
            <option value="Administrador">Administrador</option>
          </select>
        </div>

        <!-- Status (apenas na edição) -->
        @if (isEditing) {
          <div class="space-y-2">
            <label appLabel htmlFor="status">Status *</label>
            <select
              id="status"
              formControlName="status"
              class="flex h-9 w-full rounded-md border border-input bg-transparent px-3 py-1 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm"
            >
              <option value="Ativo">Ativo</option>
              <option value="Inativo">Inativo</option>
            </select>
          </div>
        }
      </div>
    </div>

    <!-- Permissões -->
    <div class="space-y-4 pt-6 border-t">
      <h2 class="text-xl font-semibold">Permissões</h2>
      <div [formGroup]="permissionsForm" class="space-y-6">
        <!-- Dashboard -->
        <div class="space-y-3">
          <h3 class="text-sm font-semibold text-gray-700">Dashboard</h3>
          <div class="flex items-center space-x-2">
            <input
              type="checkbox"
              id="dashboardView"
              formControlName="dashboardView"
              class="rounded border-gray-300 text-primary focus:ring-primary"
            />
            <label htmlFor="dashboardView" class="text-sm">Visualizar</label>
          </div>
        </div>

        <!-- Cadastros -->
        <div class="space-y-3">
          <h3 class="text-sm font-semibold text-gray-700">Cadastros</h3>
          <div class="grid grid-cols-2 md:grid-cols-4 gap-3">
            <div class="flex items-center space-x-2">
              <input
                type="checkbox"
                id="cadastrosView"
                formControlName="cadastrosView"
                class="rounded border-gray-300 text-primary focus:ring-primary"
              />
              <label htmlFor="cadastrosView" class="text-sm">Visualizar</label>
            </div>
            <div class="flex items-center space-x-2">
              <input
                type="checkbox"
                id="cadastrosCreate"
                formControlName="cadastrosCreate"
                class="rounded border-gray-300 text-primary focus:ring-primary"
              />
              <label htmlFor="cadastrosCreate" class="text-sm">Criar</label>
            </div>
            <div class="flex items-center space-x-2">
              <input
                type="checkbox"
                id="cadastrosEdit"
                formControlName="cadastrosEdit"
                class="rounded border-gray-300 text-primary focus:ring-primary"
              />
              <label htmlFor="cadastrosEdit" class="text-sm">Editar</label>
            </div>
            <div class="flex items-center space-x-2">
              <input
                type="checkbox"
                id="cadastrosDelete"
                formControlName="cadastrosDelete"
                class="rounded border-gray-300 text-primary focus:ring-primary"
              />
              <label htmlFor="cadastrosDelete" class="text-sm">Deletar</label>
            </div>
          </div>
        </div>

        <!-- Financeiro -->
        <div class="space-y-3">
          <h3 class="text-sm font-semibold text-gray-700">Financeiro</h3>
          <div class="grid grid-cols-2 md:grid-cols-4 gap-3">
            <div class="flex items-center space-x-2">
              <input
                type="checkbox"
                id="financeiroView"
                formControlName="financeiroView"
                class="rounded border-gray-300 text-primary focus:ring-primary"
              />
              <label htmlFor="financeiroView" class="text-sm">Visualizar</label>
            </div>
            <div class="flex items-center space-x-2">
              <input
                type="checkbox"
                id="financeiroCreate"
                formControlName="financeiroCreate"
                class="rounded border-gray-300 text-primary focus:ring-primary"
              />
              <label htmlFor="financeiroCreate" class="text-sm">Criar</label>
            </div>
            <div class="flex items-center space-x-2">
              <input
                type="checkbox"
                id="financeiroEdit"
                formControlName="financeiroEdit"
                class="rounded border-gray-300 text-primary focus:ring-primary"
              />
              <label htmlFor="financeiroEdit" class="text-sm">Editar</label>
            </div>
            <div class="flex items-center space-x-2">
              <input
                type="checkbox"
                id="financeiroDelete"
                formControlName="financeiroDelete"
                class="rounded border-gray-300 text-primary focus:ring-primary"
              />
              <label htmlFor="financeiroDelete" class="text-sm">Deletar</label>
            </div>
          </div>
        </div>

        <!-- Relatórios -->
        <div class="space-y-3">
          <h3 class="text-sm font-semibold text-gray-700">Relatórios</h3>
          <div class="grid grid-cols-2 md:grid-cols-4 gap-3">
            <div class="flex items-center space-x-2">
              <input
                type="checkbox"
                id="relatoriosView"
                formControlName="relatoriosView"
                class="rounded border-gray-300 text-primary focus:ring-primary"
              />
              <label htmlFor="relatoriosView" class="text-sm">Visualizar</label>
            </div>
            <div class="flex items-center space-x-2">
              <input
                type="checkbox"
                id="relatoriosExport"
                formControlName="relatoriosExport"
                class="rounded border-gray-300 text-primary focus:ring-primary"
              />
              <label htmlFor="relatoriosExport" class="text-sm">Exportar</label>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Botões -->
    <div class="flex items-center justify-end space-x-2 pt-6 border-t">
      <button appButton type="button" variant="outline" (click)="handleCancel()">
        <lucide-icon [img]="XIcon" class="h-4 w-4 mr-2"></lucide-icon>
        Cancelar
      </button>
      <button appButton type="submit" variant="outline" [disabled]="isLoading">
        <lucide-icon [img]="SaveIcon" class="h-4 w-4 mr-2"></lucide-icon>
        {{ isLoading ? 'Salvando...' : (isEditing ? 'Atualizar' : 'Salvar') }}
      </button>
    </div>
    </form>
  }
</div>
